### ISSUE TITLE
🚧「Next.jsで○○を作ろう」を執筆

### ISSUE THREAD

**Issue by t-yng** [yytypescript/book#113]
## 対象ページ
https://book.yyts.org/tutorials/nextjs

**Comment by suin** [comment]
何を作ったらいいか念の為アンケート実施
[suin・「Next.jsを使ってる人、主にどういったものを作るのに使ってますか？」 / Twitter](https://twitter.com/suin/status/1475193516901158913)

**Comment by t-yng** [comment]
猫画像をランダムに表示するアプリを作ることにしました

- 利用するAPI: https://docs.thecatapi.com/
- 画像取得API: https://api.thecatapi.com/v1/images/search

**Comment by t-yng** [comment]
#414 で執筆完了
