### ISSUE TITLE
🚧「コールバック関数 (callback functions)」を執筆

### ISSUE THREAD

**Issue by t-yng** [yytypescript/book#124]
## 対象ページ
https://book.yyts.org/reference/functions/callback-functions

**Comment by suin** [comment]
書きたいことメモ

コールバック関数は、関数に引数として渡される関数で、この渡された関数は渡した先で実行されます。

コールバック関数という言語機能や構文がJavaScriptに設けられているわけではありません。JavaScriptには、2つの仕様「関数は引数になれる」「引数として受け取った関数は呼び出せる」があります。この仕様を応用したデザインパターンがコールバック関数です。

例: コールバック関数をコールバック関数を受け取る関数に渡すサンプルコード

同期型のコールバック関数

- 目的: 処理の一部を移譲する
- 例: Array.find

非同期型のコールバック関数

- 目的: JavaScriptでブロッキングが発生しないようにするため
- 例、setTimeout、fetchなど

Q&A1「同期型のコールバック関数に非同期関数も渡せる？」「渡しても問題ない？」

Q&A2「コールバック関数を受け取る関数を作るとき、その引数の型定義どう書く？」

**Comment by t-yng** [comment]
こちら着手したいと思います。
