### ISSUE TITLE
🚧「unknown型」を執筆

### ISSUE THREAD

**Issue by t-yng** [yytypescript/book#137]
## 対象ページ
https://book.yyts.org/reference/statements/unknown

**Comment by suin** [comment]
アウトラインです。これをもとに執筆してほしいです。

links→内部リンク
keywords→できるだけ盛り込みたい検索用ワード

## unknownとは

解決する疑問: unknownとはいったい何？

- unknownはTypeScriptの特別な型
- unknown型にはどんな型も代入できる
- unknown型はどんな型にも代入できない(anyを除く)
- 代入しようとするとコンパイルエラーになる

keywords: TypeScript、型、代入

## unknownの用例

解決する疑問: そんな型どこで使うの？

- anyよりも型安全なコードになる
- JSON.parseの戻り値の型注釈に
- 型ガード関数に 

links: 型ガード関数

keywords: 用法, 使い方

## unknownの絞り込み

解決する疑問: unknownの変数が返ってきた。使うとエラーになる。どうしたらいい？

- unknownの値を処理するには、型を絞り込む
- 絞り込むには、型ガードを使う。

links: 型ガード、制御フロー分析、型の絞り込み

keywords: 判定、チェック、キャスト、変換、型ガード、type predicate

### unknownから文字列型への絞り込み

解決する疑問: unknownを文字列型に絞り込みたい

- `if (typeof value === 'string')`

keywords: string 文字列型

### unknownから配列型への絞り込み

解決する疑問: unknownから配列型(`number[]`)に絞り込みたい

- `Array.isArray`を使う
- さらに、ループの中でtypeofを使う

keywords: array 配列

### unknownからオブジェクト型への絞り込み

解決する疑問: unknownのプロパティにアクセスできない

- typeofでしぼりこむ
- プロパティごとにtypeofする

keywords: オブジェクト、プロパティ

### unknownと型アサーション

- 普通は型アサーションは一定の制約がある (string as 'a'はOKだが、string as numberは無理)
- unknownはどんな型にも型アサーションできる
- unknownを型アサーションするのは楽だが、型安全性は犠牲になるよ

links: 型アサーション「as」

## unknownとcatch

解決する疑問: catch(e)のeがunknownでハンドリングできないんだが

- useUnknownInCatchVariablesがtrueだとunknownになる

TODO: 順当にいったら型ガードで絞り込むだけど、ベストプラクティスありません？

links: 例外処理、useUnknownInCatchVariables

keywords: catch, 例外、エラー, ハンドリング

## unknownとanyの違い

解決する疑問: unknownとanyって似てるけどどう違う？

- ひとことでunknownは型安全なany
- anyにしたくなったらunknownを使おう

links: unknownとanyの違い

keywords: any 違い, anyの代わり
