### ISSUE TITLE
🚧「インデックスアクセス型(indexed access type)」を執筆

### ISSUE THREAD

**Issue by t-yng** [yytypescript/book#139]
## 対象ページ
https://book.yyts.org/reference/type-reuse/indexed-access-types

**Comment by suin** [comment]
# アウトライン

アウトラインです。これをもとに執筆してほしいです。他に追加すべきことがあれば追加してください😌

## 導入(インデックスアクセス型とは)

- TypeScriptのインデックスアクセス型(indexed access type)は、別の型のプロパティの型を参照する記法。
	- サンプルコード

*盛り込むキーワード: TypeScript、インデックスアクセス型、indexed access type*

## インデックスアクセス型の構文

```ts
type X = オブジェクト型["プロパティ名"]
```

## 配列型の要素の型を参照する

- インデックスアクセス型は配列型の要素の型を参照するために使える。
	- サンプルコード

*盛り込むキーワード: 配列型、要素、インデックスアクセス型*
