### ISSUE TITLE
DocSearchでサイト内検索を実装する

### ISSUE THREAD

**Issue by t-yng** [yytypescript/book#210]
## 概要
最近のOSSの公式ドキュメントでよく見かける文書内のキーワード検索を導入したい

## 目的
ドキュメントを読んでいて、出てきたキーワードについて復習したい時など別のページに飛んで確認したい時が多々ある。

## 方法

DocSearchを使う

## DocSearchをDocusaurusで使う方法

https://docusaurus.io/docs/search

## DocSearchのドキュメント

https://docsearch.algolia.com/docs/what-is-docsearch/

## DocSearchのappId, apiKeyなど

```
   appId: 5N3JHNPACB,

    apiKey: 99655de886960eadb0eca65591529110,

    indexName: typescriptbook,
```

## Algoliaのダッシュボード

https://www.algolia.com/apps/5N3JHNPACB/dashboard

## Crawler by algoliaのダッシュボード

https://crawler.algolia.com/admin/crawlers/faf24cc0-b2b2-49fb-af08-f03cd8a0962e/overview

**Comment by suin** [comment]
ほしいですよね！

**Comment by t-yng** [comment]
やっぱり、欲しいですね！

**Comment by suin** [comment]
DocusaurusではAlgolia DocSearch を推奨しているっぽいです。 https://docusaurus.io/docs/search

**Comment by t-yng** [comment]
毎日夜の10:00にクローラーを実行するスケジュールを設定
