### ISSUE TITLE
議論: ハードプライベート(プライベートクラス機能)を解説に盛り込むべきか？

### ISSUE THREAD

**Issue by suin** [yytypescript/book#242]
そろそろ本書でもハードプライベート(プライベートクラス機能)を解説したほうがいいんですかね？

意見募集します！

## プライベートクラス機能とは

- ECMAScript 2022でリリース予定のJavaScriptネイティブのプライベート
- `#`ではじまるフィールドやメソッドがプライベートになる
- TypeScriptでは従来の`private`修飾子によるソフトプライベートと区別してハードプライベートと呼ばれる

```ts
// TypeScript
class Foo {
  #someField?: string;
  static #someStaticMethod(): void {}
  #someMethod(): void {}
  get #someValue(): number {
    return 100;
  }
}
```

```js
// JavaScript
class Foo {
    #someField;
    static #someStaticMethod() { }
    #someMethod() { }
    get #someValue() {
        return 100;
    }
}
```

## プライベートクラス機能の履歴

- 2020-02-20: [TypeScript 3.8でフィールドのハードプライベートに対応](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-8.html#ecmascript-private-fields)
- 2021-03-26: [TypeScript 4.3でハードプライベートがメソッドにも拡大](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-3.html#ecmascript-private-class-elements)
- 2021-04-20: [Class Fieldsがstage 4になり、ES2022に盛り込まれる予定](https://github.com/tc39/proposals/commit/5435781b2f252945694618f22f5956f17a639d3a)
- 2022-06-??: ES2022がリリースされる予定

### 解説

- 解説ページはない
- [索引:記号とキーワード](https://typescriptbook.jp/symbols-and-keywords#-%E3%83%97%E3%83%A9%E3%82%A4%E3%83%99%E3%83%BC%E3%83%88%E3%83%97%E3%83%AD%E3%83%91%E3%83%86%E3%82%A3-private-property-js)では`#`が紹介されている

### 取り扱わなかった理由

- プロポーザルがstage 3だった。
- TypeScriptがメソッドのハードプライベートに対応していなかった。
- 実務では使われていなそうだった。

## エコシステム

- Denoでは[使い始めている](https://github.com/denoland/deno_std/blob/6b4ba7c925f165ef89c3c71ca2ffad72091aa947/http/server.ts#L55-L61)
- React→まだ
- Next→まだ
- angular/angular →まだ
- puppeteer/puppeteer → まだ
- reduxjs/redux → まだ

## Twitterアンケート

- [ES2022で導入予定のプライベートクラス機能、実務で使ってますか？](https://twitter.com/suin/status/1474337857473236999)

## 関連情報

- [プライベートクラス機能 - JavaScript | MDN](https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Classes/Private_class_fields)
- [TypeScript 3.8の新機能「ハードプライベート」と従来の「ソフトプライベート」を比べてみた - Qiita](https://qiita.com/suin/items/fafc81be5a7222648863) ── 古い情報も多々あるので要注意

**Comment by jamashita** [comment]
取り扱ってもいいと思います！

**Comment by suin** [comment]
そろそろ取り扱ってもいいと思います。

理由

- TSがメソッドのプライベートにも対応した
- ブラウザも対応している
- 長い目で見たら、そのうち役にたつページになるだろうから、今から作っておいてもいいと思うから
- JS標準のプライベートなので、ハードプライベートに寄せていく流れができそうだから
