### ISSUE TITLE
誤植:「出来ごと」→「出来事」

### ISSUE THREAD

**Issue by schabibi1** [yytypescript/book#267]
### 誤字の箇所
[「失われた10年」](https://typescriptbook.jp/overview/before-typescript#%E5%A4%B1%E3%82%8F%E3%82%8C%E3%81%9F10%E5%B9%B4)内の、最も最後尾の行に以下の誤字:

このような **出来こと** があり、一度は大規模化を目指したJavaScriptでしたが、その目標を達成できないまま、約10年の年月が流れることとなります。

### 修正提案
「このような **出来事** 」

**Comment by suin** [comment]
note: textlintによる過剰修正の可能性があります。その場合、prhの設定を直す必要があります。
https://github.com/yytypescript/book/blob/59e899e0adb2c7f98efe745f695fd82b6e17f861/prh/js-primer.yml#L669

**Comment by suin** [comment]
note: textlintによる過剰修正の可能性があります。その場合、prhの設定を直す必要があります。
https://github.com/yytypescript/book/blob/59e899e0adb2c7f98efe745f695fd82b6e17f861/prh/js-primer.yml#L669
