### ISSUE TITLE
非同期処理の章を消す

### ISSUE THREAD

**Issue by suin** [yytypescript/book#272]
記事分割のために用意しておいた下記ページを消します。

<img width="275" alt="20220114_201129" src="https://user-images.githubusercontent.com/855338/149506430-08c39df1-ddc1-43f1-84dc-77742d849615.png">

## 理由

1. [Promise / async / await ](https://typescriptbook.jp/reference/promise-async-await)があるため、消しても問題ない
2. 記事分割するにしても、 #271 を踏まえてからやったほうがいいから

**Comment by jamashita** [comment]
関連ページをすべてりりーすしたため、閉じることといたします
