### ISSUE TITLE
質問: JSXでclass属性を使わずにclassName属性を使うのは、classがJavaScriptの予約語だからですか？

### ISSUE THREAD

**Issue by hidenoriohnishi** [yytypescript/book#276]
「class属性は使わない」の所ですが、"class"はjsの予約語であり、jsx上で扱うのに適さないため使われないのではないでしょうか？

関連ページ: https://typescriptbook.jp/tutorials/react-like-button-tutorial

**Comment by suin** [comment]
@hidenoriohnishi `class`がJavaScriptの予約語だからそれを避けるために`className`を使った設計にしたというわけではなく、DOM APIの[className](https://developer.mozilla.org/en-US/docs/Web/API/Element/className)に[合わせた](https://github.com/facebook/react/issues/4331#issuecomment-120170033)というのが理由です。

もしJavaScriptの予約語だから使われないという設計方針なのであれば、[default属性](https://developer.mozilla.org/ja/docs/Web/HTML/Element/track#attr-default)も別名にマッピングされていないのと辻褄が合わないと思います。

ちなみに、JSXで[`class`属性を使うのは違反ではありません](https://babeljs.io/repl/#?browsers=defaults%2C%20not%20ie%2011%2C%20not%20ie_mob%2011&build=&builtIns=false&corejs=3.6&spec=false&loose=false&code_lz=G4QwTgBANiBGCmUIF4IB4YKRAxjAzvsgESzjED0AfANxA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Creact%2Cstage-2&prettier=false&targets=&version=7.16.9&externalPlugins=&assumptions=%7B%7D)。

WebComponentsによっては逆に`className`は使えず、[`class`を使わないとならない場合もあります](https://ja.reactjs.org/docs/web-components.html#using-web-components-in-react)。

**Comment by hidenoriohnishi** [comment]
ありがとうございます。なるほど確かにそうですね。英語のサイトなどで「予約語のため」と説明しているサイトが多かったのですがすっきりしました。
