### ISSUE TITLE
(インターセクション型) 不要なReadonlyを取り除く

### ISSUE THREAD

**Issue by shoma3571** [yytypescript/book#302]
はじめまして。インターセクション型の合成について質問させていただきます。
以下の画像の部分で`Readonly<T>`がついているのはなぜでしょうか。
![image](https://user-images.githubusercontent.com/60056125/153691808-0169aec6-f2c3-4e05-b0be-918c81c50a3e.png)

最初に定義されているものであれば、`sample.id = '2';`のように書き換えることが可能だと認識しています。
```ts
// 本文で書かれているものの簡略版です。
type Parameter = {
  id: string;
  index?: number;
  active: boolean;
  photo?: string;
};

const sample: Parameter = { id: '1', active: false }; 
sample.id = '2';
```
ですが、最後のものは`Readonly<Mandatory & Optional>`となっているので、書き換えることができないと思っています。
本当に同じものを作るとしたら`Mandatory & Optional`でいいのではないかとかんじました。

とても細かなところですが、よろしくお願いいたします。

関連ページ: https://typescriptbook.jp/reference/values-types-variables/intersection

**Comment by suin** [comment]
ご指摘ありがとうございます！Readonlyを付けないほうが説明にあっていそうです😌

「これで最初に定義したParameterと同じタイプエイリアスができました。」と記載されていますが、最初に定義したParameterはreadonlyではないため。

**Comment by shoma3571** [comment]
回答ありがとうございます！
すっきりしました！

**Comment by suin** [comment]
このissueを質問から改善にタイプ変更します。

理由:

執筆した@jamashita さんに確認したところ、

- `Readonly`をつけなければならないところではないよう
- ここの`Readonly`には強いメッセージがない

との回答を得られたため。
