### ISSUE TITLE
誤植: サンプルコード内の「// @log: 1 2」→「// @log: 0 0」 (分割代入引数)

### ISSUE THREAD

**Issue by sitogi** [yytypescript/book#306]
https://typescriptbook.jp/reference/functions/destructuring-assignment-parameters

`分割代入引数の全体の既定値` のサンプルコードで、指定した規定値が `{ a: 0, b: 0 }` であるにも関わらず、出力結果の記載が `1 2` となっています。

**Comment by jamashita** [comment]
PRが出ていましたのでそちらを取り込みました。
