### ISSUE TITLE
オブジェクトのシャローコピー + Map・Set + スプレッド演算子の説明を改善する

### ISSUE THREAD

**Issue by suin** [yytypescript/book#307]
## 概要

- [オブジェクトを浅くコピーする]にて、スプレッド演算子を`Map`や`Set`に適用する方法が説明されている。
- `Map`や`Set`は`...`を使わないほうが簡単にシャローコピーできる。 
  - PR #304 にてご指摘頂いた。
  - ただし、このPRはそのままだと文脈的に合わなそう。

_現状_

![20220218_201350](https://user-images.githubusercontent.com/855338/154672450-8c048830-057b-4f5c-95d0-54f1206827be.png)

_PR #304 の変更_

![20220218_201317](https://user-images.githubusercontent.com/855338/154673038-acb52238-98dd-4874-8fca-3bc0dc8f4e77.png)

## 論点: `Map`や`Set`をどう説明するか？

[オブジェクトを浅くコピーする]で`Map`、`Set`を取り上げるか？取り上げるならどう直すべきか？

### アイディア1: Map、Setは割愛する

- 説明をなくすパターンです。

### アイディア2: `...`以外でシャローコピーできる場合の説明を追加する

- 「...について」でMap Setを説明するから問題になるという側面もありそうです。
- たとえば「コンストラクタを用いたシャローコピー」のようなセクションを作り、MapやSetは`...`と分けて説明すると自然です。

### アイディア3: `...`で取り上げるものの、実はコンストラクタでコピーしたほうが簡単と伝える

- 「...について」でのMap Setはそのままにするが、
- 「ただ、Map、Setはコンストラクタでコピーしたほうが簡単です」と注意書きを添える。

**Comment by suin** [comment]
個人的には、2がいいと思います。

知らずに`new Map(...oldMap)`を書いていた時期があったので、MapにはMapのシャローコピーのやりかたがあると説明されたほうが、僕と同じ遠回りをしなくていいからです。

**Comment by bababax11** [comment]
PRのままでは、説明の文脈が合わないので、どうにかしたいとは思っていました。

私もアイデア2がいいと思っています。
この用法の`…`の説明にMapやSetを使う必然性があまりない(別の簡便なシャローコピーの方法があり、回りくどい方法を広めてしまう可能性がある)ので、やるとしてもその方法を使うのがベストとなる例を挙げるべき) だと考えます。

Mapのシャローコピーのやり方に関しては別セクションで説明すべきな感があります。
