### ISSUE TITLE
質問です: 「キャストと型アサーションの違いについて」

### ISSUE THREAD

**Issue by yo-goto** [yytypescript/book#316]
https://github.com/yytypescript/book/blob/b79390998157052066cc5472b4bd5bd736942f80/docs/reference/generics/type-parameter-constraint.md#L24
この行において「// any にキャストすればコンパイルエラーは回避できる」とありますが、

[型アサーション「as」(type assertion)』](https://typescriptbook.jp/reference/values-types-variables/type-assertion-as#%E5%9E%8B%E3%82%A2%E3%82%B5%E3%83%BC%E3%82%B7%E3%83%A7%E3%83%B3%E3%81%A8%E3%82%AD%E3%83%A3%E3%82%B9%E3%83%88%E3%81%AE%E9%81%95%E3%81%84)の項目で型アサーションとキャストの違いとして、"キャストとは、実行時にある値の型を別の型に変換することです。型アサーションは、実行時に影響しません。"と書いてあるので「any にキャスト」ではなく「any に型アサーション」ではないでしょうか? 自分の理解が間違っていたらすみません。

また、実行時に別の型への変換は具体的にどのようになるのでしょうか? 教えていただけると幸いです。

**Comment by suin** [comment]
@yo-goto ご認識であってます。キャストではなく型アサーションです。(本書の記載不備)

実行時の別の型への変換は、値によってやりかたは様々です。一例をあげると、

- テンプレートリテラルで変数展開`` `${value}` ``を行うと文字列型になります
- `.toString()`メソッドがある場合はそれを使う
- `Boolean()`や`Number()`などのラッパーオブジェクトを使う
- double bang`!!`やdouble tilde`~~`など演算子を使う
- 手作業で詰め替える

質問の答えになっていますでしょうか😌 もし不十分な回答でしたら改めてご質問ください。

**Comment by yo-goto** [comment]
@suin さん、
なるほど、理解できました。丁寧にありがとうございます!!
