### ISSUE TITLE
twoslashの全面導入

### ISSUE THREAD

**Issue by suin** [yytypescript/book#322]
twoslashが効いていたら回避できそうな疑問があることが分かったので、これを機にtwoslashを全面導入したい。

thx feedback kaneda at [YYTypeScript#125 執筆会 - HackMD](https://hackmd.io/45abWpzGToG2QhaoSOrRhQ?view#%E4%BB%8A%E5%9B%9E%E3%82%84%E3%81%A3%E3%81%9F%E3%81%93%E3%81%A8)

**Comment by jamashita** [comment]
DONE
