### ISSUE TITLE
質問: Reactいいねボタンのチュートリアルでカウンターが動きません

### ISSUE THREAD

**Issue by umeQ07** [yytypescript/book#339]
ボタンの形は出来たんですが、手順通りにコードをやってもカウントされません。
コピペなので構文エラーではないと思いますが、、
App.tsxのImportのReactのとこが「宣言されていますがその値が読み取られることはありませんと出ていますがこれが原因なのでしょうか？　

関連ページ: https://typescriptbook.jp/tutorials/react-like-button-tutorial

**Comment by suin** [comment]
@umeQ07 ご質問ありがとうございます。チュートリアルがうまく動かなかったようで申し訳ございません。。

うまく動かなかったコード一式を共有していただけると、何らかの回答ができるかもしれません。

- コード一式をgit pushしたGitHubリポジトリを教えていただく
- コード一式をzipファイルなどにして、このissueに添付していただく

などの方法で共有いただけるとありがたいです！

**Comment by umeQ07** [comment]
これです。
チュ`トリアルをそのままコピペしたので内容はおかしくないはずなんですよね。
エディタでたときにｔｓｘのほうでインポ`トＲｅａｃｔがiみ取れないと出ていたのはどうなんでしょうか？from reactは正常でした。

幼鳏丹护毪郡幛韦胜摔筏い韦！

すみませんが回答よろしくおいいたします。

Windows の メ`ル<https://go.microsoft.com/fwlink/?LinkId=550986> から送信

________________________________
差出人: suin ***@***.***>
送信日r: Thursday, March 24, 2022 10:27:08 AM
宛先: yytypescript/book ***@***.***>
CC: umeQ07 ***@***.***>; Mention ***@***.***>
件名: Re: [yytypescript/book] |です (Issue #339)


@umeQ07<https://github.com/umeQ07> ご|ありがとうございます。チュ`トリアルがうまく婴胜盲郡瑜Δ巧辘吩Uございません。。

うまく婴胜盲骏畅`ド一式を共有していただけると、何らかの回答ができるかもしれません。

  *   コ`ド一式をgit pushしたGitHubリポジトリを教えていただく
  *   コ`ド一式をzipファイルなどにして、このissueに添付していただく

などの方法で共有いただけるとありがたいです！

―

**Comment by suin** [comment]
@umeQ07  メッセージが文字化けしていて一部読めないので、再度お教えいただけませんでしょうか？

解決に向けてご協力できたらと思いますので、具体的な状況を把握するためにも

- コード一式をgit pushしたGitHubリポジトリを教えていただく
- コード一式をzipファイルなどにして、このissueに添付していただく

のいずれかをしていただけると助かります！

**Comment by umeQ07** [comment]
すみません。。
なんか一回すべて削除してからやったらできちゃいました。
yarn startが上手く出来ていなかったのか接A的な}なのか。。
お手数をおかけしました。申しUございません。


Windows の メ`ル<https://go.microsoft.com/fwlink/?LinkId=550986> から送信

差出人: ***@***.***>
送信日r: 2022年3月25日 19:22
宛先: ***@***.***>
CC: ***@***.***>; ***@***.***>
件名: Re: [yytypescript/book] |: Reactいいねボタンのチュ`トリアルでカウンタ`が婴蓼护 (Issue #339)


@umeQ07<https://github.com/umeQ07> メッセ`ジが文字化けしていて一部iめないので、再度お教えいただけませんでしょうか？

解Qに向けてごf力できたらと思いますので、具体的な状rを把握するためにも

  *   コ`ド一式をgit pushしたGitHubリポジトリを教えていただく
  *   コ`ド一式をzipファイルなどにして、このissueに添付していただく

のいずれかをしていただけると助かります！

―

**Comment by suin** [comment]
ひとまずは解決できたようで良かったです😌
