### ISSUE TITLE
誤値：[サンプルコード]undefined型とvoid型の違い

### ISSUE THREAD

**Issue by osaguild** [yytypescript/book#350]
サンプルコードの誤値を見つけました。
### 該当箇所
[undefined型とvoid型の違い](https://typescriptbook.jp/reference/functions/void-type#undefined%E5%9E%8B%E3%81%A8void%E5%9E%8B%E3%81%AE%E9%81%95%E3%81%84)

### サンプルコード AS-IS
 ```
function getIfExists(numbers: number[], search: number): number | undefined {
  if (numbers.includes(search)) {
    return number;
  }
  return undefined;
}
```

### 誤値
`return number`はnumber[]型なので、returnとして返すことはできない。
返すとしたらnumber型であるsearchの方が適切。

### サンプルコード TO-BE案
 ```
function getIfExists(numbers: number[], search: number): number | undefined {
  if (numbers.includes(search)) {
    return search;
  }
  return undefined;
}
```

**Comment by suin** [comment]
ご報告ありがとうございます！！修正させていただきました。

**Comment by osaguild** [comment]
ありがとうございます！
修正されていることを確認しました！
