### ISSUE TITLE
ReactのチュートリアルでJSXの自己閉じタグについて説明する

### ISSUE THREAD

**Issue by mendelssohnbach** [yytypescript/book#363]
有用な資料公開ありがとうございます。

`<LikeButton />`
上記のようにシングルタグに `/` を用いています。

これはXML文法として必要だからですね。

jsxに関するワンポイントのXMLの説明に「気をつける落とし穴」
として簡単に紹介されてはどうでしょうか？

関連ページ: https://typescriptbook.jp/tutorials/react-like-button-tutorial

**Comment by suin** [comment]
フィードバックありがとうございます！自己閉じタグについて、ひとことあった方がよさそうですね！
