### ISSUE TITLE
誤植: `Poiint` -> `Point`, `buiding` -> `building`

### ISSUE THREAD

**Issue by kangetsu121** [yytypescript/book#368]
細かく恐縮ですが、以下に typo がありました。
この typo の修正も含め、js-primer の `prh.yml` も何度か更新されているので、差分を確認するのも良いかもしれません。

1. `js-primer.yml`
    - `Poiint`: <https://github.com/yytypescript/book/blob/c80c2b026c3337b1c6966ee0f48578fc0260df59/prh/js-primer.yml#L219>
2. `get-a-subset-of-an-object.md`
    - <https://github.com/yytypescript/book/blame/3fd26e1c039645e8081e3056d16123765a7a69df/docs/tips/get-a-subset-of-an-object.md#L18>
    - <https://github.com/yytypescript/book/blame/3fd26e1c039645e8081e3056d16123765a7a69df/docs/tips/get-a-subset-of-an-object.md#L29>
    - <https://github.com/yytypescript/book/blame/3fd26e1c039645e8081e3056d16123765a7a69df/docs/tips/get-a-subset-of-an-object.md#L65>
    - <https://github.com/yytypescript/book/blame/3fd26e1c039645e8081e3056d16123765a7a69df/docs/tips/get-a-subset-of-an-object.md#L75>
    - <https://github.com/yytypescript/book/blame/3fd26e1c039645e8081e3056d16123765a7a69df/docs/tips/get-a-subset-of-an-object.md#L119>

**Comment by suin** [comment]
ご報告ありがとうございます！
