### ISSUE TITLE
declareに関する説明がほしい

### ISSUE THREAD

**Issue by hayato07** [yytypescript/book#370]
[オーバーロード関数 (overload functions)](https://typescriptbook.jp/reference/functions/overload-functions)のページでオーバーロードの定義をする際に、`declare`が説明なく出てくるので、これに関する説明があると良いと思いました。

[型定義ファイル (.d.ts)](https://typescriptbook.jp/reference/declaration-file)のページでも利用されていました。

関連ページ: 

- https://typescriptbook.jp/reference/functions/overload-functions
- https://typescriptbook.jp/reference/declaration-file

**Comment by suin** [comment]
メモ: [オーバーロード関数](https://typescriptbook.jp/reference/functions/overload-functions)は、declareを使わない解説に変更しました。
