### ISSUE TITLE
誤字・脱字の報告

### ISSUE THREAD

**Issue by Kounotori-ssbm** [yytypescript/book#416]
https://typescriptbook.jp/overview/before-typescript#%E5%8F%82%E8%80%83%E8%B3%87%E6%96%99

こちらの「参考資料」で `A Brief History of JavaScrip` と、最後の t が抜けているのを発見しましたので報告させていただきます。

この本をまさに読み始めたところなのですが、ターゲットにまさに当てはまっているので、とても助かるだろうと思い読み進めさせていただきます。
コントリビューターの皆さまありがとうございます！

---

P.S.
読み進めていく中で追加で脱字を見つけたので報告します。
https://typescriptbook.jp/tutorials/nextjs#%E6%9C%80%E5%88%9D%E3%81%AE%E3%83%9A%E3%83%BC%E3%82%B8%E3%82%92%E5%AE%9F%E8%A3%85
> コンポーネントの実装が完了したら、改めてdevサーバーを起動して**ブラウ**で確認してみてください。

ブラウザの「ザ」が抜けていました。

---

P.S.
追加報告します。
https://typescriptbook.jp/reference/values-types-variables/object/how-to-loop-an-object#objectvalues
```ts
for (const key of Object.values(foo)) {
```
コードサンプルの for の変数名は `key` ではなく `value` ではないかと思います。

---

追加報告です。
[if-else 文のページ](https://typescriptbook.jp/reference/statements/if-else#:~:text=%E3%82%B3%E3%83%94%E3%83%BC-,%E5%BC%8F%E3%81%A7%E6%9D%A1%E4%BB%B6%E5%88%86%E5%B2%90%E4%BD%BF%E3%81%84%E3%81%9F%E3%81%84,-%E5%A0%B4%E5%90%88%E3%81%AF%E4%B8%89%E9%A0%85) にて
> 式で条件分岐使いたい

と、「条件分岐」のあとに「を」が抜けていました。

---

追加報告です。
https://typescriptbook.jp/reference/statements/exception
こちらの例外処理のページの冒頭のコードサンプルで `catch` の中のコメントのインデントがずれていました。

---

追加報告です。
https://typescriptbook.jp/reference/functions/function-expression-vs-arrow-functions#%E5%BE%93%E6%9D%A5%E3%81%AE%E9%96%A2%E6%95%B0%E3%81%A8%E3%82%A2%E3%83%AD%E3%83%BC%E9%96%A2%E6%95%B0%E3%81%AE%E4%BD%BF%E3%81%84%E5%88%86%E3%81%91
こちらの「従来の関数とアロー関数の使い分け」の文の中に以下の誤字がありました。

> アロー関数を用いた `fullName2` **de**は `this` がオブジェクトを指さないため

**Comment by suin** [comment]
ご報告ありがとうございます！とても助かります😌
