### ISSUE TITLE
質問です: 引数の()が無い簡潔文体の型注釈

### ISSUE THREAD

**Issue by yo-goto** [yytypescript/book#417]
以下のURLの頁にあるアロー関数の簡潔文体とその型注釈の説明についての質問があります。

>さらに、関数内のコードが式1つだけの場合は、中カッコ `{}`と `return` が省略できます。この省略形は簡潔文体(concise body)、非省略形はブロック文体(block body)と呼びわけます。

この説明を読む限り `{}` が無いものが簡潔文体であるというように解釈できますが、アロー関数の引数に対して `()` があるものも簡潔文体であるのではないでしょうか。

```ts
// 簡潔文体
const increment1 = n => n + 1;
// () のある簡潔文体?
const increment2 = (n) => n + 1;
```

>簡潔文体では、引数と戻り値のどちらも型注釈を書けません。

ともあるので、正確には `()` が省略された簡潔文体が型注釈をできないという認識であってますでしょうか?
Deno では以下のように `()` をつければ型注釈ができて実行できました。

```ts
// () のある簡潔文体?
const increment3 = (n: number): number => n + 1;
```

関連ページ: https://typescriptbook.jp/reference/functions/arrow-functions

**Comment by suin** [comment]
ご回答が遅くなりすみません。

おっしゃるとおり

```typescript
const increment3 = (n: number): number => n + 1;
```

も簡潔文体なので、「簡潔文体では、引数と戻り値のどちらも型注釈を書けません。」は誤りです。

本文のほうも修正しておきたいとおもいます。

質問という形で気づかせてくださりありがとうございます！

**Comment by yo-goto** [comment]
回答ありがとうございます。理解できました。
また、記事を読んでくださったようでありがとうございます🙇‍♂️
いつも参考にさせていただいているので微力ですが勝手に宣伝しています(笑)
