### ISSUE TITLE
質問です

### ISSUE THREAD

**Issue by kenji-yodogawa** [yytypescript/book#418]
function increment(num) {
    return num + 1;
}
console.log(increment(999));

という、increment.js  ファイルができ、
それを. node increment.js として動作させようとしても
何も表示されませんが、これはなぜでしょうか？
（Windows10のコマンドプロンプトから動作させようとしました。）

関連ページ: https://typescriptbook.jp/tutorials/make-a-simple-function-via-cli

**Comment by jamashita** [comment]
1. node は正しくインストールされていますか？
2. increment.js があるディレクトリで実行していますか？
3. npx node increment.js で動きますか？

**Comment by jamashita** [comment]
こちら問題がまだ解決できないようであればreopen願います。closeします。
