### ISSUE TITLE
質問です: Type predicateの宣言とは具体的にどのような機能なのでしょうか?

### ISSUE THREAD

**Issue by yo-goto** [yytypescript/book#421]
関連ページ: https://typescriptbook.jp/reference/functions/type-guard-functions

質問というよりも指摘に近いのですが、上のURLのページの冒頭にある「Type predicateの宣言」というものが何なのかという解説が無いのですが、「Type predicate」とは具体的にどこの部分を指していて、どのような機能なのでしょうか?「Type predicate」でページを検索してみると他の２つのページでヒットしますが、どちらにも解説が無いようです。

https://typescriptbook.jp/reference/functions/assertion-functions
https://typescriptbook.jp/reference/object-oriented/interface/instanceof-and-interfaces

また、次のように型注釈の変更を行う必要性について謎があり、いまいち分かりません。
```diff ts
function isDuck(
  animal: Animal
-): boolean {
+): animal is Duck {
  return animal instanceof Duck;
}
```

わざわざ型注釈を変更した型ガード関数を使うのは、boolean 型の返り値を返す関数とするだけで型ガード関数を使わないと、次のような判定でうまく機能しなくためということでしょうか?
```ts
if (isDuck(animal)) {
  animal.quacks();
}
```

**Comment by jamashita** [comment]
めも
`if(typeof x === 'string)`
これは type predicate というかは type guard で

`if(isDuck(x))`
これは type predicate であろう関数をつかった type guard

**Comment by jamashita** [comment]
@yo-goto こちら、戻り値を `boolean` のまま使いますと、 if のブロックでも `animal` はAnimal型であると判断されたままで、Duck型になりません。そのため `quacks()` というメソッドがありませんよ。という指摘を受けることに繋がります。

( `quacks()` が Duckクラスのメソッドだとした場合の話)

**Comment by yo-goto** [comment]
回答ありがとうございます。
なるほど、`boolean` 型の値を返すだけの関数だと制御フロー解析では Duck 型と見なされないのですね。
