### ISSUE TITLE
zsh EXTENDED_GLOBオプション環境で「yarn add -D eslint@^8」がエラーになる

### ISSUE THREAD

**Issue by htaketani** [yytypescript/book#424]
`yarn add -D eslint@^8` を実行する際に、zshで拡張グロブ(EXTENDED_GLOB)オプションを有効にしている環境では、シェルが`^`を評価しようとしてエラーになるため、初学者を混乱させるかもしれません。

```
% yarn add -D eslint@^8
zsh: no matches found: eslint@^8
```

* 最近のmacがデフォルトシェルにzshを採用していること
* EXTENDED_GLOBオプションを紹介する記事が複数あり、ある程度利用されていると思われること

を鑑みて、なんらかの注釈を付けてはどうでしょうか。

```
zsh環境で次のようなエラーが出たら...
...
yarn add -D 'eslint@^8' のようにクォートで囲ってください。
```

**Comment by htaketani** [comment]
(注釈を付けるのではなく、)
いっそ、バージョン指定付きで yarn add している箇所は全てクォート付きで表記する、
という対応で良い気がしてきました。

**Comment by suin** [comment]
ご報告&PRありがとうございます！
#426 をマージさせていただきました🙇🏻‍♂️
