### ISSUE TITLE
【確認】個人的に「サバイバルTypeScript」に追加して欲しいリスト

### ISSUE THREAD

**Issue by shota-nukumizu** [yytypescript/book#440]
2022年7月22日時点で、「サバイバルTypeScript」に追加してほしい内容をここに簡潔にまとめておきます。良ければ確認してもらえると嬉しいです！

https://github.com/shota-nukumizu/development-tips/blob/main/typescript/book-ts/ideas.md

**Comment by suin** [comment]
@shota-nukumizu 素敵な提案ありがとうございます。これひとつひとつissueにしてもらえますか？😌

**Comment by shota-nukumizu** [comment]
とりあえず個人的に重要度の高いものをissue化してみました！

**Comment by jamashita** [comment]
すでにissue化されていそうなのでcloseしますね。
