### ISSUE TITLE
ジェネリクスの引数にTを使うべき理由を解説してほしい

### ISSUE THREAD

**Issue by shota-nukumizu** [yytypescript/book#443]
私自身この件については全く理解できていないので、詳細な解説があるとありがたいです！

**Comment by suin** [comment]
@shota-nukumizu ここに「ジェネリクスはなぜTが使われるのか？T以外じゃダメなのか？」の疑問に答える解説とコラムがありますが、この内容でいかかでしょうか？😌

http://localhost:3000/reference/generics/type-variables#%E5%9E%8B%E5%A4%89%E6%95%B0%E5%90%8D%E3%81%AE%E6%85%A3%E7%BF%92
