### ISSUE TITLE
TypeScriptのコーディング規約に関するトピックを追加してほしい

### ISSUE THREAD

**Issue by shota-nukumizu** [yytypescript/book#446]
TypeScriptのコーディング規約は、読みやすいコードを効率よく書く上では非常に重要だと思うので追加お願いします！

**Comment by suin** [comment]
@shota-nukumizu ありがとうございます。コーディング規約といっても様々なトピックがあると思います。

一応、[ESLintでTypeScriptのコーディング規約チェックを自動化しよう](https://typescriptbook.jp/tutorials/eslint#typescript%E3%81%AE%E6%9B%B8%E3%81%8D%E6%96%B9%E3%81%AF%E3%81%95%E3%81%BE%E3%81%96%E3%81%BE)に、コーディング規約に触れるところはあります。

具体的に、コーディング規約について、どんなことを知りたいでしょうか？😌

執筆にあたっては、コーディング規約についての具体的な疑問点を列挙していただいたほうが、対応しやすいと思います！

**Comment by suin** [comment]
shotaさんに聞いたらこういうGood・Bad集がほしいとのこと

<img width="311" alt="20220722_205601" src="https://user-images.githubusercontent.com/855338/180434301-51153ee7-13f3-4545-90f6-855a64794d28.png">

**Comment by suin** [comment]
こっちに具体化したので閉じます。 #535
