### ISSUE TITLE
TypeScriptのデコレータに関する詳細な説明を書いてほしい

### ISSUE THREAD

**Issue by shota-nukumizu** [yytypescript/book#461]
本サイトにあるデコレータに関する説明が個人的に少しザックリしているので詳細に書いたほうがいいと思います。

2022年8月5日現在で、TypeScriptのデコレータには以下のような説明があります。

* 現時点ではPlaygroundでしか使えないこと
* ローカル環境で動かすためには`tsconfig.json`の中を`["experimentalDecorators": true]`と設定しておく必要があること

デコレータはAngularを実務で触っている人にとっては重要な要素なので、別途ページを用意して詳細な説明を記したほうがいいと思います。

▼Angularのサンプルコード
```ts
import { Component, VERSION } from '@angular/core';
 
@simpleDecorator
@Component({
  selector: 'my-app',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  name = 'Angular ' + VERSION.major;
 
  constructor() {
    console.log('Hello from Class constructor');
  }
 
  ngOnInit() {
    console.log((this as any).value1);
    console.log((this as any).value2);
  }
}
 
function simpleDecorator(target: any) {
  console.log('Hello from Decorator');
 
  Object.defineProperty(target.prototype, 'value1', {
    value: 100,
    writable: false
  });
 
  Object.defineProperty(target.prototype, 'value2', {
    value: 200,
    writable: false
  });
}
```

▼記事
https://typescriptbook.jp/symbols-and-keywords#-%E3%83%87%E3%82%B3%E3%83%AC%E3%83%BC%E3%82%BF%E3%83%BC-decorator-ts

参考記事
https://qiita.com/tak001/items/ab573b8a5ba7b78b341a

公式docs：https://www.typescriptlang.org/docs/handbook/decorators.html

**Comment by suin** [comment]
現状はフロントエンドTypeScriptに絞って書いているため、デコレーターはフロントエンド実務ではまだまだ必須という状況ではないよねという結論に一旦はなっています😌本書の扱う範囲を広げる計画は簡単ですが、広げると作業量が増えて完成は遠のくので、わざと省いている部分です。本書のデコレーターの扱いがざっくりした説明になっているのはそのためです。

といっても、もし実務の状況やニーズが変わってきているなら、サバイバルTypeScriptに含めるか見直す余地はあると思います。
