### ISSUE TITLE
DefinitelyTypedのリンク切れ

### ISSUE THREAD

**Issue by yuyuyukie** [yytypescript/book#463]
https://typescriptbook.jp/reference/declaration-file
404になっています。

日本語のコントリビューションガイドはこちらになるでしょうか？
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.ja.md#%E3%82%B3%E3%83%B3%E3%83%88%E3%83%AA%E3%83%93%E3%83%A5%E3%83%BC%E3%83%88%E8%B2%A2%E7%8C%AE%E3%81%99%E3%82%8B%E6%96%B9%E6%B3%95

**Comment by jamashita** [comment]
ありがとうございます！こちらのリンクを頂戴いたします！
