### ISSUE TITLE
==と===の違いについて詳細に解説する記事を追加してほしい

### ISSUE THREAD

**Issue by shota-nukumizu** [yytypescript/book#470]
TypeScriptで、2つの値が一致しているかどうかを確認する際に使う等価演算子(`==`と`===`)の種類やその違いについて詳細に書かれている記事がなかったのでそれに関する説明を付け加えてほしい。

```ts
//
console.log("" == "0"); // false
console.log(0 == ""); // true

console.log("" === "0"); // false
console.log(0 === ""); // false
```

`==`：値そのものを比較する際に使う。たとえデータ型が違っても、`0`と`""`を`==`で接続する場合は結果が`true`になる。

`===`：値のデータ型を比較する際に使う。原則、データ型で比較する場合は`===`を用いる。

参照：[Why use triple-equal (===) in TypeScript?](https://stackoverflow.com/questions/57125700/why-use-triple-equal-in-typescript)

**Comment by jamashita** [comment]
@suin
等価であることを1ページ費やして紹介するのはいかがでしょうか？
値・型・変数の中に入れていいと思っていますが、文のほうがより適任でしょうか？

**Comment by suin** [comment]
@jamashita 

- 1ページにしたほうがいいと思います!
- 文でも良さそうですが、どちらかというと値・型・変数かいいと思います！(明確な理由があまり思いつかない)

**Comment by jamashita** [comment]
@suin ありがとうございます。そのようにいたします！
