### ISSUE TITLE
「記号とキーワード」Improvement suggestion

### ISSUE THREAD

**Issue by AceBee007** [yytypescript/book#478]
https://typescriptbook.jp/symbols-and-keywords

単独では意味をなさない記号を「XXの開始に現れる記号」という記述があるが、「XXの終了に現れる記号」という記述がなければ、これらの記号を単独の開始部分の記述ではなく、全体で意味をなす記述にすべきかと思います。

以下は私が主観的にピックアップした部分です、ご参考までに。

よろしくお願いいたします。

https://github.com/yytypescript/book/blob/master/docs/symbols-and-keywords.md?plain=1#L96
```diff
-### `$` 文字列中の変数展開 (placeholder) ![js]
+### `${}` 文字列中の変数展開 (placeholder) ![js]
```

https://github.com/yytypescript/book/blob/master/docs/symbols-and-keywords.md?plain=1#L214
```diff
-### `*` ジェネレーター関数の宣言 (generator) ![js]
+### `function*` ジェネレーター関数の宣言 (generator) ![js]
```

https://github.com/yytypescript/book/blob/master/docs/symbols-and-keywords.md?plain=1#L226
```diff
-### `*` yield\*式 (yield) ![js]
+### `yield*` yield\*式 (yield) ![js]
```

https://github.com/yytypescript/book/blob/master/docs/symbols-and-keywords.md?plain=1#L485
```diff
-### `/*` 複数行コメント (multiline comment) ![js]
+### `/*`...`*/` 複数行コメント (multiline comment) ![js]
```

https://github.com/yytypescript/book/blob/master/docs/symbols-and-keywords.md?plain=1#L495
```diff
-### `/**` JSDoc
+### `/**`...`*/` JSDoc
```

https://github.com/yytypescript/book/blob/master/docs/symbols-and-keywords.md?plain=1#L531
```diff
-### `<` ジェネリクス (generic) ![ts]
+### `<Type>` ジェネリクス (generic) ![ts]
```

https://github.com/yytypescript/book/blob/master/docs/symbols-and-keywords.md?plain=1#L542
```diff
-### `<` JSX ![ts]
+### `<tag>`...`</tag>` JSX ![ts]
```

https://github.com/yytypescript/book/blob/master/docs/symbols-and-keywords.md?plain=1#L552
```diff
-### `<` 型アサーション (type assertion) ![ts]
+### `<Type>` 型アサーション (type assertion) ![ts]
```

**Comment by suin** [comment]
ご提案ありがとうございます！

部分では意味の成さないというのは、おっしゃるとおりなです。

そもそもTypeScriptの文法意識がない入門者でも索引できるように、文法的(トークン的)にはおかしな部分で意図的に切り取っている側面がございます。

たとえば、`yield * foo`はジェネレーターのyield式というのを知っていてはじめて、`yield*`で索引できるものと思います。ジェネレーターを知らないと、`*`が`yield`に付随するものなのか、`foo`に付随するものなのかがわからないと思います。そういう場合に索引できるように`*`にてyield式を取り上げています。
