### ISSUE TITLE
【お願い】TypeScriptにおけるタグ付きユニオンに関するトピックを掲載

### ISSUE THREAD

**Issue by shota-nukumizu** [yytypescript/book#481]
個人的にこれをユニオン型のトピックで扱ってほしいと考えたので共有します。

TypeScriptにおけるタグ付きユニオンは、ユニオン型の各構成要素であるオブジェクト型がそれらが共通して持つプロパティを通じてランタイムに判別できるようなものを指します。最も典型的なのは、タグとして、各構成要素に異なるリテラル型（特に文字列のリテラル型）を与えるものです。**最大の特徴は型の絞り込みです。**

これはジェネリクスと相性がよく、例えば例外処理とそうではない処理を簡潔に分割できます。

```ts
type OkResult<T> = {
  type: "ok";
  payload: T;
};
type ErrorResult = {
  type: "error";
  payload: Error;
};

// 処理結果をジェネリクスで表現した通常の処理と例外処理で区別している
// 型を特定のものに絞り込めるのが魅力。
type Result<T> = OkResult<T> | ErrorResult;

function unwrapResult<T>(result: Result<T>): T {
  if (result.type === "ok") {
    return result.payload;
  } else {
    throw result.payload;
  }
}
```

参考になれば幸いです。

参考：[TypeScript 4.6で起こるタグ付きユニオンのさらなる進化 - Zenn](https://zenn.dev/uhyo/articles/ts-4-6-destructing-unions)

**Comment by suin** [comment]
ありがとうございます。

タグ付きユニオンは[判別可能なユニオン型 (discriminated union) | TypeScript入門『サバイバルTypeScript』](https://typescriptbook.jp/reference/values-types-variables/discriminated-union)で解説しているのですが、これで足りない内容がありそうだったら、Issueを再オープンして教えてください😌

**Comment by shota-nukumizu** [comment]
上記の記事で十分に理解できました、ありがとうございます。
