### ISSUE TITLE
[質問] Mapped Typesの”インデックス型と異なるところ”について

### ISSUE THREAD

**Issue by blue32a** [yytypescript/book#489]
> Mapped Typesはインデックス型と異なりsymbol型もキーにすることができます。

Mapped Typesのページではこのように説明されていますが、インデックス型のページではsymbol型も指定できるとありました。

> インデックス型のフィールド名の型はstring、number、symbolのみが指定できます。

実際にやってみるとsymbol型に出来たのですが、バージョンによって異ったりするのでしょうか？

```ts
// v4.7.4
let obj: {
  [K: symbol]: number;
};
obj = { [Symbol("hoge")]: 3 };
console.log(obj); // { [Symbol(hoge)]: 3 }
```

関連ページ: https://typescriptbook.jp/reference/type-reuse/mapped-types

**Comment by suin** [comment]
解説は誤りです。申し訳ございません。ご指摘のとおり、TypeScript 4.4以降、インデックス型でもsymbolが使えるようになっています。

**Comment by blue32a** [comment]
@suin 回答ありがとうございます。試したのがv4.7.4だったので使えたのですね。スッキリしました。
