### ISSUE TITLE
「TypeScriptは何ではないか？」は「何ができないか？」ではないか？

### ISSUE THREAD

**Issue by necrologie** [yytypescript/book#494]
「TypeScriptは何ではないか？」というタイトルが間違っています。
（「何ができないか？」の間違いでしょうか）

関連ページ: https://typescriptbook.jp/overview/typescript-is-not-that

**Comment by jamashita** [comment]
（何を目的としたものであって）何ではないか？
を意図した文章なので特に問題はないかと思います。
