### ISSUE TITLE
TS4.9で取り入れられたsatisfies operatorを書きませんか？

### ISSUE THREAD

**Issue by jamashita** [yytypescript/book#503]
取り急ぎ共有
https://devblogs.microsoft.com/typescript/announcing-typescript-4-9-beta/#the-satisfies-operator

**Comment by suin** [comment]
まだちゃんとキャッチアップできてませんが、書いても良さそうです！

**Comment by suin** [comment]
次の話し合いトピック: satisfiesオペレーターを取り上げるとしたら、どのようなアウトラインにするか？
