### ISSUE TITLE
質問: 配列が共変であることの利便性は何でしょうか？

### ISSUE THREAD

**Issue by yas99en** [yytypescript/book#507]
配列が共変であることの利便性は何でしょうか？

関連ページ: https://typescriptbook.jp/reference/values-types-variables/array/array-type-is-covariant

**Comment by bababax11** [comment]
`cats: Cat[]` という配列があり `hoge(animals: Animal[]) => void`
 という関数があったときにhogeにキャスト抜きでcatsを渡せるのは便利だからというのが一つの解答になります。
JavaScript では型を意識せずにやってきたことだから、TypeScriptでも許したという雰囲気を感じます。
他の静的型付けだとキャストを挟むことが多いですが、TSでそれをやるのはやめたということですね。

**Comment by suin** [comment]
# なぜ配列が共変か？

共変とは、ある型とその部分型が代入できること。

`number`型は、ユニオン型の`number | null`型の部分型です。

これを配列にした、`number[]`型は、`(number | null)[]`型の部分型ということになります。

TypeScriptの配列の型は、共変です。したがって、`number[]`型は`(number | null)[]`型に代入できます。

もし、TypeScriptの配列の型が非変なら、`(number | null)[]`型に代入できるのは、それ自身になります。`number[]`は`(number | null)[]`に代入できないことになります。

ここまでのことを整理すると次のようになります。

- `number`は`number | null`の部分型
- `number[]`は`(number | null)[]`の部分型
- 共変なら、`(number | null)[]`に`number[]`が代入できる。
- 非辺なら、`(number | null)[]`に`number[]`は代入できない。

ここで話を変えて、次のような関数を考えてみます。

```typescript
function sum(values: (number | null)[]): number {
  let total = 0;
  for (const value of values) {
    if (typeof value === "number") {
      total += value;
    }
  }
  return total;
}
```

この`sum`関数は、`(number | null)[]`、つまり数値とヌルが混在しうる配列を受け取り、数値だけピックアップして、その合計値を返す関数です。

関数の引数に代入する場合も、TypeScriptの配列は共変です。共変なので、次のような`number[]`型の値を代入できます。

```typescript
const values: number[] = [1, 2, 3];

sum(values);
```

もしも、TypeScriptの配列が非変だと、上のようなコードはコンパイルエラーになるでしょう。

そして、そのようなコンパイルエラーを回避しようとしたら、次のような余計な型アサーションを加えたりしないとなりません。

```typescript
sum(values as (number | null)[]);
//         ^^^^^^^^^^^^^^^^^型アサーション
```

こうしたことが随所で起きると、書くのも読むのも不便になります。したがって、TypeScriptでは型の完璧さよりも、利便性を優先しているものと考えられます。

また、TypeScriptはJavaScriptに型を追加した言語で、根底にはJavaScriptがあります。JavaScriptからTypeScriptに移行するコードもあると思いますが、配列が非変であることを前提に書かれたJavaScriptコードは少ないと思われます。そうした状況もあって、共変を許した可能性もあります。


こんな回答でどうでしょうか😌

**Comment by yas99en** [comment]
一応、ある程度、自己解決しました。
もとがJavaScriptだからというのも、その通りではあるのですが、
TypeScript的な理由付けを考えてみました。

上記のCatとAnimalの例で言うと、これらが単純に継承関係のあるclass同士だとすると
  class Cat extens Animals {...}
Javaと同じように見えてしまうので、配列は共変でない方が型安全で良いように見えます。

しかし両者が継承関係のない型であるなら、共変であることが自然に見えます。

ype Animal = {
  name: string
}

type Cat = {
  name: string
  tails: number
}

let orgs = [{name:"taro", tails:1}, {name:"jiro", tails: 3}]
let cats: Cat[] = orgs
let animals: Animal[] = cats

Javaとの根本的な違いとして、
TypeScriptは構造的型定義を採用しているということを考えれば
Animal[]の定義は、「メンバーにname:stringをもつオブジェクトの配列」としないと
それ以外の構造的な代入可能性と一貫性がなくなりそうな気がします。

JavaScriptと親和性のある型システムとして、
TypeScriptは構造的型定義を採用し、
その結果として、配列は共変であることが自然ということかと思います。

またTypeScriptには、構造的型定義以外にも
合併型による代入可能性： number と number|null
リテラル型による代入可能性： 1とnumber
がありますが、これらからも同様の結論になりそうに思えます。

ちょっとボンヤリしてしまいましたが、こんなところかと思いました。

**Comment by yas99en** [comment]
コンピュータ言語理論や型理論の専門家ではないので
完全に論理的な説明はできませんが、
おそらくですが、その道の専門家であれば、
- 構造的型定義
- 配列の非変性
の両方を共存させようとしたら
どこかで矛盾が生じることが証明できるのではないかと想像しています。

適当ですみません。あくまで想像です。
