### ISSUE TITLE
内容不備: TypeScript4.4以降、インデックス型にもsymbolを使用可能です。

### ISSUE THREAD

**Issue by syamozipc** [yytypescript/book#532]
https://typescriptbook.jp/reference/type-reuse/mapped-types
いつも参考にさせていただいております、ありがとうございます。

さて、「Mapped Typesはインデックス型と異なりsymbol型もキーにすることができます。」と記載してありますが、正しくはTypeScript4.4以降、インデックス型でもsymbol型をキーに出来るようです。

参考：
https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-4.html#symbol-and-template-string-pattern-index-signatures

**Comment by suin** [comment]
関連: #489
