### ISSUE TITLE
 「TypeScriptの特徴」にある一文を日本語的に違和感の少ないものに直す

### ISSUE THREAD

**Issue by taole33** [yytypescript/book#539]
https://typescriptbook.jp/overview/features
「TypeScriptの特徴」ページにある以下の日本語がおかしいので修正が必要だと思われます。

> TypeScriptはJavaScriptが実行できるすべてのブラウザ、コンピュータ、OSで動作し、オープンソースです。

以下のような修正が良いかと思います。
(案1) TypeScriptはJavaScriptが実行できるすべてのブラウザ、コンピュータ、OSで動作**する**オープンソースです。
(案2) TypeScriptはオープンソースであり、JavaScriptが実行できるすべてのブラウザ、コンピュータ、OSで動作します。

**Comment by suin** [comment]
ご指摘と改善案の提案までありがとうございます。

> (案2) TypeScriptはオープンソースであり、JavaScriptが実行できるすべてのブラウザ、コンピュータ、OSで動作します。

が良さそうです。
