### ISSUE TITLE
【提案】TypeScriptの「ベストプラクティス」に関する内容

### ISSUE THREAD

**Issue by shota-nukumizu** [yytypescript/book#541]
TypeScriptで学習や開発を始める読者に向けて、TypeScriptでコードを書く上で最低限理解しておきたい原則やテクニックなどをまとめた記事があってもいいのではないかと思いました。

理由は、これからTypeScriptで学習・開発を進めるための具体的な道標を示すことで**TypeScriptを最短で理解してもらうような仕組みを作るため**です。

【参照記事】
1. [Clean Code in TypeScript - Medium](https://javascript.plainenglish.io/clean-code-in-typescript-a183d43f3bf0)
2. [How not to learn TypeScript](https://fettblog.eu/how-not-to-learn-typescript/)

(1)の記事では、TypeScriptで書かれている質の悪いコードを具体例に取り上げて良質なコードに仕上げるためのテクニックがまとめられています。(2)では、やってはいけないTypeScriptの勉強のしかたについて言及されています。

私が考えるやり方としては、次のようなことが考えられます。(2つ)

* TypeScriptできれいなコードを書く上でのテクニック・原則をソースコード付きでまとめる。(形式は1.の記事をまねする形か？)
* TypeScriptでやってはいけない勉強方法を簡潔にまとめる

どうでしょうか？ご意見よろしくお願いします。

**Comment by suin** [comment]
アイディア良さそうです。

このissueは少なくとも2つに分割したほうが良さそうです。

1. きれいなコードを書くにはどうしたらいいか？
2. やってはいけないTypeScriptの勉強方法とは何か？

これらの知識は必要となるタイミングが必ずしも一致しないため、まぜて解説しないほうが良いからです。

**Comment by shota-nukumizu** [comment]
わかりました。こちらのIssueを一旦閉じて、新しく提案した２つのIssueに分割して再度あげておきます

**Comment by suin** [comment]
issueが分解されたのでクローズとします。
