### ISSUE TITLE
サバイバルTypeScript以外のTypeScriptの学習に役立つ情報源を紹介しませんか？

### ISSUE THREAD

**Issue by shota-nukumizu** [yytypescript/book#542]
これもより多くの読者にTypeScriptに興味を持ってもらうためには必要だと考えています。例えば、この記事では学習・開発でTypeScriptを使う上で確認しておきたいWebサイト等の情報源をまとめられています。

[【TypeScript】学習・開発で必ず確認するべきリポジトリ・サイト・書籍 33](https://zenn.dev/nameless_sn/articles/awesome_typescript_info)

本書(『サバイバルTypeScript』)にかぎらず、より多くの人にTypeScript関心を持ってもらうために他にも役立つ情報源を共有することも必要なのではと考えIssueを残しました。ご確認よろしくお願いします。

**Comment by suin** [comment]
これはいつか書きたいと思っている😌

**Comment by suin** [comment]
みなさん、具体的におすすめの情報源として何がありそうでしょうか？

まずは発散して、多すぎても圧倒されるだけなので最終的には5つ程度に厳選したいとは思います。

**Comment by yo-goto** [comment]
5つの中でも役割として分けるなどすると読み手のニーズに合わせて選択できると思います👍

具体的には以下の３つの情報源が個人的には良いかなと思います。また分け方としてはサバイバル TypeScript が「サバイバル」を目的としているので、そこからより発展できるような情報源に促すのが良いのではないかと提案します。

- (1) 『[TypeScript Deep Dive](https://typescript-jp.gitbook.io/deep-dive/)』: 同じOSSかつ日本語翻訳されており、無料で手軽に見ることのでき、コンパクトながら高度な内容を知れる
- (2) オライリーの『[Programming TypeScript](https://www.oreilly.co.jp/books/9784873119045/)』: TypeScript の型システムなどについてより深く学ぶことができ、日本語版が出版されている
- (3) Microsoft 公式の[TypeScript アナウンスブログ](https://devblogs.microsoft.com/typescript/) : TS の最新情報などについて知りたい場合に参照できる

体系的な情報源として参考にできるかどうかはちょっと微妙なところなのですが、個人的に推したいのが TypeScript の開発リポジトリでの Anders Hejlsberg さんのプルリクエスト(機能の概念や詳細な挙動などが開発者公式に解説している)。これを見れば謎なところが一発でわかることがあるので、機能について深く知りたい場合の情報源として提示すると良いかも知れません🧐

**Comment by suin** [comment]
@yo-goto ありがとうございます。

どれも良質な情報源ですね！

- 縦軸: レベル感、横軸: キャッチアップ向け
- 縦軸: レベル感、横軸: 深堀り度

みたな2次元マトリクスを作って、情報源をマッピングし可視化したら面白そうだと思いました😌

**Comment by yo-goto** [comment]
マトリクスは非常に良いアイデアだと思います👍
これなら一発で自分の知りたい情報源にアクセスできるのであると嬉しいですね!

**Comment by shota-nukumizu** [comment]
海外の情報ではありますが、[roadmap.sh](https://roadmap.sh/)も有益な情報を提供しています。他のIssueとの重複になりますが、[該当のページ](https://roadmap.sh/typescript)にはTypeScriptをマスターする上で必要最低限の知識をひと目で把握できます。

yo-gotoさんが言及していたように、一発で自分の知りたい情報源にアクセスできるという点において有益ではないかと考えます。

**Comment by suin** [comment]
![CleanShot 2023-04-14 at 19 50 17 png](https://user-images.githubusercontent.com/855338/232027760-24a354cc-6965-4a5a-a506-b8ec65c6185a.png)

あらましのの一番したにページを追加します。

**Comment by suin** [comment]
#559 とセットで @yo-goto さんにお願いすることになりました！

**Comment by yo-goto** [comment]
## ページについての全体像

項目 | 内容
--|--
ページの場所 | 『TypeScript のあらまし』のセクションの『TypeScript は何ではないか?』の後
タイトル | 『TypeScript をより知るための情報源』
内容 | TS について様々なニーズから知るための情報源を紹介し、公式ドキュメントについてはその構造や読み方のためのヒントなどを紹介する

あらましの場合 → TypeScript という言語の概要情報としてのまとめとなるので少し違和感があるかもしれない。複数ページがまとめられているセクションの外側でもいいかもしれない。

```
- あらまし/
    - ...
    - TypeScript は何ではないか?
    - ← このポイントに挿入するか
- 作って学ぶ/
- 読んで学ぶ/
- Tips/
- 索引
- ← このポイントに挿入するか
- TypeScript Playground の使い方
- TypeScript 超入門
```

**Comment by suin** [comment]
確かに違和感があるので外側のほうがいいかもしれませんね！

**Comment by yo-goto** [comment]
## 内容のアウトラインアイデア

このページでは、４から5つ程度メジャーな情報源を紹介し、その他のものもマトリクスでリンク表示したい。

紹介するものとしては、TypeScript を学習する上での指針や応用的な内容、深く学びたい場合の情報源など、詳しく紹介するものはそれぞれ役割が異なるようなものとする。以下は紹介するもの例 (暫定的)。サードパーティのものと公式のものは分けて説明するようにする。

microsoft 公式の情報
- (a) **公式ドキュメント**
- (b) TypeScript アナウンスブログ
- (c) GitHub のプルリクエスト

サードパーティの情報源
- (1) TypeScript Deep Dive
- (2) Programming TypeScript
- (3) roadmap.sh

特に公式ドキュメントはについてはその構造を把握できるようなロードマップ的なもの (あるいはそのような説明) を用意して、初学者 (あるいは特定のレベルや特定の言語習得者) がどのページを重点的に読んでいけばよいかのガイドなどがあるとよい。

**Comment by suin** [comment]
ありがとうございます。良いと思います！

下記の情報源も評判が良いので、もし触れたことがあったら、取り上げていただけると嬉しいです。

- [プロを目指す人のためのTypeScript入門 安全なコードの書き方から高度な型の使い方まで (Software Design plus) | 鈴木 僚太 |本 | 通販 | Amazon](https://www.amazon.co.jp/%E3%83%97%E3%83%AD%E3%82%92%E7%9B%AE%E6%8C%87%E3%81%99%E4%BA%BA%E3%81%AE%E3%81%9F%E3%82%81%E3%81%AETypeScript%E5%85%A5%E9%96%80-%E5%AE%89%E5%85%A8%E3%81%AA%E3%82%B3%E3%83%BC%E3%83%89%E3%81%AE%E6%9B%B8%E3%81%8D%E6%96%B9%E3%81%8B%E3%82%89%E9%AB%98%E5%BA%A6%E3%81%AA%E5%9E%8B%E3%81%AE%E4%BD%BF%E3%81%84%E6%96%B9%E3%81%BE%E3%81%A7-Software-Design-plus/dp/4297127474)
- [プレイリスト:日本一わかりやすいTypeScript入門 - YouTube](https://www.youtube.com/watch?v=kd8VH10jXwc&list=PLX8Rsrpnn3IW0REXnTWQp79mxCvHkIrad)

もし触れたことがなければ取り上げなくても構いません😌

**Comment by yo-goto** [comment]
一応触れたことがあったので、再度確認して取り上げたいと思います！

**Comment by suin** [comment]
@yo-goto PRありがとうございました！マージさせていただきました。💖

**Comment by yo-goto** [comment]
## よるマトリクス図の作成(ドラフト)

横軸: 深掘り⇔キャッチアップ
縦軸: 難解⇔分かりやすい

現時点での配置は適当です。
<img width="848" alt="image" src="https://github.com/yytypescript/book/assets/50942816/826ad33f-6043-4562-be2d-68bbb06099f0">
