### ISSUE TITLE
「TypeScriptの公式ドキュメントはどこを重点的に読んだらいいか」についてガイドを書きませんか？

### ISSUE THREAD

**Issue by shota-nukumizu** [yytypescript/book#559]
学習・開発を進める上で公式ドキュメントを参照する人は少なくないと考えるので、公式ドキュメントの読み方や攻略の仕方について簡潔にまとめられている記事を書いたほうがいいのではないかと思います。

**Comment by suin** [comment]
@shota-nukumizu Issueありがとうございます！Issueのタイトルを質問形式にしていただけると、どんな回答をしたらいいか考えやすいので、質問文を考えてもらえますか？

たとえば

- TypeScript公式ドキュメントを効率的に読むにはどうしたらいいですか？
- TypeScript公式ドキュメントはどこを重点的に読んだらいいですか？
- 英語が分からなくてもTypeScript公式ドキュメントを読み解くにはどうしたらいいですか？

**Comment by shota-nukumizu** [comment]
わかりました。
それでは、TypeScriptの公式ドキュメントはどこを重点的に読んだらいいですか？

**Comment by suin** [comment]
僕は、最近の公式ドキュメントに目を通していないので、これに対する回答を持ち合わせていません。

誰か回答できそうな人はいますか？

**Comment by yo-goto** [comment]
v2 ドキュメントは Get Started に高速で TS 機能について知れるセクションがあるので重点的に読むのをオススメしたいです🚀
特に「TypeScript for JavaScript Programmers」のページは重要な TS の機能と概念をさらっと知れるのでその知識を Handbook で拡張していくのが個人的にはオススメの方法だと思ってます👍

https://www.typescriptlang.org/docs/handbook/typescript-in-5-minutes.html

**Comment by suin** [comment]
@yo-goto こういう知見ありがたいです😌

**Comment by suin** [comment]
上のissueとセットで @yo-goto さんにお願いすることになりました！

**Comment by yo-goto** [comment]
## 公式ドキュメントの構造と読み方のページについてのアイデア

[TypeScript Documentation](https://www.typescriptlang.org/docs/) の構造と読み方について解説する。
多くの日本語書籍資料の内容がベースにしている v1 (古いバージョン)と v2 (最新)のドキュメントがあることに留意して v2 バージョンについての特徴や構造などを解説する。

### 内容のアウトライン
- ドキュメントのバージョンについて(v1とv2について)
- ドキュメントの意図と読み方について
- ドキュメントの構造について
- 初学者や別の言語習得者がどのポイントを重点的によめばいいかのヒント

### ドキュメントの主な構成項目 
名称 | 内容
--|--
Get Started | 学習者のバックグラウンドに基づいた5つのイントロダクションのセクション。
Handbook | 言語機能と挙動の包括的ガイド。
[Cheat Sheets](https://www.typescriptlang.org/cheatsheets) | シンタックスなどが分かりやすくまとめられているチートシート。
Release notes(What's new) | 各バージョンごとに追加された機能の紹介ページ。リンクされたPRなどについてもwikiのロードマップと一緒に解説する。
Reference | リファレンスセクション

**Comment by yo-goto** [comment]
公式ドキュメントの構造や意図を解説する過程で #42 の問題も直接的に取り上げる事ができる可能性があります。

特に公式ドキュメント(ハンドブック)の目的は「TypeScript が JavaScript の上にどのように構築されているかをエンジニアが理解できるように手助けすることであり、JavaScript についてはウェブや書籍のリソースにまかせて、JavaScript の機能について一から解説することを避ける」というものなので、サバイバルTypeScriptの「JavaScriptと並行して学べる」といった利点などを強調して解説できそうです。

もちろん「はじめに」のページに追加した方がいいなら取り上げません。

**Comment by suin** [comment]
> ## 公式ドキュメントの構造と読み方のページについてのアイデア
> 
> 
> 
> [TypeScript Documentation](https://www.typescriptlang.org/docs/) の構造と読み方について解説する。
> 
> 多くの日本語書籍資料の内容がベースにしている v1 (古いバージョン)と v2 (最新)のドキュメントがあることに留意して v2 バージョンについての特徴や構造などを解説する。
> 
> 
> 
> ### 内容のアウトライン
> 
> - ドキュメントのバージョンについて(v1とv2について)
> 
> - ドキュメントの意図と読み方について
> 
> - ドキュメントの構造について
> 
> - 初学者や別の言語習得者がどのポイントを重点的によめばいいかのヒント
> 
> 
> ### ドキュメントの主な構成項目 
> 
> 名称 | 内容
> 
> --|--
> 
> Get Started | 学習者のバックグラウンドに基づいた5つのイントロダクションのセクション。
> 
> Handbook | 言語機能と挙動の包括的ガイド。
> 
> [Cheat Sheets](https://www.typescriptlang.org/cheatsheets) | シンタックスなどが分かりやすくまとめられているチートシート。
> 
> Release notes(What's new) | 各バージョンごとに追加された機能の紹介ページ。リンクされたPRなどについてもwikiのロードマップと一緒に解説する。
> 
> Reference | リファレンスセクション

よさそうです！

**Comment by suin** [comment]
> 公式ドキュメントの構造や意図を解説する過程で #42 の問題も直接的に取り上げる事ができる可能性があります。
> 
> 
> 
> 特に公式ドキュメント(ハンドブック)の目的は「TypeScript が JavaScript の上にどのように構築されているかをエンジニアが理解できるように手助けすることであり、JavaScript についてはウェブや書籍のリソースにまかせて、JavaScript の機能について一から解説することを避ける」というものなので、サバイバルTypeScriptの「JavaScriptと並行して学べる」といった利点などを強調して解説できそうです。
> 
> 
> 
> もちろん「はじめに」のページに追加した方がいいなら取り上げません。

強調してもらえるのありがたいです！「はじめに」と重複してもいいです。検索から直接個別ページに来るユースケースも多いので、この場合、内容の重複は逆にいいものだと思います

**Comment by suin** [comment]
> @suin 
> 
> 公式ドキュメントの読み方や構造についての解説について、以前に自分の書いたドキュメントで下敷きにできそうなものがZennの方にあり、このドキュメントに記載した内容(バージョン情報など)をいくつかベースにして執筆していこうかなと考えています。
> 
> 
> 
> https://zenn.dev/estra/books/ts-the-minimum/viewer/b-tsmini-reading-official-docs
> 
> 
> 
> 上記のドキュメント自体には個人の意見(v2ドキュメントを実際に読んでみた自分の体験からのやり方や考え方)がかなり入っているので、サバイバルTypeScriptの内容を前提にしてかつなるべく客観的なガイドとする上での注意点などあれば指摘していただきたいです。
> 
> 
> 
> ただし、読み方のヒントなどを書こうとすると個人の体験によってしまうところが確実にでてきてしまうので、私だけでなく別のコントリビューターの体験なども組んで、「こう読め」というような物言いではなく「私はこう読みました」みたいな複数の体験談のセクションを設けるほうが読者にとってのヒントとしてわかりやすく、学習者のバックグラウンドに応じての指針にしやすくなるかもしれません。

独善的なガイドで良いと思います。初心者は「どう進めていったら分からない」が大きな悩みのひとつなので。

書こうとしているページは旅行ガイドブックと似ていると思います。知らない土地に行くときに旅行ガイドブックを頼ることがあると思いますが、羅列された候補から自分でプランを組むより、おすすめコースみたいなものをしっかり薦めてもらったほうが楽だったりします。これと同じで、「この順で読んでいくのがオススメ！」とはっきりしているほうが、むしろ良さそうです。

**Comment by yo-goto** [comment]
> 強調してもらえるのありがたいです！「はじめに」と重複してもいいです。検索から直接個別ページに来るユースケースも多いので、この場合、内容の重複は逆にいいものだと思います

承知しました!!
サバイバルTypeScriptと公式ドキュメントの役割・使い方の違いなども含めて記述していきたいと思います。

**Comment by suin** [comment]
@yo-goto PRありがとうございました！マージさせていただきました。🙏
