### ISSUE TITLE
「やってはいけないTypeScriptの勉強方法」について説明しませんか？

### ISSUE THREAD

**Issue by shota-nukumizu** [yytypescript/book#562]
#541 のIssueでの議論を踏まえて、やってはいけないTypeScriptの勉強方法みたいなのがあればご教示お願いします。

## 想定質問

 やってはいけないTypeScriptの勉強方法とは何か？

**Comment by suin** [comment]
「実務で使うなら最低限おさえておきたいこと」を本書で掲げているので、本書を読むことで、自然とやるべきことをやり、避けるべきことを避けられるようにしていきたいので、これについてページとして書く必要なないのかなと思います。

やっぱり後になって必要だと方針が変わった場合は、再オープンしたいと思います。
