### ISSUE TITLE
docsaurusをlatestにすると、yarn run startに失敗する

### ISSUE THREAD

**Issue by yabuki** [yytypescript/book#564]
インターネットに繋がない状態でも、本サイトをローカルから参照したくて、ローカルで愛読しております。

OS Debian GNU/Linux Sid
node: nvmで　lts/gallium(v16.19.0)
yarn: 1.22.19

git clone してきて、docsaurusの更新をしない状態で`yarn run start`をすると、無事に本サイトと同じものが localhost:3000で閲覧できる。

つぎに、yarn upgradeしろというおすすめにしたがって、
`yarn upgrade @docusaurus/core@latest @docusaurus/preset-classic@latest @docusaurus/module-type-aliases@latest`
を実行すると、

```
Module not found: Error: Can't resolve '@theme/hooks/useThemeContext' in '/home/yabuki/scm/git/book/src/components/codeReadingAssistant'
Module not found: Error: Can't resolve '@theme/hooks/useWindowSize' in '/home/yabuki/scm/git/book/src/theme/DocItem'
```
のようなエラーが発生して localhost:3000 で閲覧できない。

当方、js/ts/nodeの初心者のため、yarn upgradeしただけで、上記の問題を解決する方法がわからないので、yarn upgradeを**しない**というwork aroundで対処しております。もし、yarn upgradeが可能な方法について、ご存知なら、ご教授いただけると幸いです。

**Comment by suin** [comment]
愛読してくださってありがとうございます！

解決策は正確には「不明」というのが現状です。

詳しく調査していないので、推測の域を出ませんがdocusaurusのバージョンが下位互換性がなくなっていると思われます。
解決にはプログラムを直さないといけないと思うので、upgradeせずに閲覧いただくのが最も手間がないと思います。

**Comment by tats-u** [comment]
Docusaurusのバージョンが2のベータ版で、一部正式版で変更・廃止されたAPIを利用しているようですねz

```ts
import Seo from "@theme/Seo";
```

↑の代替がパッと見見つからなかったのでPRは見送りました

**Comment by suin** [comment]
別issue↑でトラッキングさせていただきます。
