### ISSUE TITLE
Prettierでコード整形を自動化しよう内のサンプルコードの誤植

### ISSUE THREAD

**Issue by Kotarosz727** [yytypescript/book#576]
[なぜPrettierを導入するのか](https://typescriptbook.jp/tutorials/prettier#%E3%81%AA%E3%81%9Cprettier%E3%82%92%E5%B0%8E%E5%85%A5%E3%81%99%E3%82%8B%E3%81%AE%E3%81%8B)内の、コードのサンプルですが「オブジェクトの最後にカンマがつかない」
と例で示されおりますが、カンマがついております。

<img width="766" alt="image" src="https://user-images.githubusercontent.com/50207951/216798619-dffd059e-76cc-445c-933e-fe55d001daa8.png">

**Comment by tats-u** [comment]
#569 で修正PR出していますが、今のところ見向きもされていません。
