### ISSUE TITLE
サンプルコードの誤植について

### ISSUE THREAD

**Issue by torippi** [yytypescript/book#577]
https://typescriptbook.jp/tutorials/prettier

どちらのコードも最後にカンマがついています。

`
// オブジェクトの最後にカンマが付いている
const user1 = {
  name: "太郎",
};

// オブジェクトの最後にカンマが付かない
const user2 = {
  name: "まさる",
};
`

**Comment by tats-u** [comment]
#569 で修正PR出していますが、今のところ見向きもされていません。
