### ISSUE TITLE
TypeSearchが終了したので、これを用いない解説に変更しませんか？

### ISSUE THREAD

**Issue by manjuu-eater** [yytypescript/book#582]
https://typescriptbook.jp/reference/declaration-file#型定義ファイル有りだが別途インストールが必要

[TypeSearch](https://microsoft.github.io/TypeSearch/)へのリンクがリンク切れになっています。

リンク先によると、

This page is no longer necessary.

The npm and Yarn package registries now include type information for packages.
You can read more on: [npm displays packages with bundled TypeScript declarations](https://github.blog/changelog/2020-12-16-npm-displays-packages-with-bundled-typescript-declarations).

だそうです。

**Comment by suin** [comment]
ご報告ありがとうございます。対応したいと思います。

**Comment by suin** [comment]
現行のチュートリアルでは、型定義パッケージを探す手法として、TypeSearchを使う手順になっています:

> [TypeSearch](https://microsoft.github.io/TypeSearch/)からパッケージ名を検索しインストールを行います。

この手順自体が不要だったかもしれないですね。

実務では`npm install @types/パッケージ名`をしてみることのほうが手っ取り早そうなので、

- 入れてみて入ったら型定義ファイルがある
- 入れてみて入らなかったら型定義ファイルがない

と判断すればいいよ、という趣旨の説明に変えても良さそうです。

・・・

その上で、どのパッケージには型定義ファイルがあるのかを、念の為確認する方法として、npmのパッケージを見に行ったら分かる旨を添えておくと良さそうです。

- TSアイコンがある → 型定義ファイルが同梱されているパッケージ
- DTアイコンがある → 型定義ファイル有りだが別途インストールが必要なパッケージ

**Comment by jamashita** [comment]
こちら着手いたします

**Comment by jamashita** [comment]
@manjuu-eater 大変遅くなりましたがこちらを反映いたしました。
ご意見いただきありがとうございました 🙇
