### ISSUE TITLE
誤植: コードブロックのハイライトのずれを直す

### ISSUE THREAD

**Issue by yukiyohure** [yytypescript/book#589]
- [発生セクション](https://typescriptbook.jp/tutorials/nextjs#getserversideprops%E3%81%A7%E5%88%9D%E6%9C%9F%E7%94%BB%E5%83%8F%E3%82%82%E3%83%A9%E3%83%B3%E3%83%80%E3%83%A0%E3%81%AB%E8%A1%A8%E7%A4%BA)

> 続いてgetServerSidePropsで猫画像を取得して、IndexPageにpropsとして渡します。

の下にあるコードブロックにて、チュートリアル上で `getServerSideProps` の実装が初出なのにも関わらずハイライトされていないようです。

<img width="841" alt="スクリーンショット 2023-02-22 0 15 06" src="https://user-images.githubusercontent.com/35441214/220384164-582b1209-c43a-4592-bbac-c8dc72bb2a48.png">

**Comment by suin** [comment]
ご報告ありがとうございます！誤りなので対応致します。
