### ISSUE TITLE
誤植: 使用していないuseEffectをサンプルコードから取り除く

### ISSUE THREAD

**Issue by yukiyohure** [yytypescript/book#590]
- [発生セクション](https://typescriptbook.jp/tutorials/nextjs#api%E3%83%AA%E3%82%AF%E3%82%A8%E3%82%B9%E3%83%88%E3%81%A7%E7%8C%AB%E3%81%AE%E7%94%BB%E5%83%8F%E3%82%92%E5%8F%96%E5%BE%97)

チュートリアル上で使用されていない `useEffect` を import している記述がコードブロックに残っていました。

<img width="847" alt="スクリーンショット 2023-02-22 0 18 52" src="https://user-images.githubusercontent.com/35441214/220385969-984f618b-08d2-488d-beb3-77320c3b51f3.png">

**Comment by suin** [comment]
ありがとうございます。対応致します！

**Comment by suin** [comment]
よく見たらuseEffectは使っていました。

<img width="665" alt="CleanShot 2023-02-26 at 17 15 10 png" src="https://user-images.githubusercontent.com/855338/221399629-2a38dcb1-e9c0-4b56-a64e-e4527ba60b2c.png">

(useEffectの利用部分にハイライトが効いていない点は別issue #610 で対応します。)

ご指摘の箇所が違っていたら再オープンしてください。

**Comment by yukiyohure** [comment]
@suin 
すみません、おっしゃる通り該当箇所のファイル説明で useEffect は使われていましたね。
#610 にあるように useEffect の部分がハイライトされていなかったために「使っていない」と誤判断してしまっていたようです。
ご確認ありがとうございました！

**Comment by suin** [comment]
いえいえ、使われていないと思うのも当然です！混乱させるサンプルコードになっていて申し訳ありません🙇🏻‍♂️ハイライトの誤りに気づくきっかけになったので、大変ありがたいです！
