### ISSUE TITLE
もったいないプルリクエストを減らすためにチケット駆動プロセスを導入する

### ISSUE THREAD

**Issue by suin** [yytypescript/book#596]
## 概要

プルリクエストをマージしない場合、プルリクエスト作者の時間と労力が無駄になり、申し訳ないという問題がある。これを解決すべく、プルリクエストを作成する前に、issueで話し合うプロセスを採用します。

## 背景: コントリビューターの増加

サバイバルTypeScriptのコントリビューターの増加に伴い、プルリクエストが増えてきました。プルリクエストの中には、マージされないものも出てきました。その理由として、本書の方向性と合わないといった理由が多いです。

## 課題1: 労力などがもったいない

プルリクエストは、コントリビューターの時間・労力・才能が注ぎ込まれて作られます。そうした貢献を取り込まないことは、時間・労力・才能を無駄遣いすることに他なりません。これは、コントリビューターにとって望ましいことではないでしょう。

## 課題2: 断るのが心理的負担

プルリクエストを断ることは、メンテナーにとっても難しいことです。プルリクエストの背後にある時間や労力について考えると、ひとことでは断れません。読者のことを考えるとマージすべきではないと思いつつも、コントリビューターのことを思うとマージしてあげたい。そんな板挟みもあります。そうした心理的負担は、メンテナーにとっての問題であり、執筆を進める上での抵抗にもなっています。

## 解決策: issueドリブン

上の課題を解決するのがissueドリブンです。「着手する前に話し合いましょう」というのが趣旨です。

着手する前に話し合うことで、上の課題が解決し、次のメリットがあります。

- 本書の方向性とあったプルリクエストが生まれやすい
- コントリビューターの時間・労力・才能の無駄遣いが減る
- メンテナーの心理的負担が軽減される

また副次的に次のようなメリットもあります。

- 変更の経緯が追える。変更についてどのような議論がなされたのか、なぜ変更する必要があったのかなどを後の人が知れるようになります。

### issueドリブンの流れ

issueドリブンの流れとしては次のようにします。

1. issueを作る
2. 議論する
3. 議論が熟すなどして、頃合いが良くなったら着手する
4. プルリクエストを作る
5. マージする

本書に変更を加えたいというアイディアはまず、issueとして起票します。issueの内容は次のものが考えられます。

- 何をどうしたいのか？
- それが必要な理由は何なのか？
- やるとなったら自分(issue起票者)が着手したいのか？メンテナーにお願いしたいのか？

issueを起票したら、メンテナーを含めて議論します。議論の内容は次のものが考えられます。

- 取り組むべきか？
- 他のアイディアはあるか？
- 誰がやるべきか？

十分に議論するなどして、メンテナーが最終的に、やるか、やるとしたら誰がやるかを決めます。やらないと決めた場合は、issueをCloseします。

メンテナーがやると判断した場合、メンテナーが指定した担当者が作業に着手します。

担当者は作業をプルリクエストにして、メンテナーがそれをマージします。

### もしもissueドリブンでないプルリクエストが作られた場合

もしも議論をせずにプルリクエストが作られた場合は、次のプロセスを行います。

- issueから始め直す。議論が必要そうであれば、issueからやり直す必要があります。その場合、一定期間(1ヶ月程度)Closeせずに保留とする。
- そのままマージする。議論が必要なく、取り込む必要性が自明なときはマージする。

ただし、できるだけissueドリブンを崩すべきではないと思うので、issueから始め直すがデフォルトフローとなるようにします。

また、issueなしにプルリクエストが作られた場合は、Closeされるリスクが高いことをドキュメントで注意喚起しておきます。

## 副解決策: PULL_REQUEST_TEMPLATE.mdの導入

PULL_REQUEST_TEMPLATE.mdを用意しておき、issueドリブンで行っていることを旨をそれに含めておきます。こうすることで、プルリクエストを作成する際にその内容が表示されるため、新規参加者もissueドリブンに気づきやすくなります。この解決策は、課題1には効果が薄いですが、課題2への解決策にはなります。

## 補助策: GitHub Actionsで「Close {issue_number}」をチェックする

GitHub Actionsでプルリクエストの本文にイシューを閉じる指示「Close {issue_number}」が含まれているかをチェックし、issueドリブンが原則として働く環境づくりをします。

使用するGitHub Action: https://github.com/marketplace/actions/verify-linked-issue

いくらissueドリブンを謳っても、それを働きかける環境がないと形骸化しそうです。形骸化を防ぐためには、このGitHub Actionsが有効そうです。

## 関連PDR

なし

## やること

- [x] PDRを書く
- [x] [はじめて執筆する方へ](https://typescriptbook.jp/writing/getting-started)にまずはissueを作る必要があることを伝える
- [x] [執筆の流れ](https://typescriptbook.jp/writing/how-to-change)を「環境構築からプルリクエストまでの流れ」にタイトルを変える
- [x] PULL_REQUEST_TEMPLATE.mdを作る
- [x] GitHub Actionsで「Close {issue_number}」をチェックする

## このissueが解決するとクローズできるissue

Close #394

**Comment by suin** [comment]
上についてコメントいただきました。

・とても良い思う
・書籍から貢献したくなった方、リポジトリから貢献したくなった方、両者の目に留まるので、もったいない貢献が減りそう
source: https://discord.com/channels/672737595347828736/672737595347828739/1078813510391316520

**Comment by suin** [comment]
↓リポジトリを作って、PULL_REQUEST_TEMPLATE.mdを試してみました。

https://github.com/suinplayground/pull-request-template-md

次のどちらのパターンでも、プルリクエスト作成時にPULL_REQUEST_TEMPLATE.mdの内容がプルリクエスト本文に挿入されることが確認できました。

1. GitHubのUIでForkしてFork先のリポジトリから「Contribute」ボタンを押してプルリクエストを作るケース
2. GitHubのUIでForkボタンを使わずに、Edit in place機能(鉛筆アイコンから編集に入る機能)でプルリクエストを作るケース

**Comment by suin** [comment]
GitHub Actionsで`Closes #123`などが書いていないときにCIをFAILにする手法を試してみました。
https://github.com/suinplayground/try-github-action-check-linked-issues/pull/1
`Closes #123`などがプルリクエストの本文にないと、コメントでも指摘があるので分かりやすいです。
コメントは設定で好きな内容に変えられるようです。

**Comment by suin** [comment]
「issueドリブン」から「チケット駆動」に用語を変更しました。そのほうが一般的な言葉だと思ったからです。

**Comment by suin** [comment]
草稿を書いたので、この内容で良さそうだったらプルリク作ります。

ブランチ:

- https://github.com/yytypescript/book/compare/issues/596

草稿プレビュー:

* [はじめて執筆する方へ | TypeScript入門『サバイバルTypeScript』](https://book-1z4ukxecu-yytypescript.vercel.app/writing/getting-started#%E3%83%97%E3%83%AB%E3%83%AA%E3%82%AF%E3%81%99%E3%82%8B%E5%89%8D%E3%81%AB%E8%A9%B1%E3%81%97%E5%90%88%E3%81%8A%E3%81%86)
* [チケット駆動(プルリクする前に話し合おう) | TypeScript入門『サバイバルTypeScript』](https://book-1z4ukxecu-yytypescript.vercel.app/writing/ticket-driven)
* [環境構築からプルリクエストまでの流れ | TypeScript入門『サバイバルTypeScript』](https://book-1z4ukxecu-yytypescript.vercel.app/writing/how-to-change#%E3%83%97%E3%83%AB%E3%83%AA%E3%82%AF%E3%82%A8%E3%82%B9%E3%83%88%E3%82%92%E9%80%81%E3%82%8B)
* [0010-チケット駆動の執筆 | TypeScript入門『サバイバルTypeScript』](https://book-1z4ukxecu-yytypescript.vercel.app/writing/pdr/0010-ticket-driven)

また、GitHub Actionsによる関連issue未記入のプルリクエストに、コメントをつけるデモはこちらになります:

- https://github.com/yytypescript/book/pull/599#issuecomment-1445202098

**Comment by jamashita** [comment]
- `PULL_REQUEST_TEMPLATE.md` issue駆動ではないPRは
- `ticket-driven.md` 事前に認識合わせできない、そういったPRは

マージされずにクローズとなることがあります。
とあります。意図は理解できるのですがなかなか表現が強く、なにか別の表現ができないかなと考えてみました。

## 案

- このようなPRは作成の経緯（意図）の確認や認識合わせを追って行う必要があり、方針にまだ合わないと判断された場合はマージが延期されたりクローズされることがあります。
- このようなPRは作成の経緯（意図）の確認を追って行いますが、本書の読者の層を鑑みて不要と判断された場合、マージされずにクローズとなることがあります。

難しいですね・・・ 🧐

**Comment by suin** [comment]
@jamashita ご確認ありがとうございます！そうですね、もうすこしソフトにする必要がありそうですね😌

**Comment by suin** [comment]
僕も改善案を考えてみました。次の改善案3はいかがでしょうか？

**問題の箇所**

> 注意点として、issue駆動でないプルリクエストを作成した場合、事前の認識合わせが不十分であるため、そのプルリクエストがクローズされる場合があることをご了承ください。

**改善案3: 過去の失敗事例をベースに伝える**

> 過去には、issue駆動でないプルリクエストが、事前の認識合わせが十分でなかったため本書の方向性と合わせきれず、クローズとなってしまった例もありますので、できる限りissue駆動に則ることをおすすめします。

**Comment by suin** [comment]
PULL_REQUEST_TEMPLATE.mdでは「本プロジェクトではチケット駆動を原則としています。GitHubのキーワードを用いたissueの関連付け機能を用いて、対応したissueをプルリクエストに関連付けてください。」とチケット駆動のページへのリンクだけにとどめて、「マージされずにクローズとなること」は重ねて言わなくてもいいかもしれませんね。

**Comment by jamashita** [comment]
@suin 改善案3いいですね！さすがの文章力です！ 👏  💪

**Comment by suin** [comment]
@jamashita ありがとうございます！原稿を直しておきます！

**Comment by suin** [comment]
プレビューサイト

* はじめて執筆する方へ | TypeScript入門『サバイバルTypeScript』
* チケット駆動(プルリクする前に話し合おう) | TypeScript入門『サバイバルTypeScript』
* 環境構築からプルリクエストまでの流れ | TypeScript入門『サバイバルTypeScript』
* 0010-チケット駆動の執筆 | TypeScript入門『サバイバルTypeScript』

**Comment by suin** [comment]
https://discord.com/channels/672737595347828736/672737595347828739/1079570880390250567
もろもろ見ました
すてき 😍

https://discord.com/channels/672737595347828736/672737595347828739/1079600593619931156
差分読みました、めちゃいいですね！！👶

**Comment by suin** [comment]
> https://discord.com/channels/672737595347828736/672737595347828739/1080290876904976394
> 私も拝見させていただきました、これで問題ないかと思います...！

**Comment by t-yng** [comment]
チケット駆動にするアイディアとても良いと思います！😺

**Comment by suin** [comment]
@t-yng お読みいただきありがとうございます！感謝

**Comment by suin** [comment]
これ以上の意見はなさそうなので運用していこうと思います。

運用してみてダメなところは直していきましょう！
