### ISSUE TITLE
「Prettierでコード整形を自動化しよう」にて、本書フォーマッターのprettierにサンプルコードが過剰修正されている

### ISSUE THREAD

**Issue by yoichi-muraoka** [yytypescript/book#615]
以下のセクションのサンプルコードに間違いがあるようですので、ご確認ください。

[Prettierでコード整形を自動化しよう - CLIオプションで設定](https://typescriptbook.jp/tutorials/prettier#cli%E3%82%AA%E3%83%97%E3%82%B7%E3%83%A7%E3%83%B3%E3%81%A7%E8%A8%AD%E5%AE%9A)

「整形されたコードを見るとセミコロンが消えて、インデント幅が2から4に変更されているのを確認できます。」とありますが、その下に記載されているコードには、セミコロンが残っており、インデント幅も2スペース分のままです。
正しくは、
```javascript
const hello = (name: string) => {
    console.log("Hello,World " + name)
}
```
でないでしょうか？

**Comment by suin** [comment]
@yoichi-muraoka ご報告ありがとうございます！おっしゃるとおり誤植なので修正させていただきます🙇🏻‍♂️

**Comment by suin** [comment]
対処法: サンプルコードの直前に`<!--prettier-ignore-->`を追加するか、サンプルコード内に`// prettier-ignore`を書く

**Comment by suin** [comment]
![CleanShot 2023-03-10 at 19 46 03 png](https://user-images.githubusercontent.com/855338/224296520-3ef9e7bd-8c83-4b1d-a443-32fe69244957.png)

**Comment by suin** [comment]
対応をりょうさんにお願いしました😌
