### ISSUE TITLE
「日英対訳表」の「Assertion Function」の対訳を「アーサーション関数」と正式に定義する

### ISSUE THREAD

**Issue by shota-nukumizu** [yytypescript/book#618]
[日英対訳表](https://typescriptbook.jp/writing/japanese-english-table)のページに、Assertion Functionが日本語不明のカテゴリーに入っているのですが、本書で「アサーション関数」と書かれているので日本語訳を表記したほうがいいのではないですか？

**Comment by shota-nukumizu** [comment]
【該当記事】TypeScript アサーション関数
https://typescriptbook.jp/reference/functions/assertion-functions

**Comment by suin** [comment]
たしかに、事実上対訳が決まってますんで、正式にリストに定義したほうがいいですね！ありがとうございます
