### ISSUE TITLE
インスタンスメソッドとクラスメソッドの表現のしかたを統一しませんか？

### ISSUE THREAD

**Issue by suin** [yytypescript/book#619]
インスタンスメソッド(厳密にはプロトタイプのメソッド)とクラスメソッド(厳密にはコンストラクタのメソッド)を本書で表現したいとき、どう表現するか書き方が決まってません。決めて、統一したいです。

## 僕から提案する統一案

- インスタンスメソッド: `クラス名.prototype.メソッド名` (例: `Array.prototype.map`)
- クラスメソッド: `クラス名.メソッド名` (例: `Array.isArray`)
- MDNやJS Primerと同じ方法です

## 作るもの

- 執筆者向けのガイドライン

**Comment by suin** [comment]
「Promise.prototype.thenは、〜」と書くより「Promiseのthenメソッドは、〜」と書いたほうが読者フレンドリーかもしれませんね。

**Comment by suin** [comment]
ありがとうございます！

**Comment by jamashita** [comment]
instance methodの扱いについて
- `Xxxx.prototype.yyyy()` と書く
- `Xxxx` の `yyyy` メソッドは、と文章としては紹介する
