### ISSUE TITLE
PRのテンプレートにclose #<ISSUEの番号> を追加しませんか？

### ISSUE THREAD

**Issue by t-yng** [yytypescript/book#626]
## やりたいこと
PRのテンプレートに`close #<ISSUEの番号>`を追記する

## 変更の理由
チケット駆動になったことでPR作成時に関連するISSUEの紐付けをする運用になった。テンプレートに `close #<ISSUE番号>`と記載があると、PRを作成する時にISSUEの関連付けが少しやりやすくなり忘れ防止にも繋がりそうだと思いました。

**Comment by suin** [comment]
やりましょう！

**Comment by t-yng** [comment]
こちら、サクッとできそうなのでやっておきます！
