### ISSUE TITLE
`never`が絡んだ型推論についての質問です

### ISSUE THREAD

**Issue by matoruru** [yytypescript/book#627]
型の一致不一致を確認するための型`Equal`を作りました。

```ts
type Equal<A, B> = A extends B ? (B extends A ? "true" : "false") : "false"
```

`Equal`に渡す引数の`A`と`B`が等しければ`"true"`、そうでなければ`"false"`になるように作っています。

```ts
type Test1 = Equal<number, number>
// true

type Test2 = Equal<number, string>
// false
```

しかし`never`を渡した時だけ挙動が変わってしまいます。

```ts
type Test3 = Equal<never, string>
// never

type Test4 = Equal<never, never>
// never

type Test5 = Equal<string, never>
// false
```

`Equal`の条件では等しくなければ`"false"`に推論されるはずですし、`Test4`では`never`と`never`の比較なので`"true"`に推論されるのが妥当だと考えていました。`Test5`だけ`"false"`に推論されているのも理解できません。

これは`never`の仕様から説明できるでしょうか・・・？

ご回答お待ちしています。よろしくお願いいたします。

関連ページ: https://typescriptbook.jp/reference/statements/never

**Comment by canalun** [comment]
たまたまこのissueを見かけ、参考になりそうな情報を持っていたので一応共有いたします。参考になれば幸いです。

# 挙動の理由
前提として、`T extends U ? X : Y`という式の`T`に`never`を代入させると、その結果は例外なく`X`や`Y`の値とは無関係に`never`になると言われています。
私自身もソースコードを直接追ってみたことはないのですが、下記リンク先の説明が自分にとっては分かりやすく納得しています。
https://scrapbox.io/mrsekut-p/T_%E3%81%8Cnever%E3%81%AE%E6%99%82%E3%81%AE%E3%80%81T_extends_.._%E3%81%AF%E3%80%81%E5%95%8F%E7%AD%94%E7%84%A1%E7%94%A8%E3%81%A7never%E3%81%AB%E3%81%AA%E3%82%8B#:~:text=%E3%81%AA%E3%81%9C%E3%81%8B%EF%BC%9F%0A%09union%E5%9E%8B,%E3%81%AA%E3%81%A3%E3%81%A6%E3%81%97%E3%81%BE%E3%81%86
(英語でも良ければ、異なる言い方のほぼ同じ説明がこちらにもありました😃: https://stackoverflow.com/a/65492934)

なお、この挙動は公式ドキュメントでは言及されていない(ように思える)のですが、公式のissuesでは過去に言及されているようです👶
https://github.com/microsoft/TypeScript/issues/23182#issuecomment-379094672

この前提を踏まえると、 @matoruru さんの仰る挙動も説明がつくのではと考えています。

```type Test3 = Equal<never, string> // never```
```type Test4 = Equal<never, never> // never```
これら2つは、`never`がConditional Types(extendsの式)の第一項にくるので問答無用で`never`になってしまうのかと考えられます。

一方で
```type Test5 = Equal<string, never> // false```
は、
```string extends never ? (never extends string ? "true" : "false") : "false"```
となりますが、これは最初の`string extends never`が偽と評価されて`false`に転ぶのではないかと思いました。

# 解決策のアイデア

解決策のアイデアとしては、第一項を配列型にしてしまう策があるようです(先ほど紹介したissuesの議論にも登場しているようです: https://github.com/microsoft/TypeScript/issues/23182#issuecomment-379091887)。
```type Equal<A, B> = [A] extends [B] ? ([B] extends [A] ? "true" : "false") : "false"```

これで実際に試してみると、下記のように期待される結果になりました！👶
![スクリーンショット 2023-03-04 20 51 16](https://user-images.githubusercontent.com/61643630/222898795-48cb278e-5788-4739-a6c5-3c14aa3dc150.png)

playgroundへのリンク: https://www.typescriptlang.org/play?#code/C4TwDgpgBAogjgVwIYBsA8BBANFAQgPigF4oBtDAXSggA9gIA7AEwGczcqB+KAClI+p1GrMpSjcARMABOCCBKgAuKBIBmqFvICUSlepSaJAKCOhIUACoQWwAIzFYiVGgYIAtgCMI0nK8-f8IyYIAGMUJGloEIB7BhsoehtbZSsk02s7IwB6LKgAPU4TM2hU4AAmB3hkdD8vHygbaQBLBgBzQOCwiKjY+MTylIyy9JthnPzC03ASjIBmSqcaiAA3bxxGlvag0PDIqBi44AS5wZtZkeBz8YKi6csMgBYF6pcVtagGN+kOne793qO-Qep2ADwuYOuk2K9xsAFZns4Nm1fF8fl09gc+hlYSDYRc8ZCgA

ただ、私自身あまりわかっていないのですが、TSで型の同一性を正確に評価するにはなんだかもう少し工夫が必要なようです……！
これは公式のissuesでも議論されたことがあり、結論としては下記リンク先の型計算で実現できるようなのです。
https://github.com/Microsoft/TypeScript/issues/27024#issuecomment-421529650
この仕組みについて調べられている記事もちらほらある(e.g. https://zenn.dev/yumemi_inc/articles/ff981be751d26c)ようなのですが、あまりわかっておらずここについては特に自分からはこれ以上伝えられなさそうです……すみません！

**Comment by suin** [comment]
これはconditional typeがunion distributionするのと、neverが空のユニオンであるために発生する事象です。

conditional typeの型パラメーターはユニオンに展開されます。

```ts
type X<T> = T extends string ? 'string' : 'not-string';
```

のような型があるとき、

```ts
type Y = X<string | number>;
```

は

```ts
type Y = X<string> | X<number>;
```

のように分配されます。

次のようにneverを渡した場合ですが、

```ts
type Y = X<never>;
```

neverは空のユニオンと決められているので、分配が行えなくなります。そのため、「分配できませんでした」の意味でneverが返されます。

本当にneverが空のユニオンかどうかは、次のように1つの型から構成されるユニオン型から、その最後の1つの型を取り除くことで確認することもできます。

```ts
type X = Exclude<string, string>;
// X は neverになる
```

ちなみに、neverをconditonal typeで扱える方法もあります: https://zenn.dev/suin/scraps/8828d6c915298c

**Comment by suin** [comment]
@canalun さんも回答ありがとうございます！

**Comment by suin** [comment]
理解の手助けになったようでなによりです😌
