### ISSUE TITLE
誤植「loadingが`true`のとき」→「loadingが`false`のとき」

### ISSUE THREAD

**Issue by toku-sa-n** [yytypescript/book#635]
素晴らしい本をありがとうございます．

現在猫画像ジェネレータのページを読み進めています．「ページを表示したときに画像を表示する」の節において，以下のような記述があります．

> ❸ 最後に画像を表示するロジックです。||は論理和演算子で、loadingがtrueのときに<img>要素を表示します。
>
> ```javascript
>   return <div>{loading || <img src={imageUrl} />}</div>;
> ```

しかしながらこれは短絡評価の結果から，`loading`が`false`の時に画像が表示されるのではないでしょうか．すなわち`loading`が`true`であるならばそこで評価が終了し，`false`ならば評価が止まらず，次の`img`の評価に進むと考えているのですが，これは正しいでしょうか．

ご回答いただければ幸いです．

関連ページ: https://typescriptbook.jp/tutorials/nextjs

**Comment by suin** [comment]
ご報告ありがとうございます。これは誤植ですね。

ご指摘のとおり`loading`が`false`のときに画像が表示されるのが正しいです。

> 最後に画像を表示するロジックです。||は論理和演算子で、loadingが<del>true</del>**false**のときに要素を表示します。

**Comment by toku-sa-n** [comment]
ありがとうございます。後ほどPRを送ろうと思いますがよろしいでしょうか？

**Comment by suin** [comment]
@toku-sa-n PRまでして頂けるんですか😆 ぜひお願いします！
