### ISSUE TITLE
「Prettierでコード整形を自動化しよう」にて，「見づらいコード」が既に整形されている

### ISSUE THREAD

**Issue by toku-sa-n** [yytypescript/book#637]
[TypeScriptScriptを自動整形する](https://typescriptbook.jp/tutorials/prettier#typescript%E3%82%92%E8%87%AA%E5%8B%95%E6%95%B4%E5%BD%A2%E3%81%99%E3%82%8B)において，「見づらいコード」とされているものが既に整形されています．

Related: https://github.com/yytypescript/book/issues/615

https://typescriptbook.jp/tutorials/prettier

**Comment by suin** [comment]
![CleanShot 2023-03-10 at 19 47 10 png](https://user-images.githubusercontent.com/855338/224296780-bb645d15-ebdb-4b16-a995-077a3f09a15a.png)

**Comment by suin** [comment]
ぐちゃぐちゃにする案

-  不自然にスペースがあったり、足りなかったり `( name : string)=>    {`
- `console`の前にインデントがない
- 無駄にどこか改行がある
- 謎の空行

**Comment by suin** [comment]
対応をりょうさんにお願いしました😌

**Comment by suin** [comment]
@ryo-manba  りょうさん、issue2件とも対応ありがとうございました！

**Comment by suin** [comment]
@toku-sa-n さんもご報告ありがとうございました！
