### ISSUE TITLE
誤植「project、...相対パスで指定」→「project`は`、...相対パスで指定」

### ISSUE THREAD

**Issue by toku-sa-n** [yytypescript/book#638]
> projectとtsconfigRootDirはTypeScript ESLint独自のオプションです。tsconfigRootDirはプロジェクトルートの絶対パスを指定します。project、ESLint実行時に使うコンパイラ設定ファイルをtsconfigRootDirからの相対パスで指定します。これらの設定は、TypeScript ESLintが型情報を参照するために必要な設定です。

projectのあとの「は」が抜けています．

https://typescriptbook.jp/tutorials/eslint#typescript-eslint%E3%81%AE%E8%A8%AD%E5%AE%9A%E3%83%95%E3%82%A1%E3%82%A4%E3%83%AB%E3%82%92%E4%BD%9C%E3%82%8B

**Comment by suin** [comment]
@toku-sa-n ご報告とPRありがとうございます！PRマージさせていただきました。
