### ISSUE TITLE
ハイパーリンク対象のテキストの範囲のズレのを直す

### ISSUE THREAD

**Issue by hayashi-ay** [yytypescript/book#641]
https://typescriptbook.jp/reference/values-types-variables/undefined-vs-null

リンク対象のテキストに`「`が含まれていない。

## 提案
以下のどちらかにする。

1. [「nullは使わない」というたった1行のシンプルなガイドライン](https://github.com/Microsoft/TypeScript/wiki/Coding-guidelines#null-and-undefined)

2. 「nullは使わない」というたった1行のシンプルな[ガイドライン](https://github.com/Microsoft/TypeScript/wiki/Coding-guidelines#null-and-undefined)

## キャプチャ
<img width="795" alt="image" src="https://user-images.githubusercontent.com/39038230/224453336-191cfed0-3bf5-4bff-a83b-1816c0f671a5.png">

**Comment by suin** [comment]
@hayashi-ay ご報告ありがとうございます！

**Comment by suin** [comment]
頂いた提案にある1の案を採用します。
