### ISSUE TITLE
「列挙型(enum)の問題点と代替手段 」において，「構造的部分型」へのリンクが正しくない

### ISSUE THREAD

**Issue by toku-sa-n** [yytypescript/book#644]
[文字列列挙型だけ公称型になる](https://typescriptbook.jp/reference/values-types-variables/enum/enum-problems-and-alternatives-to-enums#%E6%96%87%E5%AD%97%E5%88%97%E5%88%97%E6%8C%99%E5%9E%8B%E3%81%A0%E3%81%91%E5%85%AC%E7%A7%B0%E5%9E%8B%E3%81%AB%E3%81%AA%E3%82%8B)の節に存在する「構造的部分型」へのリンクが，この列挙型の問題点のページにリンクされていますが，おそらく正しいリンクは[構造的部分型 (structural subtyping)](https://typescriptbook.jp/reference/values-types-variables/structural-subtyping)へのリンクだと思います．

**Comment by suin** [comment]
@toku-sa-n ご報告ありがとうございます！ご指摘の通り誤植です。

**Comment by suin** [comment]
ご報告・PRありがとうございました！マージさせていただきました。
