### ISSUE TITLE
誤植：「変数`x`代入し」→「変数`x`に代入し」

### ISSUE THREAD

**Issue by toku-sa-n** [yytypescript/book#646]
> たとえば、次の例です。オブジェクト{ n: 1 }を変数x代入し、さらにxを関数changeの引数yに代入すると、xとyは同じオブジェクトを参照します。

https://typescriptbook.jp/reference/functions/pass-by-value#javascript%E3%81%AF%E5%80%A4%E6%B8%A1%E3%81%97

**Comment by suin** [comment]
ご報告とPRありがとうございます！
