### ISSUE TITLE
誤植「log: 5」→「log: 5`n`」

### ISSUE THREAD

**Issue by hayashi-ay** [yytypescript/book#649]
https://typescriptbook.jp/reference/values-types-variables/bigint

bigint型と評価されるので5nになる。

##  キャプチャ
**当該箇所**
<img width="910" alt="image" src="https://user-images.githubusercontent.com/39038230/224502589-c6f6d4e0-be10-4d0c-a502-22476349decd.png">

**Google Chrome(MacOS)でのconsole.logの出力**
<img width="508" alt="image" src="https://user-images.githubusercontent.com/39038230/224502621-2e99dd25-ee55-497e-ba45-8540608008f7.png">

**Comment by suin** [comment]
@hayashi-ay 誤植のご報告ありがとうございます！

**Comment by suin** [comment]
## 修正すること

1. 1行目の`//=> 5n`を消す (4行目のtwoslashのログ記法と重複しているため)
2. 2行目の無駄な空行を消す
3. 4行目の`// @log: 5`を`// @log: 5n`に変更する

**Comment by suin** [comment]
@hayashi-ay  ご報告・PRありがとうございました！マージさせていただきました。
