### ISSUE TITLE
「definite assignment assertion」を「明確な割り当てアサーション」にする

### ISSUE THREAD

**Issue by hayashi-ay** [yytypescript/book#652]
https://typescriptbook.jp/reference/values-types-variables/definite-assignment-assertion

他の用語については日本語訳があるが、definite assignment assertionには日本語訳がない。

## 提案
「明確な割り当てアサーション」

[プログラミングTypeScript](https://www.oreilly.co.jp/books/9784873119045/)では、「Definite Assignment Assertions」を「明確な割り当てアサーション」と訳している。

## キャプチャ
[英語版見出し](https://www.oreilly.com/library/view/programming-typescript/9781492037644/)
<img width="444" alt="image" src="https://user-images.githubusercontent.com/39038230/224524010-eb9246ba-06bd-449d-ad1b-ce5cc6fc7893.png">

[日本語訳見出し](https://www.oreilly.co.jp/books/9784873119045/)
<img width="380" alt="image" src="https://user-images.githubusercontent.com/39038230/224524015-51c23f21-2050-45b1-95fd-9c9c9315cc97.png">

**Comment by suin** [comment]
## 提案

現状日本語訳を踏襲する対象として下記文献があります。

- TypeScript Deep Dive日本語版
- MDN日本語版

これに

- オライリーの[プログラミングTypeScript](https://www.oreilly.co.jp/books/9784873119045/)

も追加しませんか？

その上で、「Definite Assignment Assertions」を「明確な割り当てアサーション」と翻訳していくのはどうでしょうか。

**Comment by suin** [comment]
## Todo

- [definite assignment assertion](https://typescriptbook.jp/reference/values-types-variables/definite-assignment-assertion)の修正
  - なお序文にて「明確な割り当てアサーション」が初出する場所は「明確な割り当てアサーション(definite assignment assertion)」のように英語訳を注釈する
- [日英対訳表](https://typescriptbook.jp/writing/japanese-english-table)に「definite assignment assertion」と「明確な割り当てアサーション」を追加する
