### ISSUE TITLE
誤植「grade === "number"」→「`typeof` grade === "number"」

### ISSUE THREAD

**Issue by toku-sa-n** [yytypescript/book#653]
https://typescriptbook.jp/reference/object-oriented/interface/instanceof-and-interfaces#%E3%82%A4%E3%83%B3%E3%82%BF%E3%83%BC%E3%83%95%E3%82%A7%E3%83%BC%E3%82%B9%E3%81%AE%E5%88%A4%E5%AE%9A%E3%81%AB%E3%81%AF%E5%9E%8B%E3%82%AC%E3%83%BC%E3%83%89%E9%96%A2%E6%95%B0%E3%82%92%E4%BD%BF%E3%81%86

> 
> ```typescript
> interface Student {
>   name: string;
>   grade: number;
> }
>  
> // Student型かを判定する型ガード関数
> function isStudent(value: unknown): value is Student {
>   // 値がオブジェクトであるかの判定
>   if (typeof value !== "object" || value === null) {
>     return false;
>   }
>   const { name, grade } = value as Record<keyof Student, unknown>;
>   // nameプロパティーが文字列型かを判定
>   if (typeof name === "string") {
>     return false;
>   }
>   // gradeプロパティーが数値型かを判定
>   if (grade === "number") {
>     return false;
>   }
>   return true;
> }
> ```

`grade === "number"`となっていますが，正しくは`typeof grade === "number"`のはずです．

**Comment by suin** [comment]
誤植のご報告・PRありがとうございました！マージさせていただきました。
