### ISSUE TITLE
「undefinedは変数です」が説明不足感があるため改善しませんか？

### ISSUE THREAD

**Issue by MSK1206** [yytypescript/book#655]
https://typescriptbook.jp/reference/values-types-variables/undefined

![97E96B5C-2046-4A79-9898-CA895E7A6F8A](https://user-images.githubusercontent.com/86665622/224689327-ee906265-87a2-4605-8bd5-914f1a4e1c0f.jpeg)

- undefinedリテラル、の文章内
> 実はundefinedは変数です。

上記は、undefinedは定数の間違いでしょうか？
変数が未定義の場合に返す定数と思ってたのですが、気になりご報告致しました。

**Comment by MSK1206** [comment]
変数の位置付けでも有るとの事で自己解決しました。失礼しました。

**Comment by suin** [comment]
解説不足だと思うので、表現改善のために再オープンします。

**Comment by suin** [comment]
どのように改善するか検討しましょう。

**Comment by shota-nukumizu** [comment]
こちらの質問をChatGPTに丸投げしてみたら、以下のような回答が返ってきました。

![image](https://user-images.githubusercontent.com/82911032/228401658-83831fef-3af0-4f37-aeb5-c0716d40bfb8.png)


TypeScriptにおける`undefined`の要点としては、次のようなものが考えられます。

* 値が未定義であることを示すプリミティブ値
* 宣言された変数に値が割り当てられなかった場合、関数が値を返さなかった場合等に値が未定義であることを示すために使う
* JavaScriptにおける`false`として出力される値の１つであり、条件分岐でよく活用される
* 一般的には`null`が未定義の値を表現するために使われる

別途`null`と`undefined`の違いを表記しておいたほうがいいかもしれませんね。しかし、そうすると『サバイバルTypeScript』のコンテンツが増えるので初心者に易しくなくなる可能性が高いですが。

**Comment by jamashita** [comment]
このissueが言いたいのは、 `undefined` というリテラルは存在しないということであるのではないですかね。
要するに `undefined` 自体は `undefined = 1` といった代入ができる変数で（とはいえ上書き禁止されていた気がしますが）あるよ。ということかと。
そんなこんなの経歴があって値が `undefined` であるかの比較に `x === undefined` を使うより `typeof x === 'undefined'` をつかほうが安全ということも経緯としてあったり

**Comment by MSK1206** [comment]
jamashitaさまの仰っている経緯もあり、違和感が有り上げたissueでしたが、本質は変数であると言う事で納得致しましたので、特にOpenしておく理由がなければ当issueにつきましてcloseして下さって大丈夫です。
