### ISSUE TITLE
誤植「i`z`Zero」→「i`s`Zero」

### ISSUE THREAD

**Issue by H1rono** [yytypescript/book#657]
[Jestでテストを書こう](https://typescriptbook.jp/tutorials/jest)のページで誤植と思われるものを見つけました。

https://github.com/yytypescript/book/blob/a9b7898ecbd9e68f102957d764a46eca0feb757a/docs/tutorials/jest.md?plain=1#L186

https://github.com/yytypescript/book/blob/a9b7898ecbd9e68f102957d764a46eca0feb757a/docs/tutorials/jest.md?plain=1#L224-L225

これが誤植であると確認出来次第、プルリクを出そうと思います。

**Comment by suin** [comment]
@H1rono ご報告・PRありがとうございました！マージさせていただきました。
