### ISSUE TITLE
サバイバルTypeScriptが大きすぎます。超入門的なコンテンツを考えませんか？

### ISSUE THREAD

**Issue by suin** [yytypescript/book#670]
当初はコンパクトに始まったサバイバルTypeScriptですが、年数が経過するにつれてコンテンツが充実してきていて、すべてを読むにはかなり時間を要する情報源になってきました。特に「読んで学ぶ」(リファレンス部分)は区切りなくずっと読める構造になっているので、読者からするとゴールがかなり遠く感じてしまうようです。リファレンス部分は困ったときにググってたどり着く場所としての役割があるので、そのままでいいです。

その代わりに、1時間程度でTypeScriptのおおまかな概要を把握できるような、超入門というか、超要約のようなページがあったほうがいいと思います。イメージとしては次のようなページです。

* [とってもやさしいGo言語入門](https://zenn.dev/sharefull_blog/articles/1fb628d82ed79b?redirected=1)
* [とほほのRust入門 - とほほのWWW入門](https://www.tohoho-web.com/ex/rust.html)
* [他言語からのRuby入門](https://www.ruby-lang.org/ja/documentation/ruby-from-other-languages/)

**Comment by hayashi-ay** [comment]
自分も似た感想です。初学者に勧めるには分量が多いなと思います。

**Comment by hayashi-ay** [comment]
このページとはまた別の想定ですか？
https://typescriptbook.jp/typescript

**Comment by hayashi-ay** [comment]
https://github.com/yytypescript/book/issues/149

**Comment by shota-nukumizu** [comment]
まとめページに似たようなものを冒頭に掲載するなら、最低限でも以下の様なことを簡潔に説明したほうがいいのではないかと思います。(Google検索でよく出力されるチートシートが最も良い具体例？)

* TypeScriptとは
* TypeScriptの強み
* 型定義とは、そのメリット
* 環境構築
* 基本的な文法(データ型、条件分岐、繰り返し)
* 活用事例

あるいは、[公式のチートシート](https://www.typescriptlang.org/cheatsheets)と似たような感じで、文法のエッセンスだけ抽出してまとめたものを画像形式で共有するのもいいかもしれません。

**Comment by suin** [comment]
> このページとはまた別の想定ですか？ https://typescriptbook.jp/typescript
> 
> #149

#149 は実際の課題が生まれる前に想像で作られたissueでしたが、今は実際に課題として観測できているので、タイミング的にちょうどいいと思うので、この機会にゼロベースで考えたいとおもいます！

**Comment by suin** [comment]
> まとめページに似たようなものを冒頭に掲載するなら、最低限でも以下の様なことを簡潔に説明したほうがいいのではないかと思います。(Google検索でよく出力されるチートシートが最も良い具体例？)
> 
> * TypeScriptとは
> * TypeScriptの強み
> * 型定義とは、そのメリット
> * 環境構築
> * 基本的な文法(データ型、条件分岐、繰り返し)
> * 活用事例
> 
> あるいは、[公式のチートシート](https://www.typescriptlang.org/cheatsheets)と似たような感じで、文法のエッセンスだけ抽出してまとめたものを画像形式で共有するのもいいかもしれません。

僕もおおまかにこの構成がいいと思います！

**Comment by suin** [comment]
**ステーキファースト構想**

現状は、トップページ(「はじめに」のページ)では、本書についての解説が行われています。トップページをTypeScript超入門ページにし、現在の「はじめに」はその次のページにするアイディアがあります。

理由

- 「前置きはいいから、早くTSについて教えてくれ！」というニーズもあるかと思うから。
- 現状、トップページの流入が最も多く、そこで読者を満足させられることで、続きを読んでもらいやすくなると思うから。
- 現状、トップページが最もSEOが強い。そして、まとめ系ページはSEOが強い。この2つを組み合わせたらSEOが最強になりそうだから。

さらなる構想として、トップページは単なるMarkdownのレンダリングでなく、少しグラフィックやギミックを加えて、視覚的に楽しくし、また、TypeScriptコンパイルなどをその場で体験できたりするインタラクションも備えられたらとも考えています。

**Comment by suin** [comment]
### アウトラインを検討中です。

https://www.figma.com/file/nb7IWIbTyzXnRON6Qz3i8p/%E3%82%B5%E3%83%90%E3%82%A4%E3%83%90%E3%83%ABTypeScript%E3%81%AE%E8%B6%85%E5%85%A5%E9%96%80%E3%83%9A%E3%83%BC%E3%82%B8?node-id=0%3A1&t=x4iy5Zcc0c0orznT-1

**Comment by suin** [comment]
## 方針: 他のコンテンツより力を入れます

- トップページのコンテンツにする予定である
- トップページは10万PV/月に匹敵する
- インパクトが大きいので、しっかり作り込んでいきたい

**Comment by suin** [comment]
## 「TypeScriptって良さそう！」「TypeScriptはこんな特徴があるんだ！」と読者に思ってもらうコンテンツになることが目標

- 本書プロジェクトの発足理念は「TypeScriptプログラマーを少しでも増やすこと」。なので本書の顔となる超入門は、TypeScriptを魅力的に思ってもらえるコンテンツになるように心がけます。
- TypeScriptの言語特徴(type, interface, 型推論など)を個別に紹介することで、「TypeScriptはこんな特徴があるんだ！」と思ってもらい、「TypeScriptって良さそう！」という感想に説得力を与えます。

要するに、TypeScriptのプロモーションとなるようなコンテンツを目指します。

**Comment by suin** [comment]
## ここまでの要約

課題:
サバイバルTypeScriptが大変充実しており、すべてを読むのに時間がかかるため、読者がゴールが遠く感じる可能性がある。

方針:
1. TypeScriptの概要を1時間程度で把握できる「超入門」、「超要約」ページを作成する。参考にするイメージは、[とってもやさしいGo言語入門](https://zenn.dev/sharefull_blog/articles/1fb628d82ed79b?redirected=1)、[とほほのRust入門 - とほほのWWW入門](https://www.tohoho-web.com/ex/rust.html)、[他言語からのRuby入門](https://www.ruby-lang.org/ja/documentation/ruby-from-other-languages/)。
2. 現在のトップページ(「はじめに」のページ)をTypeScript超入門ページにし、現在の「はじめに」はその次のページにする。これにより、「前置きはいいから、早くTSについて教えてくれ！」というニーズに対応する。
3. 最初に提供されるTypeScript超入門ページのコンテンツに力を入れ、視覚的に楽しいデザインやインタラクションを取り入れる。これにより、トップページのインパクトを大きくし、続きを読んでもらいやすくする。
4. TypeScript超入門ページでは、TypeScriptの言語特徴を個別に紹介し、「TypeScriptはこんな特徴があるんだ！」と思ってもらい、「TypeScriptって良さそう！」という感想に説得力を与える。これにより、TypeScriptプロモーション効果のあるコンテンツとする。
