### ISSUE TITLE
誤植「今まで`と`おり」→「今まで`ど`おり」、「n`とおり`」→「n`通り`」加えて、textlintの「通り」のルールを外す

### ISSUE THREAD

**Issue by manjuu-eater** [yytypescript/book#672]
https://typescriptbook.jp/reference/import-export-require

誤字が1ヶ所、誤字という訳ではないが通常漢字で書くものが3ヶ所ありました。

----
パターン①
これは誤字です。通常「いままでどおり」と読まれますが、「とおり」となっています。
https://github.com/yytypescript/book/blob/3912aa575f619a8be57a1107af81a8c81f625a5d/docs/reference/import-export-require.md?plain=1#L350

----
パターン②
誤字という訳ではないのですが、通常漢字で書くと思います。

https://github.com/yytypescript/book/blob/3912aa575f619a8be57a1107af81a8c81f625a5d/docs/reference/import-export-require.md?plain=1#L189

https://github.com/yytypescript/book/blob/3912aa575f619a8be57a1107af81a8c81f625a5d/docs/reference/import-export-require.md?plain=1#L236

https://github.com/yytypescript/book/blob/3912aa575f619a8be57a1107af81a8c81f625a5d/docs/reference/import-export-require.md?plain=1#L308

----
追記：前述のパターン②はわざとだったようです。
表記ゆれ修正の処理があったようなのですが、パターン①はこの処理による誤変換のように思われます。
https://github.com/yytypescript/book/blob/6000b5b6771f49f1441ab9a9a16ca33a6cf01e60/prh/js-primer.yml#L651-L653

これは個人的な感想なのですが、「このとおり」「次のとおり」の表記ではなく「n通り」の使い方の場合、漢字による表記の方が適切なのではないかと思います。
軽く検索したところ、「その他、名詞ではなく助数詞としての意味で用いる場合もひらがなではなく漢字で書かれることが多いです。」という解説もありました。
https://kokugoryokuup.com/touri-difference/

**Comment by suin** [comment]
js-primerさんのtextlintをそのまま継承したもので、本書としてはひらがなの「とおり」にこだわる必要はないと思うので、textlintからこのルールを外し、「どおり」や「通り」の誤植を直すというのでいいと思います。特に異論がなさそうなら、この方針でやりたいと思います。

**Comment by suin** [comment]
ご報告・PRありがとうございました！マージさせていただきました。
