### ISSUE TITLE
誤植「`Regexp`.prototype.match」→「`String`.prototype.match」

### ISSUE THREAD

**Issue by kuniga** [yytypescript/book#678]
すばらしいドキュメントを公開していただき、ありがとうございます。とても勉強になります。
ドキュメントを読んでいて見つけたのですが、以下の箇所は `String.prototype.match()` の誤りでしょうか。
https://github.com/yytypescript/book/blob/b6833a9/docs/reference/builtin-api/regexp.md?plain=1#L56

**Comment by suin** [comment]
ご報告ありがとうございます！ご指摘のとおり誤植です🙇🏻‍♂️

**Comment by jamashita** [comment]
ご指摘ありがとうございます！
