### ISSUE TITLE
年代に追従する「2020年の今日でも」→「2023年の今日でも」

### ISSUE THREAD

**Issue by kawanohiroki** [yytypescript/book#679]
https://typescriptbook.jp/overview/before-typescript

すばらしいドキュメントの提供をありがとうございます。
このセクションの文末に
「しかし、TypeScriptの目玉である「型」は、2020年の今日でもJavaScriptの仕様には盛り込まれていません。」
との記述がありますが、今はもう2023年なので現状を確認したうえで2023年時点の仕様に応じて、必要であれば改訂していただけるとよいと思いました。

**Comment by suin** [comment]
こんにちでもJavaScriptには型チェックがないので年数を更新してもいいですね！

**Comment by sontixyou** [comment]
こちら、着手します。

**Comment by suin** [comment]
@sontixyou PRありがとうございました！マージしました。
