### ISSUE TITLE
「関数宣言」のリンク先が「関数式」になっている誤りを直す

### ISSUE THREAD

**Issue by kawanohiroki** [yytypescript/book#681]
https://typescriptbook.jp/reference/functions/function-expression
とても有益なドキュメントの提供を本当にどうもありがとうございます。

このページの冒頭に二箇所、[関数宣言]へのリンクが設定されていますが、リンク先が間違っているようです。

該当箇所：
1. 関数式の構文は、[関数宣言](https://typescriptbook.jp/reference/functions/function-expression)と同じです。
2. [関数宣言](https://typescriptbook.jp/reference/functions/function-expression)は文でしたが、関数式は式です。

訂正内容：
いずれのリンク先も正しくは下記になると思われます。
https://typescriptbook.jp/reference/functions/function-declaration

**Comment by suin** [comment]
ご報告ありがとうございます！ご指摘のとおり誤植です🙇🏻‍♂️

**Comment by jamashita** [comment]
ご報告ありがとうございます。こちら修正いたします 🙇
