### ISSUE TITLE
誤植「swi`ct`h」→「swi`tc`h」

### ISSUE THREAD

**Issue by tojimasan** [yytypescript/book#692]
## 概要

- 表題の通りですが、[TypeScriptでtypeofを使うとifやswicthでその型として使うことができる] でswicthとタイポを発見しました(https://typescriptbook.jp/reference/values-types-variables/typeof-operator#typescript%E3%81%A7typeof%E3%82%92%E4%BD%BF%E3%81%86%E3%81%A8if%E3%82%84swicth%E3%81%A7%E3%81%9D%E3%81%AE%E5%9E%8B%E3%81%A8%E3%81%97%E3%81%A6%E4%BD%BF%E3%81%86%E3%81%93%E3%81%A8%E3%81%8C%E3%81%A7%E3%81%8D%E3%82%8B)

## やること

- タイポ修正
  - swicth → switch
  - 該当箇所 https://github.com/yytypescript/book/blob/bc6273bfe3dd48e59fb4bff25261fbb6d34b53d7/docs/reference/values-types-variables/typeof-operator.md?plain=1#L22

**Comment by suin** [comment]
ご報告・PRありがとうございました！マージさせていただきました。
