### ISSUE TITLE
質問です: `拒否されたPromiseをawaitしたとき`と`拒否されたPromiseをcatchする`の違い

### ISSUE THREAD

**Issue by yukiyohure** [yytypescript/book#700]
`拒否されたPromiseをawaitしたとき`と`拒否されたPromiseをcatchする`のerrorの取り扱いの違いがわからなかったので質問させてください。
二つともcatch句でerrorを捕捉できるよ、ということを教えてくれているのかと理解しました。
違いがあるとすれば、一つ目と二つ目のcatch句に渡ってくるerrorの中身が違ってくるということでしょうか？

関連ページ: https://typescriptbook.jp/reference/asynchronous/await

**Comment by jamashita** [comment]
結論を先に申しますと捕捉されるerrorに違いはありません。

ある関数`func1()`があり、その関数`func2()`が内部でPromiseを返す`func2()`を呼んだとします。コードはこのようなものを想定してください。

```ts
async function func1(): Promise<unknown> {
    // なにかの処理
    
    XXXX func2();
}
```

この`XXXX`の部分が

1. `return await`のときは`func2()`が履行されたときはその値を返し、拒否時は`func1()`のcatchでerrorを捕捉できます
2. `await`のときは`func2()`に戻り値を返すことができません。拒否時は1.と同様`func1()`のcatchでerrorを捕捉できます
3. `return`のときは`func1()`を呼び出した関数に履行された値も拒否されたerrorも返します。`func1()`内ではcatchがあってもerrorを捕捉できません。

**Comment by jamashita** [comment]
@yukiyohure issueを一旦閉じますが、こちらの回答でまだ説明が足りない場合は問題を開いて再度質問継続ください 🙇 
またご意見をもとによりわかりやすい表現を心掛け #743 にて修正しようと思います
ありがとうございます 🙇

**Comment by yukiyohure** [comment]
@jamashita 
解説と表現改善のIssueも作成いただきありがとうございます！理解できました🤓
更新楽しみにしております！
