### ISSUE TITLE
標準ライブラリ型定義の参照先リンク切れを修正する

### ISSUE THREAD

**Issue by yukiyohure** [yytypescript/book#701]
```
標準ライブラリの型定義の参照方法
```
にて紹介されているGithubリンクが二つともリンク切れしているようです。

誤: https://github.com/microsoft/TypeScript/tree/master/lib
正: https://github.com/microsoft/TypeScript/tree/main/src/lib

誤: https://github.com/microsoft/TypeScript/blob/main/lib/lib.es5.d.ts#L1170
正: https://github.com/microsoft/TypeScript/blob/main/src/lib/es5.d.ts#L1246

関連ページ: https://typescriptbook.jp/reference/generics/built-in-libraries-using-generics

**Comment by jamashita** [comment]
@yukiyohure お返事大変遅くなりすみません。そしてご指摘、提案ありがとうございます。
ただいま確認しましたところこちらのPRにて修正がされておりました。

<https://github.com/yytypescript/book/pull/720>

またお気づきがございましたらお教えください。よろしくお願いいたします。
