### ISSUE TITLE
誤植「値`が`有無を確認する」→「値`の`有無を確認する」

### ISSUE THREAD

**Issue by osushicrusher** [yytypescript/book#702]
https://typescriptbook.jp/reference/builtin-api/set#%E5%80%A4%E3%81%8C%E6%9C%89%E7%84%A1%E3%82%92%E7%A2%BA%E8%AA%8D%E3%81%99%E3%82%8B---setprototypehas

> 値が有無を確認する - Set.prototype.has()

値「の」有無を確認する　の誤植だと思われます。

**Comment by suin** [comment]
ご報告・PRありがとうございました！マージさせていただきました。
