### ISSUE TITLE
型名称の表記揺れを統一したい

### ISSUE THREAD

**Issue by jamashita** [yytypescript/book#704]
型の名称をこのように筆記するパターンがあり、統一されていないので統一したいです。

- string型 (ふつう)
- `string`型 (名称部分をコードに)
- 文字列型 (日本語化)

日本語化した型名称は少ない印象がありますがその他ふたつはぼちぼち散見。どちらかといえばふつうのほうが多いか 🤔

**Comment by suin** [comment]
stringに限らず、null型、undefined型、論理型、数値型、bigint型、シンボル型も統一したいですね。

**Comment by suin** [comment]
読者はMDNやJS Primerを併読することが多そうなので、これら先行文献と同じ表現だと学習が進みそうです。

MDN

![CleanShot 2023-05-05 at 20 08 35 png](https://user-images.githubusercontent.com/855338/236442984-69cfe6ec-748b-4ba3-871d-95ea574a0bd3.png)

https://developer.mozilla.org/ja/docs/Web/JavaScript/Data_structures

JavaScript Primer

![CleanShot 2023-05-05 at 20 12 15 png](https://user-images.githubusercontent.com/855338/236443149-57326088-675b-4e3f-8785-12c01a9b1a76.png)

**Comment by jamashita** [comment]
なるほど！そのようにいたします！
筆記を統一できるようにもりもり変更してみます！

**Comment by suin** [comment]
| English           | MDN訳            | JS Primer訳                                             | ベリー本訳  |
|-------------------|-----------------|--------------------------------------------------------|------------|
| boolean           | 論理型	        | 真偽値                                       | 真偽値      |
| number            | 数値型	        | 数値                                         | 数値        |
| bigint            | 長整数型	        | 巨大な整数                                   | BigInt      |
| string            | 文字列型	        | 文字列                                       | 文字列型     |
| undefined         | Undefined 型	  | undefined                                               | undefined   |
| null              | Null 型	        | null                                                    | null        |
| symbol            | シンボル型	     | シンボル                                     | シンボル     |

stringは文字列型で良さそうですが、booleanやbigintなど一貫してない型もありますね。。このへんはどうしますかね😕💭

**Comment by suin** [comment]
あ、ベリー本は、値については、文字列、数値と表現して、型についてはstring型、number型と表現しているっぽい

**Comment by suin** [comment]
サンプルコードに付随しているコメントや解説で、言及するコードに`string`という型注釈が書かれている場合は、「文字列型」と言うより、「string型」と言ったほうが、わかりやすさはありますね。

![CleanShot 2023-05-05 at 20 27 23 png](https://user-images.githubusercontent.com/855338/236446182-b4031c9f-2b8b-42c4-adc4-76201a968d2f.png)

もしかして、変に統一するより文脈にまかせて使い分けたほうが良いのかも(？)

**Comment by jamashita** [comment]
今textlint作っていて思ったのですがvoid型なんていう型やstring | number型なんていう型もあったりして日本語表記よりもアルファベットを維持したほうがわかりやすいかもですね 🧐

**Comment by jamashita** [comment]
いちエンジニアとしては

- 表現がいくらかあるのは知りたい
- でも読み替えが発生しないように文章中はできるだけ統一しておいてほしい
- 翻訳するコストがすくないほうがいいのでコードと同じ名称が使えるならそれがいい

ですかね。なので string型、number型、boolean型を推します・・・
`string`型、とcodeにする必要があるかといえば、全撤廃でいい気がしています。

**Comment by jamashita** [comment]
textlint (yaml) 内部で ``` を認識させる方法に苦しむ

**Comment by suin** [comment]
## string型 vs `string`型

これはstring型でいい気がします。

## string | number型 vs `string | number`型

これはさすがに`string | number`型ですかね…。アクセシビリティを考えるとパイプが入った時点でTypeScriptコードなので、`<code>`で囲ってあげたほうがいいかと思いました。

## あえて統一するとしたらstring型

文字列型とstring型の共存が不可という場合は、string型への統一が良さそうです。

**Comment by suin** [comment]
## void型 vs `void型`

string型と同じく「void型」。any型、unknown型も同じ。

## boolean型 vs 論理型

boolean型に統一。ただし、boolean型のページでは、初出「boolean型(論理型)」のように考えられる和訳を併記する。
