### ISSUE TITLE
JavaScriptの学習に役立つ情報源も紹介する

### ISSUE THREAD

**Issue by yo-goto** [yytypescript/book#705]
以下のような理由で「[TypeScriptの学習リソース](https://typescriptbook.jp/learning-resources)」の紹介ページにおいてJavaScriptの学習リソースについても紹介したいと思います。

- TypeScriptの学習においてJavaScriptの学習も並行する必要があるから。
- JavaScriptを学習しようとする時に結局は必要な学習リソースを探すことになるので回り道しないようにオススメのリソースを提供したい。

紹介するリソースはTypeScriptの学習リソースの方を尊重してなるべく少数にとどめたいです。今のところこの２つについて書こうと思いますが、他にこれも入れたほうがよいというものがあれば教えてください。

- [JavaScript Primer](https://jsprimer.net)
- [MDN Web Docs](https://developer.mozilla.org/ja/docs/Web/JavaScript)

ref #542

**Comment by suin** [comment]
良さそうです！

**Comment by suin** [comment]
@yo-goto さん着手中
