### ISSUE TITLE
誤植「.module`s`.css」->「.module.css」

### ISSUE THREAD

**Issue by bamps53** [yytypescript/book#707]
https://typescriptbook.jp/tutorials/nextjs

> このスタイルをIndexPageコンポーネントに当てます。まず、index.modules.cssをインポートします。.modules.cssで終わるファイルはCSSモジュール(CSS Modules)と言うもので、CSSファイル内で定義したクラス名をTypeScriptからオブジェクトとして参照できるようになります。

この文中の二つの「.modules.css」は「.module.css」が正しいでしょうか？

**Comment by suin** [comment]
ご報告ありがとうございます！sがないほうのmodule.cssのほうが正しいです😊
