### ISSUE TITLE
誤植 catImageUrl -> imageUrl

### ISSUE THREAD

**Issue by bamps53** [yytypescript/book#708]
https://typescriptbook.jp/tutorials/vercel-deploy

[前のページ](https://typescriptbook.jp/tutorials/nextjs)までは`imageUrl`だったのが、このページでは`catImageUrl`になっているため、この部分だけ変更するとエラーが生じます。

**Comment by suin** [comment]
ご報告ありがとうございます！前のページの[Next.jsで猫画像ジェネレーターを作ろう](https://typescriptbook.jp/tutorials/nextjs)の内容が大きく変わってしまったため、[Vercelにデプロイしてみよう](https://typescriptbook.jp/tutorials/vercel-deploy)の内容との整合性が失われていました。[Vercelにデプロイしてみよう](https://typescriptbook.jp/tutorials/vercel-deploy)を全体的に見直して修正することとします。そのため、このissueはcloseさせて頂きます。

**Comment by suin** [comment]
- #710
