### ISSUE TITLE
「明確な割り当てアサーション」の「より安全なコードを書くには」の項のサンプルコードで非nullアサーションを使わないようにする

### ISSUE THREAD

**Issue by haruguchi-yuma** [yytypescript/book#718]
https://typescriptbook.jp/reference/values-types-variables/definite-assignment-assertion#%E3%82%88%E3%82%8A%E5%AE%89%E5%85%A8%E3%81%AA%E3%82%B3%E3%83%BC%E3%83%89%E3%82%92%E6%9B%B8%E3%81%8F%E3%81%AB%E3%81%AF

「明確な割り当てアサーション」の「より安全なコードを書くには」の項では**明確な割り当てアサーション**や**非nullアサーション**はできるだけ使わないようにしましょうとのことですが、その解決策として提示されているコードに非nullアサーションが使われてしまっているように思います。(おそらくtypo?)

```typescript
let num: number;
num = initNum();
console.log(num! * 2);　// ←この部分
function initNum() {
  return 2;
}
```

**Comment by suin** [comment]
誤植と思われます！ご報告ありがとうございます
