### ISSUE TITLE
「TypeScriptの射程」のサーバーレスの実例にAzure Functionsも追加する

### ISSUE THREAD

**Issue by Kiroru-Kojima** [yytypescript/book#726]
TypeScript初学者です。
[サーバーレス](https://typescriptbook.jp/overview/range-of-typescript#%E3%82%B5%E3%83%BC%E3%83%90%E3%83%BC%E3%83%AC%E3%82%B9-faas) のセクションにおいてAzure Functionsが挙げられていないのは何か理由があるんでしょうか？
TypeScriptと同じくMicrosoft社が提供するサービスなので、ここで挙げられていないのは気になりました。

関連ページ: https://typescriptbook.jp/overview/range-of-typescript

**Comment by suin** [comment]
理由はなく、単純に漏れですね。Azure Functionsも挙げておきたいと思います！
