### ISSUE TITLE
GitHub Actionsで yarn build するワークフローを追加してCIで検出できるようにする

### ISSUE THREAD

**Issue by suin** [yytypescript/book#727]
Vercelのビルド画面がsuinしか見れないために起こるこういうやりとりを無くしたい:

![CleanShot 2023-06-16 at 20 47 14 png](https://github.com/yytypescript/book/assets/855338/5ab9bb33-c160-4f63-a9f6-5bef78e812eb)

類似の事例

- #690

**Comment by suin** [comment]
yarn buildよりvercel deployのほうがいいかもしれない(要調査):

https://vercel.com/guides/how-can-i-use-github-actions-with-vercel

**Comment by t-yng** [comment]
こちら、ローカル環境だと普通にビルドが成功してしまったので、やはりデプロイ環境に近い環境でのビルド環境はあった方が良さそうでした。😺
