### ISSUE TITLE
Node.js 18へのアップデートを試みる

### ISSUE THREAD

**Issue by suin** [yytypescript/book#729]
- VercelのNode 16のサポートが終了している
- ~~yngさんのPRのビルドがVercelでコケ続けている~~

**Comment by t-yng** [comment]
> yngさんのPRのビルドがVercelでコケ続けている

自分の問題は単純にtwoslashによるエラーのようでした。🙏🏻
Markdownファイルを修正したらビルドエラー解消しました。

https://github.com/yytypescript/book/pull/722

**Comment by suin** [comment]
twoslashのエラーの件、Node.jsではなくyarnで入るtypescriptのバージョンが起因してそうでした。
