### ISSUE TITLE
ChatGPTを用いてTypeScriptの質問ができるチャットボットを作りませんか？

### ISSUE THREAD

**Issue by suin** [yytypescript/book#732]
どうやってGPTにサバイバルTypeScriptのコンテンツを参照させたらいいか？

GPT搭載のチャットボットSaaSでも可

**Comment by suin** [comment]
## 着手可になるまでに必要なこと

- 調査: コンテンツを学習または参照させる技術的な手法

**Comment by t-yng** [comment]
試しに調査してプロトタイプ作ってみます。🙌🏻

**Comment by hayashi-ay** [comment]
MDNのAI Help機能の仕組みが参考になりそう。
すべての記事に対して生成したembeddingsをSupabaseでホストしているPostgreSQLに格納していて、質問に関連した記事を取得してくる。その次に、OpenAIのAPIを叩いて最終的な回答を取得する。

https://developer.mozilla.org/en-US/blog/introducing-ai-help/#under_the_hood

**Comment by hayashi-ay** [comment]
一方でコンテンツの出し方およびクオリティに問題があるとAI Explain機能みたいにぷち炎上しそう。

https://developer.mozilla.org/en-US/blog/ai-explain-postmortem/

**Comment by suin** [comment]
参考情報ありがとうございます！読んでみます！

**Comment by t-yng** [comment]
試しにサンプルコードを使って「読んで学ぶTypeScript > 文」の記事を対象にBOTを構築してみました。

質問:
```
unkown型とany型の違いを教えてください。
```

回答:
```
unknown型とany型の違いは、以下の点です。

1. 代入の制約: any型はどのような型の変数にも代入できますが、unknown型の値は具体的な型への代入ができません。具体的な型が不明な場合に使用されます。

2. 型安全性: unknown型は型安全なany型とも言われます。unknown型の値は、具体的な型が不明なため、そのままではプロパティへのアクセスやメソッドの呼び出しができません。一方、any型は型安全性が低く、どのような操作でも許可されます。

3. プロパティへのアクセスとメソッドの呼び出し: unknown型の値は、プロパティへのアクセスやメソッドの呼び出しも許されません。一方、any型ではこれらの操作が許可されます。

unknown型は、具体的な型が不明な場合に使用され、型安全性を保つための制約があります。一方、any型は型安全性が低く、どのような操作でも許可されるため、注意が必要です。
```

**Comment by suin** [comment]
TypeScriptコアチームからこんなのも出てる！

https://microsoft.github.io/TypeChat/

**Comment by t-yng** [comment]
こちら、GPTsを使って改めて色々と実験しています。🤖

それっぽい回答は得られているのですが、参考情報のURLを提供させるといくつか課題がある状態です。

## 現状の課題
- 与えた情報に存在しないURLを推測して生成しまうことがある
- 生成されたリンクをクリックできない
  - Makrdown形式を使用しないことで、URL分からなくなる問題は回避できそうです
  - コミュニティでも [Custom GPT Bug - Hyperlinks not clickable](https://community.openai.com/t/custom-gpt-bug-hyperlinks-not-clickable/565499) で解決してない問題として話されています。

## プロンプト
```
あなたはTypeScriptに関する質問を回答するエージェントです。

質問者のTypeScriptに関する質問に対して、docs.csvに含まれるデータに基づいて回答をしてください。

また、回答の最後にdocs.csvに含まれるデータに基づいて、質問に関連するページURLとタイトルを追記してください。URLは絶対に推測しないでください。

## URL表示について
・URLはMakrdown形式を使用せずに、タイトルとハイパーリンクを直接表示してください。

## docs.csvについて
docs.csvはサバイバルTypeScriptと呼ばれるOSSのドキュメントの情報をページごとにまとめたCSVファイルです。
・url: ページのURL
・title: ページのタイトル
・content: ページの本文
```

## 実行結果
![image](https://github.com/yytypescript/book/assets/11068883/1874c735-4ec8-479c-af46-36b9314faaa0)

**Comment by t-yng** [comment]
GPTs作ってみました。🤖

↓限定リンク
https://chat.openai.com/g/g-EzVTRSzR7-sabaibarutypescript

![image](https://github.com/yytypescript/book/assets/11068883/f5242eb0-729f-49a8-ba3b-b2a9842b17a2)

**Comment by t-yng** [comment]
GPTsとして公開されたので、このISSUEはクローズにします。🙌🏻
https://chat.openai.com/g/g-EzVTRSzR7-sabaibarutypescript
![image](https://github.com/yytypescript/book/assets/11068883/7d3d62c3-1b65-4815-8298-8a521556f934)

**Comment by suin** [comment]
すごい！
![image](https://github.com/yytypescript/book/assets/855338/4cbca413-4fca-4a29-9dfa-d6ea86de0f2b)

**Comment by hayashi-ay** [comment]
ChatGPT Plusでないと使えないんですね 😢 

<img width="1052" alt="image" src="https://github.com/yytypescript/book/assets/39038230/fcd19a52-490d-4cef-aff1-9c66d382fc98">

**Comment by suin** [comment]
URLがハルシネーション起こしてしまう問題に気づきました。致し方ないかもですが🥹

![CleanShot 2024-03-08 at 20 34 59 png](https://github.com/yytypescript/book/assets/855338/4fd1a8c9-a230-42c0-9880-0621ce89917a)
![CleanShot 2024-03-08 at 20 36 15 png](https://github.com/yytypescript/book/assets/855338/25522ade-7c5a-4f9f-b6ee-5568ca1d4fa3)

**Comment by t-yng** [comment]
@hayashi-ay 
そうなんですよね。。。😭

現状、GPTsが有料プラン限定なので、全員に広く使ってもらおうとすると自前でインターフェース用意してAPI経由で機能を提供する必要がありますね

**Comment by suin** [comment]
一旦公開して、次のステップでAPI経由にしても良さそうですね

**Comment by t-yng** [comment]
URLのハルシネーション問題は、厳密に文脈データに基づいて回答するようにプロンプトを調整したら、発生確率は減らせるのですが、その分関連情報を見つけれないと言われる可能性が高くなってしまうので、精度のトレードオフはありました🙋🏻‍♂️

プロンプト改善は別途ISSUEとして改善していきたいですね❤️

プロンプトの例
```
質問者のTypeScriptに関する質問に対して、docs.jsonに含まれるデータに基づいて回答をしてください。

また、質問に関連するページの情報のurlとtitleを、docs.jsonに基づいて追記してください。urlはdocs.jsonに含まれるものだけを使用してください。
```

![image](https://github.com/yytypescript/book/assets/11068883/fe075228-cd54-4c2a-9005-f05c308e7ffd)
