### ISSUE TITLE
faviconがDocusaurusのデフォルトに戻っているのを直す

### ISSUE THREAD

**Issue by tats-u** [yytypescript/book#737]
以前のfaviconは青地白抜きの「TS入門」だった記憶ですが、Docusaurusのデフォルトのもの（恐竜の[Slashくん](https://v1.docusaurus.io/en/about-slash)）になっています。

**Comment by suin** [comment]
ご報告ありがとうございます！
先日のDocusaurusのアップグレードでリグレッションが発生したようです😢
