### ISSUE TITLE
拒否されたPromiseをawaitしたときと拒否されたPromiseをcatchするの違いを明確にする

### ISSUE THREAD

**Issue by jamashita** [yytypescript/book#743]
ref #700 
わかりやすくかきたい！

**Comment by t-yng** [comment]
ここら辺はPromiseを題材にしているだけで、例外処理と同じ話なのかなとちょっと思いました。
Promiseを使わない場合でも関数の中で別関数を呼び出しているときに例外処理を書かないと呼び出し側に例外が投げられてしまうので、そうしたくない場合は例外を捕捉しましょう。という事だと思っております。

なので、それを踏まえてPromiseの場合も同じだよという説明をしてあげると、イメージがしやすいかもです？

**Comment by suin** [comment]
それ、良さそうですね！

**Comment by jamashita** [comment]
#700 で説明するときに使ったサンプル

https://github.com/yytypescript/book/issues/700#issuecomment-1635716069

**Comment by jamashita** [comment]
finallyを含めた場合も書いておきたい
