### ISSUE TITLE
誤植「早期リ`ータ`ン」→「早期リ`ター`ン」

### ISSUE THREAD

**Issue by shuhei23** [yytypescript/book#746]
https://github.com/yytypescript/book/blob/a24083f8938cf82d88d50c62b7d61c2b18a3af1d/docs/reference/statements/control-flow-analysis-and-type-guard.md?plain=1#L60

素晴らしい本ありがとうございます。
上記の箇所で誤植があったため報告します。

誤：これは制御フロー分析により`month`変数が`string`型の場合は早期**リータン**により関数が終了し
正：これは制御フロー分析により`month`変数が`string`型の場合は早期**リターン**により関数が終了し

**Comment by suin** [comment]
ご報告ありがとうございます！
