### ISSUE TITLE
Prettier の実行結果が異る

### ISSUE THREAD

**Issue by nsgc** [yytypescript/book#761]
ページ: https://github.com/yytypescript/book/edit/master/docs/tutorials/prettier.md
[prettier#設定ファイルを作成する](https://typescriptbook.jp/tutorials/prettier#%E8%A8%AD%E5%AE%9A%E3%83%95%E3%82%A1%E3%82%A4%E3%83%AB%E3%82%92%E4%BD%9C%E6%88%90%E3%81%99%E3%82%8B)

https://github.com/yytypescript/book/blob/b4185d707daa2bd6d7300112a039479b58dec888/docs/tutorials/prettier.md?plain=1#L227-L231

直前の設定で `"singleQuote": true` にして実行しているので、

```ts
const hello = (name: string) => {
  console.log('Hello,World ' + name);
};
```

とシングルクォートで囲まれると思います。

**Comment by jamashita** [comment]
@nsgc ご報告いただきありがとうございます！
こちらご指摘の通りでございます！反映いたしますね！ 🙇

**Comment by jamashita** [comment]
こちら反映いたしました。
https://github.com/yytypescript/book/pull/768
