### ISSUE TITLE
誤字修正提案

### ISSUE THREAD

**Issue by ryoichi-obara** [yytypescript/book#765]
「てにをは」が変なので修正しませんか。

> JavaScriptのモジュールでは、デフォルトで変数や関数などを非公開になるわけです。

↓

> JavaScriptのモジュールでは、デフォルトで変数や関数などは非公開になるわけです。

**Comment by jamashita** [comment]
@ryoichi-obara たしかに助詞が変ですね。ご迷惑をおかけします！
ご意見ちょうだいします！ありがとうございます！ 🙇

**Comment by jamashita** [comment]
こちら反映いたしました。
https://github.com/yytypescript/book/pull/769
ありがとうございました
