### ISSUE TITLE
issueテンプレートを作って、コントリビューターの意志を確認できるようにする

### ISSUE THREAD

**Issue by suin** [yytypescript/book#771]
[チケット駆動(プルリクする前に話し合おう) | TypeScript入門『サバイバルTypeScript』](https://typescriptbook.jp/writing/ticket-driven)では、次のように書いてありますが、担当したいかどうかの意志を漏れなく確認したいので、issueテンプレートにしましょう。

![CleanShot 2023-09-08 at 20 59 18 png](https://github.com/yytypescript/book/assets/855338/98eb9a4f-cef3-497a-855c-464cd1f10eef)

**Comment by hayashi-ay** [comment]
+1
