### ISSUE TITLE
「コンパイル」は「トランスパイル」と言い換えて行くべきか？

### ISSUE THREAD

**Issue by katayamahide** [yytypescript/book#794]
### 何をどうしたいか？
以下リンクの記事の見出し「Google Apps Script」内の文章の誤植を修正したいです。
[TypeScriptの射程 | TypeScript入門『サバイバルTypeScript』](https://typescriptbook.jp/overview/range-of-typescript#google-apps-script)

> TypeScriptで書いたコードもJavaScriptにコンパイルすることで、ブラウザ拡張として動かせます。
↓
TypeScriptで書いたコードもJavaScriptにトランスパイルすることで、ブラウザ拡張として動かせます。

### やるとなったら自分が担当したいか？ (自分がその変更のプルリクエストを作りたい場合)
どちらでも可です。

**Comment by suin** [comment]
トランスパイルもコンパイルの一種なので誤植ではないという見解ですがいかがでしょうか？😌

**Comment by katayamahide** [comment]
コメントありがとうございます。
そうですね。コンパイルは高→低水準、トランスパイルは同水準の言語変換と考えていましたが、おっしゃる通りなのでcloseしていただけますと幸いです。
