### ISSUE TITLE
誤植「create-react-appでは」→「yarn create react-appでは」

### ISSUE THREAD

**Issue by katayamahide** [yytypescript/book#795]
### 何をどうしたいか？
以下リンクの記事の見出し「プロジェクトを作る」内の文章の誤植を修正したいです。
[Reactでいいねボタンを作ろう | TypeScript入門『サバイバルTypeScript』](https://typescriptbook.jp/tutorials/react-like-button-tutorial#%E3%83%97%E3%83%AD%E3%82%B8%E3%82%A7%E3%82%AF%E3%83%88%E3%82%92%E4%BD%9C%E3%82%8B)

> create-react-appではReactのインストールも自動で行われます。インストールされたReactのバージョンを確認するには次のコマンドを用います。
↓
`yarn create react-app`ではReactのインストールも自動で行われます。インストールされたReactのバージョンを確認するには次のコマンドを用います。

### やるとなったら自分が担当したいか？ (自分がその変更のプルリクエストを作りたい場合)
はい。

**Comment by suin** [comment]
@katayamahide ご報告&PRありがとうございました！
