### ISSUE TITLE
ESLintの「JetBrains IDEとESLintを統合しよう」にJetBrains IDEを知らない人が混乱しないようにする

### ISSUE THREAD

**Issue by takaraOta** [yytypescript/book#796]
JetBrains IDEとESLintを統合しよう
のところでAutomatic ESLint configurationの項目を探してみたのですが見つかりません。
ESLintのメニューを開いても似たような画面が表示されないので
たぶん自分のやり方が間違っていると思うのですがどのようにすればいいですか？
↓このような画面になります。
https://gyazo.com/80b41d78c02b1b5a24c83c49502f8a8e

関連ページ: https://github.com/yytypescript/book/edit/master/docs/tutorials/eslint.md

**Comment by takaraOta** [comment]
すみません、自分が勘違いしてました🙇‍♂
JetBrains IDEとかWebStormというのがよく分からず、
記事の通りに進めたらそれができるようになるのかと思ってました。
そうではなくて、事前にWebStormなどのJetBrains IDEを導入しているという
前提のもと書かれている記事だったみたいですね。
通りで表示されないわけです、存在しないのですから！笑
お手数おかけしてすみませんでした。

**Comment by suin** [comment]
いえいえ、むしろWebStormを知っていることが前提になっている構成にも問題があるので、課題に気づけてありがたいです！

**Comment by suin** [comment]
## 課題

- ESLintの記事は基本的に上から進めていけばいい流れになっている
- ところが、IDEとの統合の部分は、使っているIDEに応じて分岐する
- これにより、WebStormを知らないVS Codeユーザーが混乱する場合がある

## 改善方法

- VS CodeとJetBrains IDEにリンクを貼る: リンク先: https://typescriptbook.jp/tutorials/setup#%E3%82%A8%E3%83%87%E3%82%A3%E3%82%BF%E3%83%BCide
- 「VS Codeをお使いの方はこの手順を実施してください」「JetBrains IDEをお使いの方はこの手順を実施してください」などとひとこと添える
