### ISSUE TITLE
titleタグと見出しにファイル名が出てしまっている

### ISSUE THREAD

**Issue by suin** [yytypescript/book#798]
1行目が見出しじゃないとtitleタグと見出しにファイル名が出てしまうようです。

```
<!-- textlint-disable prh -->

# boolean型 (論理型)

<!-- textlint-enable prh -->
```

![CleanShot 2023-12-01 at 21 00 16 png](https://github.com/yytypescript/book/assets/855338/09427bdd-2b16-4e5b-b149-4e27f752103c)

**Comment by suin** [comment]
textlintはずしても問題なければはずしたい。

問題ある場合は、front matterのtitleを設定する？

**Comment by jamashita** [comment]
問題が発生しているページのタイトル

- bigint型
- boolean型
- string型
- symbol型
- number型
