### ISSUE TITLE
ソースコード内にライセンスについての記載を追加しませんか？

### ISSUE THREAD

**Issue by ueferi** [yytypescript/book#801]
## 何をどうしたいか

- README.mdにCC BY-SA 4.0とMIT Licenseで公開している旨を追記します。
- LICENSESディレクトリを作成し、そこにCC BY-SA 4.0とMIT Licenseの詳細を記載したテキストファイルを格納します。
参考: 本書と同様に複数のライセンスで公開しているRustのリポジトリ 
https://github.com/rust-lang/rust/tree/master/LICENSES

```
(例)

└── LICENSES
    ├── CC BY-SA 4.0
    └── MIT License
```

## そうしたい理由は何か

ドキュメントのライセンスページを見に行かないと、どのライセンスが適用されているか分からないためです。

## やるとなったら自分が担当したいか？ 

ぜひPRを立てたいと思います。

**Comment by suin** [comment]
ご提案&調査ありがとうございます！

GitHubにも本プロジェクトのライセンスを認識してもらえると、サイドバーにライセンスが表示されるため、より目的を達成しやすいと思うのですがいかがでしょうか。

LICENSESディレクトリではGitHubに認識してもらえないようです。RustではプロジェクトルートにLICENSE-MITファイルを配置しているようで、これによりマルチライセンスとGitHubに認識され、サイドバーに表示されているようです。

![CleanShot 2023-12-15 at 20 34 08 png](https://github.com/yytypescript/book/assets/855338/989bc202-65ab-41b0-a35d-424da1c0e086)

**Comment by ueferi** [comment]
ご返信ありがとうございます。

>GitHubにも本プロジェクトのライセンスを認識してもらえると、サイドバーにライセンスが表示されるため、より目的を達成しやすいと思うのですがいかがでしょうか。

ご提案頂いた通り、GitHubのリポジトリにライセンスを認識してもらう方向でいきたいと思います。
> LICENSESディレクトリではGitHubに認識してもらえないようです。RustではプロジェクトルートにLICENSE-MITファイルを配置しているようで、これによりマルチライセンスとGitHubに認識され、サイドバーに表示されているようです。

確認不足でお手数お掛けして申し訳ありません。ご指摘頂いた内容を当方で確認いたしました。

<img width="1259" alt="スクリーンショット_2023-12-19_0_37_55" src="https://github.com/yytypescript/book/assets/58869038/d7109259-60a5-41ee-a037-f11d06419fd1">

プロジェクトルートにLICENSEファイルを配置したところ、確かにGitHubがライセンスを認識してくれました。

参考記事:
- [リポジトリへのライセンスの追加](https://docs.github.com/ja/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository)
- [GitHub リポジトリに CC Licenses を設定したい](https://zenn.dev/spiegel/articles/20200919-ccl)
