### ISSUE TITLE
number型の記事に「README」が残っている

### ISSUE THREAD

**Issue by ch1hh1** [yytypescript/book#802]
https://github.com/yytypescript/book/edit/master/docs/reference/values-types-variables/number/README.md

こちらのnumber型のページに「README」残っているのは誤植・変更漏れでしょうか？
![スクリーンショット 2023-12-10 12 57 24](https://github.com/yytypescript/book/assets/126086206/12039a13-b8c6-4448-aea1-d4581a1db091)

**Comment by suin** [comment]
ご報告ありがとうございます！これは誤植ですね

**Comment by suin** [comment]
Note: docusaurusの設定に関する部分のようなので、単純にMarkdownを直せばいいものではなさそう

**Comment by suin** [comment]
次と重複しているようでしたので一旦Closeします。

- #798
