### ISSUE TITLE
TSConfigのページにオプションの一覧を用意する

### ISSUE THREAD

**Issue by t-yng** [yytypescript/book#803]
## 課題
TSConfigのページでオプションの詳細が記述されており非常に便利で助かるなーと思っております。
ただ、どのオプションについて記述があるかパッとで分かりづらい状態が分かりづらいなと思いました。

## 何をやるか？
- オプションの一覧をリンク集として作成する。
- 作成してないオプションのページについてはPR募集中である旨を記載する

## 期待する結果
- TSConfigのオプション一覧を把握しやすくする。
- オプションの説明ページのPRを作成してもらいやすくする。

**Comment by suin** [comment]
いいと思います！
