### ISSUE TITLE
型理論的な話題での型の説明(型のメンタルモデル)のアイデア

### ISSUE THREAD

**Issue by yo-goto** [yytypescript/book#804]
## 前提

静的型付け言語 (あるいは構造的部分型の型システム) にあまり詳しくない人が「TypeScript における型とはなにか」を集合論などを使った意味論で直感的に型について理解できるメンタルモデルを作ることができるような説明が追加できると良さそう。

また、本格的な型理論の話題には踏み入らずに、公式ドキュメントには載っていないがちょっと知っているだけでも直感的に理解できるような型理論の話を盛り込むと比較的手間をかけずに恩恵を受けられそう。例: Top 型と Bottom 型、Unit 型の話題など

## アイデア

- [x] unkown(top) 型と never(bottom) 型が全体集合と空集合に対応するという考え方
- [x] any(dynamic) 型の部分型関係での位置 (unknown と同じ top 位置)
- [x] null, undefined などの値を一つしか持たない Unit 型の話
- [ ] 部分型関係の推移律 (関係性が伝播できるという性質) と反射律
- [x] 型の絞り込み (narrowing) は集合を小さくしていくという考え方

集合論的な見方の話をするなら、以下の公式ドキュメントの『[Types as Sets](https://www.typescriptlang.org/docs/handbook/typescript-in-5-minutes-oop.html#types-as-sets)』から拝借して「型 = a set of values」の概念で説明できる。

> In TypeScript, it’s better to think of a type as a set of values that share something in common. Because types are just sets, a particular value can belong to many sets at the same time.

**Comment by suin** [comment]
よさそう！
