### ISSUE TITLE
構造的部分型の説明をより初心者にわかりやすくしたい

### ISSUE THREAD

**Issue by suin** [yytypescript/book#821]
ピンとこなかったというフィードバックがあったため

https://x.com/inobou25/status/1745078817838821641?s=46&t=IpZybZq5__EiCip46Tb3Kg

**Comment by yo-goto** [comment]
公称型(nominal typing)に加えて、名前的部分型(nominal subtyping)という概念名を加えて、構造的に対する比較の概念として分かりやすくするなどがあったほうがいいかなと思います。

https://en.wikipedia.org/wiki/Nominal_type_system

例えば、名前的部分型においては宣言された型の名前が重要であり、新しい型を部分型として導入するには明示的に型を継承するように宣言して名前付けするなどの、構造的(structural)であることに対して名前的(nominal)であることの特徴を分かりやすく説明するなどがあると、そもそも公称型の概念に詳しくない人にとっても二つの概念の対立が分かりやすくなると思います!

**Comment by suin** [comment]
- 読者はどんな人をイメージするか？
    - JavaやPHPなどの他の言語のほうが詳しい
    - そもそも自分が使っている言語が公称型だという認識がない
- 想定される疑問
    - 構造的部分型の特徴は何？
    - なぜTSは構造的部分型なのか？
    - 構造的部分型の利点
    - 構造的部分型の注意点はある？

**Comment by suin** [comment]
いきなり構造的部分型ではなく、構造的型付け(structral typing)と名前的片付け(nominal typing)から入るほうがいい気がしてきました。

そのうえで、構造的部分型(structural subtyping)と名前的部分型(nominal subtyping)の話に発展する。

**Comment by suin** [comment]
> なぜTSは構造的型付けなのか？
JavaScriptの拡張言語として作られたことに密接に関係している。オブジェクトリテラルは匿名の型になるし、JavaScriptはダックタッピングの文化なので、これらと相性がいい型システムが構造的型付けだった。
