### ISSUE TITLE
bigintはJSON.serializeするとTypeErrorが起こることを追記したい

### ISSUE THREAD

**Issue by suin** [yytypescript/book#829]
## 何をどうしたいか？

bigintはJSON.serializeするとTypeErrorが起こることを追記したい

## そうしたい理由は何か？（誤植の修正など理由が自明な場合は不要）

実務でハマったから

## 着手可能になったら自分でプルリクエストを作成したいか？
他の人でも可

※ 着手可になってから、1ヶ月以上経過している場合は他の人が着手する可能性があります。

**Comment by hayashi-ay** [comment]
MDNのここらへんが参考になりますね。単にリンク貼るだけでも良いかも。

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt#use_within_json
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify#description

**Comment by jamashita** [comment]
似たような事象を #892 起票
