### ISSUE TITLE
リポジトリのNode.jsのバージョンをv20にアップデート

### ISSUE THREAD

**Issue by t-yng** [yytypescript/book#830]
## 何をどうしたいか？
リポジトリのNode.jsのバージョンをv20にアップデートする

## そうしたい理由は何か？（誤植の修正など理由が自明な場合は不要）
VercelがNode.js環境でv20のサポートが開始されているんので、メンテナンスのためにアップデートをしておきたい。

## 着手可能になったら自分でプルリクエストを作成したいか？
他の人でも可

※ 着手可になってから、1ヶ月以上経過している場合は他の人が着手する可能性があります。

**Comment by suin** [comment]
よさそうです。
