### ISSUE TITLE
誤植「Foodクラスに抽象クラスに変更し」→「Foodクラスを抽象クラスに変更し」

### ISSUE THREAD

**Issue by hoshico** [yytypescript/book#832]
## 何をどうしたいか？

助詞の「に」を「を」に変更した方がいいのではと思いました。

- ページ内本文7行目(※ abstract-class.md l11)
https://typescriptbook.jp/reference/object-oriented/class/abstract-class

## そうしたい理由は何か？（誤植の修正など理由が自明な場合は不要）

該当ページを読んでいて気になりました。
ただ、個人的な感想ですのでもしこれが自然であるなら修正はなくてもいいかなとも思います。

## 着手可能になったら自分でプルリクエストを作成したいか？
自分で作成したい

※ 着手可になってから、1ヶ月以上経過している場合は他の人が着手する可能性があります。

**Comment by suin** [comment]
ご報告ありがとうございます。PRお待ちします😌

**Comment by suin** [comment]
PRありがとうございました！マージいたしました。
