### ISSUE TITLE
ライセンスページのリンクに関するタイポ

### ISSUE THREAD

**Issue by t-hamano** [yytypescript/book#838]
## 何をどうしたいか？

本書のライセンスページにおいて、「リンクは`rel="nofollowed"`にしてはいけません。」という一文がありますが、 `nofollow` のタイポだと思われます。

[HTML 属性: rel - HTML: ハイパーテキストマークアップ言語 | MDN](https://developer.mozilla.org/ja/docs/Web/HTML/Attributes/rel)

## 着手可能になったら自分でプルリクエストを作成したいか？

はい

※ 着手可になってから、1ヶ月以上経過している場合は他の人が着手する可能性があります。

**Comment by suin** [comment]
ありがとうございます！
