### ISSUE TITLE
GPTsへの導線を作りませんか？

### ISSUE THREAD

**Issue by suin** [yytypescript/book#844]
### 概要

サバイバルTypeScriptのウェブサイトに、読者がChatGPTを用いた質問支援システム（GPTs）に簡単にアクセスできるような導線を設ける提案です。これはIssue #732で議論された、サバイバルTypeScriptのコンテンツについて質問できる特別なChatGPT GPTsを読者に提供するためのものです。

### 背景

- Issue #732において、サバイバルTypeScriptの読者がコンテンツに関する質問をChatGPT GPTsを通じて行えるようなシステムが構築されました。
    - #732
- この新しいツールを読者に積極的に利用してもらうためには、サイト内での目立つ導線が必要です。

### 提案内容

- サバイバルTypeScriptのウェブサイトのヘッダー部分に、GPTsへのリンクを追加します。
- リンクには、認識しやすいアイコンを使用し、読者の注目を引きます。提案されたアイコンは、[Lucide](https://lucide.dev/icons/bot)の`bot`アイコンです。
- アイコンまたはリンクにマウスをホバーした際に、GPTsの簡単な説明がポップアップ表示されるようにすることで、読者がその機能を理解しやすくします。

### 導線のデザイン案

以下の図は、提案された導線をヘッダーにどのように配置するかの具体的なイメージです。

![Frame 2](https://github.com/yytypescript/book/assets/855338/7c231755-7649-46f2-9cf6-07101926c617)

### 実現のための次のステップ

1. **デザインの承認**：提案された導線のデザイン案についてチーム内で合意を得る。
2. **実装**：承認されたデザインに基づき、ウェブサイトのヘッダーに導線を追加する。
3. **テスト**：変更を適用した後、ウェブサイト上での表示と機能を確認し、問題がないかテストする。

### 提案の目的

この提案は、サバイバルTypeScriptの読者が新たに追加されたChatGPT GPTsをより気軽に利用し、サイトのコンテンツに関する疑問や質問を解決できるようにすることを目的としています。また、この導線の追加により、ウェブサイトの利便性とユーザーエクスペリエンスが向上することが期待されます。

### 着手の可否について

本提案の実装に関しては、プルリクエストを作成することにオープンで、誰がやってもいいです。

**Comment by suin** [comment]
GPT Plusが必要な旨はボタン押す前にわかったほうがいいかもしれません

**Comment by t-yng** [comment]
導線の遷移先です。
https://chat.openai.com/g/g-EzVTRSzR7-sabaibarutypescript

**Comment by t-yng** [comment]
docsaurasが内部で利用している[infimaのボタンデザイン](https://infima.dev/docs/components/button)に従うなら、ボタンの角の丸みは弱めた方が良さそうでした。

<img width="1440" alt="image" src="https://github.com/yytypescript/book/assets/11068883/05cee8ec-7779-4e2f-b150-a7aaf91053bd">

ただ、提案されている角丸デザインの方が見た目的にはスッキリしていて違和感が無い感じがしております。
<img width="1440" alt="image" src="https://github.com/yytypescript/book/assets/11068883/614d6190-7bc7-4a27-9202-66218f4477e9">

**Comment by t-yng** [comment]
説明はツールチップで出すとこんな感じになりますが、もう少しデザインした方がいいでしょうか？
<img width="377" alt="image" src="https://github.com/yytypescript/book/assets/11068883/4d620aa4-59d8-472a-a70d-a412b64ab0d6">

**Comment by t-yng** [comment]
## 決まったこと
- ボタンはinfimaのボタンデザインに合わせる
- レイアウトはdocusaurausのレイアウトに合わせる
- ツールチップの表示は一旦title属性で対応する
- モバイルでもデザイン崩れ起きないように調整
