### ISSUE TITLE
オプショナルチェーンの説明で「「オブジェクトのプロパティが存在しない」」→「オブジェクト自体が存在しない」

### ISSUE THREAD

**Issue by TamagawaJousui** [yytypescript/book#846]
https://github.com/yytypescript/book/edit/master/docs/reference/values-types-variables/object/optional-chaining.md

> JavaScriptのオプショナルチェーン?.は、オブジェクトのプロパティが存在しない場合でも、エラーを起こさずにプロパティを参照できる安全な方法です。

「オブジェクトのプロパティが存在しない」ではなく、「オブジェクト自体が存在しない(`null`や`undefined`となる)」だと思います。

**Comment by t-yng** [comment]
@TamagawaJousui 
提案ありがとうございます。

「オブジェクト自体が存在しない」という表現ですと、下記のようなコードをイメージするのかなと思ったのですが、合ってますかでしょうか？

```と
const animal = undefined

animal?.name
```

[MDN: オプショナルチェーン (?.)](https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Operators/Optional_chaining) でも次のような記載があるように、オプショナルチェーンはnullishなプロパティへの参照を安全に行う仕組みなのかなと思っていますので、自分は元の記載で違和感は無いように思いました🙏🏻

> 接続されたオブジェクトチェーンの深くに位置するプロパティの値を、チェーン内の各参照が正しいかどうかを明示的に確認せずに読み込むことを可能にします。

「オブジェクト自体が存在しない(nullやundefinedとなる)」の方が良い理由がありましたら、もう少し具体的に教えていだけると嬉しいです！

**Comment by t-yng** [comment]
次のようなコードの場合は、参照元のオブジェクトに対してオプショナルチェーンでチェックをしているので、こういった文脈では「オブジェクトが存在しない」という表現とも言えるかもですね！

```
type Animal = {
  name: string;
}

function showName(animal: Animal | undefined) {
  console.log(animal?.name);
}
```

**Comment by TamagawaJousui** [comment]
@t-yng 
ご返信ありがとうございます。

「オブジェクトのプロパティが存在しない」の場合は、エラーが出なくで、通常のプロパティアクセサーの様に、`undefined` が返します。


<img width="163" alt="image" src="https://github.com/yytypescript/book/assets/118496913/95720171-cbe7-4d06-b4ff-e1b42c6cef68">


「オブジェクト自体が存在しない」の場合、エラーが出ます。


<img width="510" alt="image" src="https://github.com/yytypescript/book/assets/118496913/24c3ff21-a707-4ed4-8b61-505e6f299563">


つまり、オプショナルチェーンの目的は、「nullishな**オブジェクト**のプロパティへの参照」を安全にする為だと思います。

MDNの原文では、

> オプショナルチェーン (optional chaining) 演算子 (?.) は、接続されたオブジェクトチェーンの深くに位置するプロパティの値を、**チェーン内の各参照**が正しいかどうかを明示的に確認せずに読み込むことを可能にします。

ここで、**チェーン内の各参照**というのは、最後のプロパティではなく、チェーンの途中の各オブジェクトだと思います。

**Comment by t-yng** [comment]
@TamagawaJousui 
ご説明ありがとうございます！

> 「オブジェクト自体が存在しない」の場合、エラーが出ます。
> つまり、オプショナルチェーンの目的は、「nullishな`オブジェクト`のプロパティへの参照」を安全にする為だと思います。

ここの説明を見ていて思ったのですが、 `オブジェクトのプロパティ` とだけ言っているので、今回の違和感が発生している気がしました。

オプショナルチェーンの評価対象はあくまで `変数` や `オブジェクトのプロパティ` になるのかなと思っており、「オブジェクト自体が存在しない」という表現だと「オブジェクト」評価対象との


`変数`や`オブジェクトのプロパティ`に値が代入されて評価されるので、「オブジェクト自体が存在しない(`null`や`undefined`となる)」というよりは「変数やオブジェクトのプロパティがnullやundefinedの場合でも...」という説明の方が @TamagawaJousui  さんのモヤッとも解消されて、スッキリするかもと思ったのですが、いかがでしょうか？👀

**Comment by t-yng** [comment]
@TamagawaJousui 
ご説明ありがとうございます！

> 「オブジェクト自体が存在しない」の場合、エラーが出ます。
> つまり、オプショナルチェーンの目的は、「nullishな`オブジェクト`のプロパティへの参照」を安全にする為だと思います。

ここの説明を見ていて思ったのですが、 `オブジェクトのプロパティ` とだけ言っているので、今回の違和感が発生している気がしました。

オプショナルチェーンの評価対象はあくまで `変数` や `オブジェクトのプロパティ` になるのかなと思っており、「オブジェクト自体が存在しない（`null`や`undefined`となる）」という表現だと「オブジェクト自体が`null`や`undefined`となる」という意味にも取れてしまい少し混乱を招きそうな感じがしました。
※ 実際にオブジェクトは代入された値なので、nullやundefinedになるのは**オブジェクトではなく**変数やオブジェクトのプロパティなのかなと思いました。

なので「オブジェクトのプロパティ」に限定せずに「存在しない」という言葉も使わずに「変数やオブジェクトのプロパティなどの参照がnullやundefinedの場合でも...」という説明だと @TamagawaJousui  さんのモヤッとも解消されて、スッキリするかもと思ったのですが、いかがでしょうか？

検討違いなこと言ってしまっていたら、ご指摘ください。🙇‍♂️

**Comment by TamagawaJousui** [comment]
@t-yng 
ご返信ありがとうございます。

ご提案は素晴らしいと思います。そして、「**~~変数~~**やオブジェクト**~~のプロパティなど~~**の参照がnullやundefinedの場合」の方がいかがでしょうか。前回述べた通り、変数若しくはプロパティ自体が `nullish` の場合は、エラーは起きないですから。

どうぞよろしくお願いします。

**Comment by t-yng** [comment]
@TamagawaJousui 
ありがとうございます！

> そして、「~~変数や~~オブジェクト~~のプロパティなど~~の参照がnullやundefinedの場合」の方がいかがでしょうか。前回述べた通り、変数若しくはプロパティ自体が nullish の場合は、エラーは起きないですから。

確かに訂正して頂いた↑の表現が一番しっくり来るかもですね！！

もし可能でしたら、修正のプルリク作成して頂けると嬉しいです😊

**Comment by TamagawaJousui** [comment]
@t-yng 
遅くなりすみませんでした。

先程プルリクを作成しました、ご確認の程よろしくお願いします。
