### ISSUE TITLE
ユーティリティ型 (utility type)にNoInferの追加

### ISSUE THREAD

**Issue by mikinovation** [yytypescript/book#850]
## 何をどうしたいか？

ユーティリティ型 (utility type)にNoInferの解説を追加したい

https://typescriptbook.jp/reference/type-reuse/utility-types

## そうしたい理由は何か？（誤植の修正など理由が自明な場合は不要）

Typescript5.4で追加された頻繁に使いそうなユーティリティ型だから

一度記事を書きましたが、サバイバルTypescriptに合わせてまとめようと思います

https://zenn.dev/gerunda/articles/20240307-ts-noinfer-frontend-component

## 着手可能になったら自分でプルリクエストを作成したいか？

自分で作成したい

**Comment by suin** [comment]
@mikinovation ご提案ありがとうございます！PRを心待ちにしております😆

**Comment by suin** [comment]
@mikinovation 遅くなりましたが、PRありがとうございました！マージしました😊
