### ISSUE TITLE
Typo: ログラミング言語 → プログラミング言語

### ISSUE THREAD

**Issue by stakiran** [yytypescript/book#851]
https://github.com/yytypescript/book/edit/master/docs/reference/values-types-variables/mental-model-of-types.md

before:

`ログラミング言語`

>このように型について一般化された知識を使うことで、ログラミング言語をスイッチするような場合でもスムーズに機能の類推や学習を行うことができるようになります。

after:

>このように型について一般化された知識を使うことで、プログラミング言語をスイッチするような場合でもスムーズに機能の類推や学習を行うことができるようになります。

**Comment by stakiran** [comment]
image
![image](https://github.com/yytypescript/book/assets/23325839/61b027a5-940d-4a30-9da7-d85726a14cbe)

**Comment by jamashita** [comment]
@stakiran 
ご報告ありがとうございます！
こちらで修正してしまっても良いでしょうか？

**Comment by stakiran** [comment]
問題ありません！

**Comment by jamashita** [comment]
@stakiran こちら修正いたしました！
今回はご報告いただきありがとうございました。今後ともサバイバルTypeScriptをよろしくお願いいたします 🙇
