### ISSUE TITLE
「型のメンタルモデル」ページの説明文と図が一致していない

### ISSUE THREAD

**Issue by igarashitakukmi** [yytypescript/book#852]
## 概要
説明文の修正提案です。

## 該当箇所
[部分型関係の解釈](https://typescriptbook.jp/reference/values-types-variables/mental-model-of-types#%E9%83%A8%E5%88%86%E5%9E%8B%E9%96%A2%E4%BF%82%E3%81%AE%E8%A7%A3%E9%87%88)

https://github.com/yytypescript/book/edit/master/docs/reference/values-types-variables/mental-model-of-types.md

## 問題点
説明文と図解が一致してないかも？
![CleanShot 2024-03-25 at 08 21 38@2x](https://github.com/yytypescript/book/assets/23009294/f004b551-3e23-4035-8f6b-6762b5ef3086)

## 修正提案
説明文を図に合わせる。

### AS IS
```
型Aが型Bの部分型であるとき~~~
```

### TO BE
```
型Bが型Aの部分型であるとき~~~
```

**Comment by yo-goto** [comment]
ご指摘ありがとうございます。
確かに下の図と上の文でA, B が対応していないので分かりづらくなっていました。
私の方で修正してしまって大丈夫でしょうか？

**Comment by igarashitakukmi** [comment]
> ご指摘ありがとうございます。
> 
> 確かに下の図と上の文でA, B が対応していないので分かりづらくなっていました。
> 
> 私の方で修正してしまって大丈夫でしょうか？

ご確認ありがとうございます。大丈夫です。
よろしくお願い致します！
