### ISSUE TITLE
typo :「みっつ」→「３つ」

### ISSUE THREAD

**Issue by koya-tech** [yytypescript/book#857]
## 何をどうしたいか？
以下のように「みっつ」を「３つ」に修正
https://github.com/yytypescript/book/blob/5394e8ca664b50ddcf9e8a43fae6c550c6856cb5/docs/reference/asynchronous/promise.md?plain=1#L10
※ただし同様の表現（みっつ）が他にも散見されているので、何かしらの意図がある場合はそのままで大丈夫です。
（検索の結果）他にも
async.mdで１か所
await.mdで１か所
promise.mdで５か所

## 着手可能になったら自分でプルリクエストを作成したいか？
自分で作成したい（が、他のtypo修正などのPRがあるならそのPRにまとめていただいても問題ないです）

**Comment by t-yng** [comment]
@koya-tech 
こちら、特に意図して「みっつ」としている訳ではないので、可能であれば修正して頂けると嬉しいです！

**Comment by koya-tech** [comment]
承知しました。
修正します
