### ISSUE TITLE
オプショナルプロパティに null を代入できました

### ISSUE THREAD

**Issue by specialweek1114** [yytypescript/book#859]
https://github.com/yytypescript/book/edit/master/docs/reference/values-types-variables/object/optional-property.md

## 問題
- 上記ページ内の説明ではオプショナルプロパティに null は代入できないと記載されていますが、下記環境ではエラーは再現しませんでした。``tsconfig.json`` に ``strictNullChecks": true`` を追加すると null を代入できなくなったので、これが正しい場合はページの記載内容の変更をお勧めいたします。

## 環境
- OS: Windows 10 Pro 22H2  WSL2 Ubuntu 20.04.6 LTS
- node: v20.11.1

## tsconfig.json
```json
{
    "compilerOptions": {
        "target": "es2021"
    }
}
```

**Comment by jamashita** [comment]
@specialweek1114 ご指摘ありがとうございます。
こちらですが、 @specialweek1114 さまが修正しPRを出される予定でしょうか？
それとも、我々のほうで修正してしまってもよろしいでしょうか？
お返事いただけますと幸いです

**Comment by specialweek1114** [comment]
@jamashita ご返信ありがとうございます。
修正いただいて問題ありません。よろしくお願いいたします。

**Comment by jamashita** [comment]
@specialweek1114 大変遅くなりすみません。
こちら対応いたしました。今回はご報告いただきありがとうございました。
また何かございましたら報告をよろしくお願いいたします 🙇 

https://typescriptbook.jp/reference/values-types-variables/object/optional-property
