### ISSUE TITLE
誤植:「プロパティをを変更して」→「プロパティを変更して」

### ISSUE THREAD

**Issue by imoken777** [yytypescript/book#867]
## 何をどうしたいか？
https://typescriptbook.jp/reference/advanced-topics/tsconfig-for-npm-package-developers#%E5%85%83%E3%81%AEts%E3%82%82%E5%85%AC%E9%96%8B%E3%81%99%E3%82%8B
 
「元のtsも公開する」の2行目の「プロパティをを変更して」を「プロパティを変更して」に修正

## そうしたい理由は何か？（誤植の修正など理由が自明な場合は不要）
誤植の修正

## 着手可能になったら自分でプルリクエストを作成したいか？
自分で作成したい

※ 着手可になってから、1ヶ月以上経過している場合は他の人が着手する可能性があります。

**Comment by t-yng** [comment]
@imoken777 
ありがとうございます！
普通に誤植ですね😇

修正して頂けると嬉しいです！！
