### ISSUE TITLE
不要な「,」削除

### ISSUE THREAD

**Issue by devland-jin** [yytypescript/book#875]
https://github.com/yytypescript/book/edit/master/docs/reference/type-reuse/utility-types/omit.md

不要な「,」が含まれていますので、削除の検討をお願いします。

![image](https://github.com/yytypescript/book/assets/165169962/ef9e837c-9606-4040-b1fa-c3e1ea5f206b)

**Comment by jamashita** [comment]
@devland-jin ご報告ありがとうございます。
こちら #888 にて修正いたしました。
またお気づきの点がございましたら報告いただけますと幸いです。よろしくお願いいたします 🙇
