### ISSUE TITLE
「keyof演算子」説明内の例文変更のお願い

### ISSUE THREAD

**Issue by devland-jin** [yytypescript/book#876]
https://github.com/yytypescript/book/edit/master/docs/README.md

例文は以下が良いと思いますが、いかがでしょうか。

(誤)
```
type Key = keyof Point
```

(正)
```
type Key = "x" | "y"
```

![image (1)](https://github.com/yytypescript/book/assets/165169962/97d4cbd5-8388-4e00-b166-6fdfa96e2185)

**Comment by suin** [comment]
ご報告ありがとうございます。
この吹き出しの部分はtwoslashが機械的に出している部分なので、twoslashではなくコメントで表現するようにしたほうがいいかもしれません。

**Comment by jamashita** [comment]
@devland-jin ご指摘ありがとうございます。
こちら #889  にて修正いたしました。
また何かございましたら報告いただけますと幸いです。よろしくお願いいたします。
