### ISSUE TITLE
誤字：出力が`さんさん`になる

### ISSUE THREAD

**Issue by aMitsukiAoyama** [yytypescript/book#878]
https://github.com/yytypescript/book/edit/master/docs/reference/functions/callback-functions.md

[このページの](https://typescriptbook.jp/reference/functions/callback-functions#関数の振る舞いの制御)部分での小さなミスをを見つけたので報告させていただきます。

```
function greetNewUser(func: (name: string) => string) {
  console.log(func("ご新規さん"));
}
 
function hello(name: string) {
  return `こんにちは！${name}さん！！`;
}
 
function goodMorning(name: string) {
  return `おはようございます！${name}さん！！`;
}
 
// こんにちは！ご新規さん!!
greetNewUser(hello);
 
// おはようございます！ご新規さん!!
greetNewUser(goodMorning);

```
このコードなのですが出力は「こんにちは！ご新規さんさん!!」と「おはようございます！ご新規さんさん!!」になるのではないでしょうか？
``` console.log(func("ご新規さん"));```の部分を``` console.log(func("ご新規"));```に変更するか、
```return `こんにちは！${name}さん！！`;```の部分を```return `こんにちは！${name}！！`;```
```return `おはようございます！${name}さん！！`;```の部分を```return `おはようございます！${name}！！`;```にするのが適切ではないかと思います。

**Comment by suin** [comment]
ご報告ありがとうございます！

**Comment by jamashita** [comment]
@aMitsukiAoyama ご指摘ありがとうございます。
こちら #887 で修正いたしまして反映いたしました。
今後も何かありましたら報告いただけますと幸いです。よろしくお願いいたします 🙇
