### ISSUE TITLE
ES Moduleのimportについての説明が間違っている

### ISSUE THREAD

**Issue by megazalrock** [yytypescript/book#880]
## 何をどうしたいか？

[ES moduleのimportについての説明](https://typescriptbook.jp/reference/import-export-require#import) についての下記引用部分ついて

> importは必ずファイルの一番上に書く必要があります。

とありますが、「importは必ずトップレベル（ブロックや関数の外）に書く必要があります。」と修正したいと思います。

## そうしたい理由は何か？

ES moduleにおいて `import` はファイルの先頭に書かなくてはいけないという制約はありません。
ただし、トップレベルに書く必要があるため、「トップレベル」という言葉の補足を加えたうえで修正したいと思います。

参考として、[MDNでは下記のように説明](https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Statements/import#%E8%AA%AC%E6%98%8E)されています。

> import 宣言はモジュールのトップレベル（要するにブロックや関数などの中以外）にのみ書くことができます。

## 着手可能になったら自分でプルリクエストを作成したいか？

自分で作成いたします。

**Comment by suin** [comment]
@megazalrock ご指摘の通りですね。PRいただけると嬉しいです！

**Comment by suin** [comment]
@megazalrock PRありがとうございました！マージしました！
