### ISSUE TITLE
誤植「大したものではないというが」→「大したものではないという`の`が」

### ISSUE THREAD

**Issue by htoyoda18** [yytypescript/book#882]
https://github.com/yytypescript/book/edit/master/docs/reference/values-types-variables/undefined-vs-null.md

[このページ](https://typescriptbook.jp/reference/values-types-variables/undefined-vs-null#%E4%BD%BF%E3%81%84%E5%88%86%E3%81%91%E6%84%8F%E8%AD%98%E3%82%92%E8%82%B2%E3%81%A6%E3%82%8B%E5%8A%B4%E5%8A%9B%E3%81%AF%E3%81%9D%E3%82%8C%E3%81%AB%E8%A6%8B%E5%90%88%E3%81%86%E3%83%A1%E3%83%AA%E3%83%83%E3%83%88%E3%81%8C%E5%B0%91%E3%81%AA%E3%81%84)にて、小さな誤りを見つけたので報告させていただきます。

「の」が抜けています。
> undefinedとnullを使い分けるメリットは大したものではないというが実際のところです

正しくは以下のようになると思われます： 「大したものではないというのが実際のところです」

**Comment by suin** [comment]
ご報告ありがとうございます！

**Comment by jamashita** [comment]
@htoyoda18 ご指摘ありがとうございます。
こちら #886 にてマージいたしました。
また何かございましたら報告していただけますと幸いです 🙇
