### ISSUE TITLE
symbolを含むオブジェクトをJSON.serializeするとそのプロパティは消えることを追記する

### ISSUE THREAD

**Issue by jamashita** [yytypescript/book#892]
## 何をどうしたいか？

掲題の通りです

## そうしたい理由は何か？（誤植の修正など理由が自明な場合は不要）

値にsymbolを含むオブジェクトを`JSON.stringify()`にかけるとそのキーごと消えることを紹介したいです
（厳密には値が `undefined` になる)

## 着手可能になったら自分でプルリクエストを作成したいか？
自分で作成します

※ 着手可になってから、1ヶ月以上経過している場合は他の人が着手する可能性があります。

**Comment by suin** [comment]
Close #326
