### ISSUE TITLE
誤植「特定の型を絞り込みことが」→「特定の型に絞り込むことが」 in 型ガード関数ページ

### ISSUE THREAD

**Issue by TakadaMasaya** [yytypescript/book#924]
## 何をどうしたいか？
[型ガード関数 (type guard function)](https://typescriptbook.jp/reference/functions/type-guard-functions) ページの2文目に、不自然に感じる表現がありましたので、修正したいです！
> 制御フロー分析の活用として、ifやswitchといった制御構造で型ガードを使用することによって各場所での変数を特定の型を絞り込みことができます。
```diff
- 特定の型を絞り込みことが
+ 特定の型に絞り込むことが
```

## 着手可能になったら自分でプルリクエストを作成したいか？
自分で作成したいです。

※ 着手可になってから、1ヶ月以上経過している場合は他の人が着手する可能性があります。

**Comment by suin** [comment]
PRを作成したいとのことなので、PRをいただけると嬉しいです！

**Comment by suin** [comment]
PRありがとうございました！
