### ISSUE TITLE
質問です

### ISSUE THREAD

**Issue by natsuki-engr** [yytypescript/book#926]
> varは変数の巻き上げが発生したタイミングでundefinedで変数を初期化している

https://typescriptbook.jp/reference/values-types-variables/vars-problems#%E5%A4%89%E6%95%B0%E3%81%AE%E5%B7%BB%E3%81%8D%E4%B8%8A%E3%81%92

文章中の上の記述によると、以下のコードでも`console.log`が入っているブロック内での`x`の巻き上げ時に`undefined`で初期化されるという理解です。
なので、`console.log`により`undefined`が出力される想定でしたが、実際には`1`が出力されました。
この理由は何故でしょうか？

```js
function output() {
  var x = 1;
  {
    console.log(x);
    var x = 2;
  }
}

output();
```

関連ページ: https://github.com/yytypescript/book/edit/master/docs/reference/values-types-variables/vars-problems.md

**Comment by suin** [comment]
@natsuki-engr この動作について説明させていただきます。

実際には、varによる変数の巻き上げ（hoisting）は**関数スコープ**で行われます。つまり、ブロックスコープ（`{}`）ではなく、function全体が変数の有効範囲となります。

上記のコードは、内部的には以下のように解釈されます：

```javascript
function output() {
  var x;  // 巻き上げにより関数スコープの先頭で宣言
  x = 1;  // 最初の代入
  {
    console.log(x); // この時点でxは1
    x = 2;  // 同じxに対する再代入
  }
}
```

ポイントは以下の通りです：

1. varは関数スコープなので、ブロック内の `var x = 2` は新しい変数を作るのではなく、既に存在する同じxを参照します
2. 巻き上げは関数の先頭で一度だけ行われ、ブロック内で新たな巻き上げは発生しません
3. そのため、`console.log(x)`が実行される時点では、既に`x = 1`による代入が完了しており、値は1となります

もし変数のスコープをブロックレベルにしたい場合は、letやconstを使用することが推奨されます：

```javascript
function output() {
  let x = 1;
  {
    console.log(x); // ReferenceError: Cannot access 'x' before initialization
    let x = 2;      // 新しいスコープでの宣言
  }
}
```

この場合は、ブロック内のxは新しい変数として扱われ、その巻き上げによりTDZ（Temporal Dead Zone）が発生するため、エラーとなります。​​​​​​​​​​​​​​​​

**Comment by natsuki-engr** [comment]
@suin 
ご回答いただき、ありがとうございます！
var変数の巻き上げは関数スコープ内のみ発生するということは、ifやforのブロックでも同様に巻き上げは起きないという事ですね。
理解できましたので、クローズさせていただきます。
