### ISSUE TITLE
誤植：any型は一見するとボトム型のよう→トップ型 in 型のメンタルモデル

### ISSUE THREAD

**Issue by nanikasi** [yytypescript/book#941]
## 何をどうしたいか？
[型のメンタルモデル](https://typescriptbook.jp/reference/values-types-variables/mental-model-of-types#%E3%83%88%E3%83%83%E3%83%97%E5%9E%8B) の記述に誤植があるので訂正

```
any型はnever型を除けばあらゆる型へも割当可能なため一見するとボトム型のように振る舞っているように見えますが、実際にはボトム型ではありません。
```
↓ ボトム型ではなくトップ型
```
any型はnever型を除けばあらゆる型へも割当可能なため一見するとトップ型のように振る舞っているように見えますが、実際にはトップ型ではありません。
```

## 着手可能になったら自分でプルリクエストを作成したいか？
自分で作成したい

※ 着手可になってから、1ヶ月以上経過している場合は他の人が着手する可能性があります。

**Comment by suin** [comment]
@yo-goto もし可能であれば一度確認いただけると嬉しいです！

**Comment by yo-goto** [comment]
@nanikasi 
issueとPRの作成ありがとうございます! 
当該ページを作成した者ですが、ここの文章の意としては「any型の変数にはあらゆる型の値を割当可能なのでany型はトップ型として振る舞っている一方で、逆に(neverを除く)あらゆる型の変数に対して割当可能でもあるのでボトム型としても振る舞っているように見えるが、実際にはボトム型ではない」ということを意図して書いておりました。


```ts
// ボトム型である変数 n はあらゆる型の変数に割当可能
declare const n: never;

const s1: unknown = n; // OK
const s2: number = n; // OK
const s3: never = n; // OK
```

実際any型の変数は以下のようにnever型の振る舞いと同じように見えます。

```ts
// 変数 a はneverを除くあらゆる型の変数に割当可能なのでボトム型のように振る舞っているように見える
declare const a: any;

const s1: unknown = a; // OK 
const s2: number = a; // OK
const s3: never = a; // NG: 割当不能
```

あらゆる型の変数**へ**割当可能であること(`const p1: {} = (1 as never)`)はボトム型の特徴であり、逆にあらゆる型の変数**から**割当可能(`const p2: unknown = 1`)であることはトップ型の特徴となります。

従って、ここでの文章は間違いではないですが、トップ型の説明で逆の性質を持つボトム型に言及してしまったので分かりづらくなってしまっていました。少し改修しようと思います🙇

**Comment by yo-goto** [comment]
厳密には any 型は漸進的型付けシステムにおいて一般化される Dynamic type という種類の型に分類されるので top/bottom とは異なる文脈で扱うべきものなのですが、top type である unknown が導入されるまでは実質的に top として扱われていたようなので top の一つとして説明していました。ちょっとこの辺も追加で説明を入れた方が混乱しないですむかもしれません。

**Comment by nanikasi** [comment]
@yo-goto cc @suin 
ご返信いただきりがとうございます！
> ここの文章の意としては「any型の変数にはあらゆる型の値を割当可能なのでany型はトップ型として振る舞っている一方で、逆に(neverを除く)あらゆる型の変数に対して割当可能でもあるのでボトム型としても振る舞っているように見えるが、実際にはボトム型ではない」ということを意図して書いておりました。

なるほど！理解しました！丁寧に回答いただきありがとうございます！
issueとPRはこちらでcloseさせていただきます！
