### ISSUE TITLE
マイナーフィードバック

### ISSUE THREAD

**Issue by utakokase** [yytypescript/book#98]
TECH PLAY女子部に参加させていただき、本書を使ってTypescriptを勉強させていただきました。（わざわざ参加者向けのメッセージやIssueのリンクを貼ってくださり、ありがとうございます！！）
とてもわかりやすく理解できました、本書を書いていただきありがとうございます！
もくもく会で読み進めるにあたって何点か気づいたことがありますので、フィードバックを書かせていただきます。

- `yarn start` を実行した後の yarnの抜け方 (Mac: Ctrl + C, Windows: ???) が書いてあるといいかなと思いました

- `brew install node`を実行すると最新のバージョンがインストールされますが、環境によっては最新ではなくLTSバージョンではないと`yarn start`時にエラーが出るようです。[こちらの記事](https://teratail.com/questions/366330)をご参照ください。
もくもく会では
```
nvm uninstall v17.0.1
nvm install --lts
```
を実行することによって最新のLTSバージョンを入れることによってyarnが無事動きました。本書に入れるかどうかの判断はお任せしますが、ご参考までにどうぞ。

- 「読んで学ぶTypeScript」の概要ページとその次のページが少し挙動不審でした。「概要ページ」に進んだかと思いきやタイトルは「値・型・変数」ページになっており、工事中のアイコンがないにもかかわらず何も表示されていませんでした。
- [こちらのページ](https://book.yyts.org/reference/values-types-variables/object/object-literal)に誤字がありました。「JSONは多くのプログラミング言語で用いら（れ）ていますが」

これからも本書の更新を楽しみにしております。

**Comment by suin** [comment]
@utakokase 嬉しいフィードバックありがとうございます！Reactいいねボタンのチュートリアルを試してくださった上でのフィードバック、とても役に立ちます。いずれのフィードバックも改善点に加えさせていただこうと思います😌
